import type {
  VideoGenerationProviderDefinition,
} from './video-generation.types';

export const GOOGLE_VEO_3_1_MODEL = 'veo-3.1-generate-preview';
export const GOOGLE_VEO_3_1_FAST_MODEL = 'veo-3.1-fast-generate-preview';
export const GOOGLE_VEO_3_1_LITE_MODEL = 'veo-3.1-lite-generate-preview';
export const MINIMAX_H3_MODEL = 'MiniMax-H3';
export const MINIMAX_H3_MAX_MODEL = 'MiniMax-H3-Max';
export const DOUBAO_SEEDANCE_2_MODEL = 'doubao-seedance-2-0-260128';
export const DOUBAO_SEEDANCE_2_FAST_MODEL = 'doubao-seedance-2-0-fast-260128';
export const VIDU_Q3_PRO_MODEL = 'viduq3-pro';
export const VIDU_Q3_TURBO_MODEL = 'viduq3-turbo';
export const VIDU_Q3_MIX_MODEL = 'viduq3-mix';
export const ZHIPU_COGVIDEOX_3_MODEL = 'cogvideox-3';
export const HUNYUAN_VIDEO_1_5_MODEL = 'hy-video-v1.5';
export const QWEN_WAN_3_MODEL = 'wan3.0-video';
export const QWEN_WAN_3_PRIME_MODEL = 'wan3.0-video-prime';

const GOOGLE_STANDARD_CAPABILITIES = {
  textToVideo: true,
  imageToVideo: true,
  firstLastFrame: true,
  referenceImages: true,
  referenceVideo: false,
  generatedAudio: true,
  silentOutput: false,
  durationSeconds: [4, 6, 8] as const,
  resolutions: ['720p', '1080p', '4k'] as const,
  aspectRatios: ['16:9', '9:16'] as const,
  maximumReferenceImages: 3,
  maximumReferenceVideos: 0,
} as const;

export const VIDEO_GENERATION_PROVIDER_CATALOG:
  readonly VideoGenerationProviderDefinition[] = [
    {
      providerKey: 'google',
      displayName: 'Google Veo',
      baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
      apiKeyUrl: 'https://aistudio.google.com/app/apikey',
      docsUrl: 'https://ai.google.dev/gemini-api/docs/veo',
      enabled: true,
      sortOrder: 10,
      models: [
        {
          modelKey: GOOGLE_VEO_3_1_MODEL,
          displayName: 'Veo 3.1',
          recommended: true,
          enabled: true,
          capabilities: GOOGLE_STANDARD_CAPABILITIES,
        },
        {
          modelKey: GOOGLE_VEO_3_1_FAST_MODEL,
          displayName: 'Veo 3.1 Fast',
          recommended: false,
          enabled: true,
          capabilities: GOOGLE_STANDARD_CAPABILITIES,
        },
        {
          modelKey: GOOGLE_VEO_3_1_LITE_MODEL,
          displayName: 'Veo 3.1 Lite',
          recommended: false,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: false,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: false,
            durationSeconds: [4, 6, 8],
            resolutions: ['720p', '1080p'],
            aspectRatios: ['16:9', '9:16'],
            maximumReferenceImages: 0,
            maximumReferenceVideos: 0,
          },
        },
      ],
    },
    {
      providerKey: 'minimax',
      displayName: 'MiniMax',
      baseUrl: 'https://api.minimax.io/v2',
      apiKeyUrl: 'https://platform.minimax.io/user-center/basic-information/interface-key',
      docsUrl: 'https://platform.minimax.io/docs/api-reference/video-generation-v2-create',
      enabled: true,
      sortOrder: 20,
      models: [
        {
          modelKey: MINIMAX_H3_MODEL,
          displayName: 'MiniMax H3',
          recommended: true,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: true,
            referenceVideo: true,
            generatedAudio: true,
            silentOutput: false,
            durationSeconds: { minimum: 4, maximum: 15 },
            resolutions: ['768p', '2k'],
            aspectRatios: ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 9,
            maximumReferenceVideos: 3,
          },
        },
        {
          modelKey: MINIMAX_H3_MAX_MODEL,
          displayName: 'MiniMax H3 Max',
          recommended: false,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: false,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: false,
            durationSeconds: { minimum: 5, maximum: 15 },
            resolutions: ['480p', '768p'],
            aspectRatios: ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 0,
            maximumReferenceVideos: 0,
          },
        },
      ],
    },
    {
      providerKey: 'doubao',
      displayName: '火山方舟 / Seedance',
      baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
      apiKeyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
      docsUrl: 'https://www.volcengine.com/docs/82379/1520757?lang=zh',
      enabled: true,
      sortOrder: 30,
      models: [
        {
          modelKey: DOUBAO_SEEDANCE_2_MODEL,
          displayName: 'Doubao Seedance 2.0',
          recommended: true,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: true,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: true,
            durationSeconds: { minimum: 4, maximum: 15 },
            resolutions: ['480p', '720p', '1080p', '4k'],
            aspectRatios: ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 9,
            maximumReferenceVideos: 0,
          },
        },
        {
          modelKey: DOUBAO_SEEDANCE_2_FAST_MODEL,
          displayName: 'Doubao Seedance 2.0 Fast',
          recommended: false,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: true,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: true,
            durationSeconds: { minimum: 4, maximum: 15 },
            resolutions: ['480p', '720p'],
            aspectRatios: ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 9,
            maximumReferenceVideos: 0,
          },
        },
      ],
    },
    {
      providerKey: 'vidu',
      displayName: 'Vidu',
      baseUrl: 'https://api.vidu.com/ent/v2',
      apiKeyUrl: 'https://platform.vidu.com/',
      docsUrl: 'https://platform.vidu.com/docs/',
      enabled: true,
      sortOrder: 40,
      models: [
        {
          modelKey: VIDU_Q3_PRO_MODEL,
          displayName: 'Vidu Q3 Pro',
          recommended: true,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: false,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: true,
            durationSeconds: { minimum: 1, maximum: 16 },
            resolutions: ['540p', '720p', '1080p'],
            aspectRatios: ['16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 0,
            maximumReferenceVideos: 0,
          },
        },
        {
          modelKey: VIDU_Q3_TURBO_MODEL,
          displayName: 'Vidu Q3 Turbo',
          recommended: false,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: true,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: true,
            durationSeconds: { minimum: 1, maximum: 16 },
            resolutions: ['540p', '720p', '1080p'],
            aspectRatios: ['16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 7,
            maximumReferenceVideos: 0,
          },
        },
        {
          modelKey: VIDU_Q3_MIX_MODEL,
          displayName: 'Vidu Q3 Mix',
          recommended: false,
          enabled: true,
          capabilities: {
            textToVideo: false,
            imageToVideo: false,
            firstLastFrame: false,
            referenceImages: true,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: true,
            durationSeconds: { minimum: 1, maximum: 16 },
            resolutions: ['720p', '1080p'],
            aspectRatios: ['16:9', '1:1', '9:16'],
            maximumReferenceImages: 7,
            maximumReferenceVideos: 0,
          },
        },
      ],
    },
    {
      providerKey: 'zhipu',
      displayName: '智谱 / CogVideoX',
      baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
      apiKeyUrl: 'https://bigmodel.cn/usercenter/proj-mgmt/apikeys',
      docsUrl: 'https://docs.bigmodel.cn/cn/guide/models/video-generation/cogvideox-3',
      enabled: true,
      sortOrder: 50,
      models: [
        {
          modelKey: ZHIPU_COGVIDEOX_3_MODEL,
          displayName: 'CogVideoX-3',
          recommended: true,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: false,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: true,
            durationSeconds: [5, 10],
            resolutions: ['720p', '1080p', '2k', '4k'],
            aspectRatios: ['16:9', '1:1', '9:16'],
            maximumReferenceImages: 0,
            maximumReferenceVideos: 0,
          },
        },
      ],
    },
    {
      providerKey: 'hunyuan',
      displayName: '腾讯混元 Video',
      baseUrl: 'https://tokenhub.tencentmaas.com/v1/wand/hunyuan-video',
      apiKeyUrl: 'https://tokenhub.tencentmaas.com/',
      docsUrl: 'https://cloud.tencent.com/document/product/1772/119195',
      enabled: true,
      sortOrder: 60,
      models: [
        {
          modelKey: HUNYUAN_VIDEO_1_5_MODEL,
          displayName: 'Hunyuan Video 1.5',
          recommended: true,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: false,
            referenceImages: false,
            referenceVideo: false,
            generatedAudio: false,
            silentOutput: true,
            durationSeconds: [5],
            resolutions: ['720p'],
            aspectRatios: ['16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 0,
            maximumReferenceVideos: 0,
          },
        },
      ],
    },
    {
      providerKey: 'qwen',
      displayName: '阿里云百炼 / Wan',
      baseUrl: 'https://dashscope.aliyuncs.com/api/v1',
      apiKeyUrl: 'https://bailian.console.aliyun.com/?apiKey=1&tab=model',
      docsUrl: 'https://help.aliyun.com/zh/model-studio/wan3-video-generation-api-reference',
      enabled: true,
      sortOrder: 70,
      models: [
        {
          modelKey: QWEN_WAN_3_MODEL,
          displayName: 'Wan 3.0 Video',
          recommended: true,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: true,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: true,
            durationSeconds: { minimum: 2, maximum: 30 },
            resolutions: ['480p', '720p', '1080p'],
            aspectRatios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 10,
            maximumReferenceVideos: 0,
          },
        },
        {
          modelKey: QWEN_WAN_3_PRIME_MODEL,
          displayName: 'Wan 3.0 Video Prime',
          recommended: false,
          enabled: true,
          capabilities: {
            textToVideo: true,
            imageToVideo: true,
            firstLastFrame: true,
            referenceImages: true,
            referenceVideo: false,
            generatedAudio: true,
            silentOutput: true,
            durationSeconds: { minimum: 2, maximum: 30 },
            resolutions: ['480p', '720p', '1080p'],
            aspectRatios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'],
            maximumReferenceImages: 10,
            maximumReferenceVideos: 0,
          },
        },
      ],
    },
  ] as const;
