export const MCP_RUNTIME_CONFIG = Symbol('MCP_RUNTIME_CONFIG');
export const MCP_AUTH_SESSION_REPOSITORY = Symbol('MCP_AUTH_SESSION_REPOSITORY');
export const MCP_OAUTH_STATE_REPOSITORY = Symbol('MCP_OAUTH_STATE_REPOSITORY');
export const MCP_AUDIT_SINK = Symbol('MCP_AUDIT_SINK');
