import {
  SPREADSHEET_PLAN_BORDER_STYLES,
  SPREADSHEET_PLAN_HORIZONTAL_ALIGNMENTS,
  SPREADSHEET_PLAN_PAPER_SIZES,
  SPREADSHEET_PLAN_VERTICAL_ALIGNMENTS,
  SPREADSHEET_RENDER_PLAN_VALUE_TYPES,
} from './spreadsheet-render-plan.types';

const positiveNumber = { type: 'number', exclusiveMinimum: 0 };
const nonNegativeInteger = { type: 'integer', minimum: 0 };
const positiveInteger = { type: 'integer', minimum: 1 };

export const SPREADSHEET_RENDER_PLAN_SCHEMA: Record<string, unknown> = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  type: 'object',
  additionalProperties: false,
  required: ['version', 'kind', 'objective', 'workbook', 'design', 'output'],
  properties: {
    version: { const: 'render-plan/v1' },
    kind: { const: 'spreadsheet' },
    objective: { $ref: '#/$defs/objective' },
    workbook: { $ref: '#/$defs/workbook' },
    design: { $ref: '#/$defs/design' },
    output: { $ref: '#/$defs/output' },
    rationale: { $ref: '#/$defs/rationale' },
  },
  $defs: {
    objective: {
      type: 'object',
      additionalProperties: false,
      required: ['purpose'],
      properties: {
        purpose: { type: 'string', minLength: 1 },
        audience: { type: 'string' },
        usage: { type: 'string' },
        language: { type: 'string' },
      },
    },
    rationale: {
      type: 'object',
      additionalProperties: false,
      properties: {
        structure: { type: 'string' },
        design: { type: 'string' },
      },
    },
    workbook: {
      type: 'object',
      additionalProperties: false,
      required: ['title', 'sheets'],
      properties: {
        title: { type: 'string', minLength: 1 },
        subtitle: { type: 'string' },
        sheets: {
          type: 'array',
          minItems: 1,
          maxItems: 100,
          items: { $ref: '#/$defs/sheet' },
        },
      },
    },
    sheet: {
      type: 'object',
      additionalProperties: false,
      required: ['name', 'blocks'],
      properties: {
        name: { type: 'string', minLength: 1 },
        title: { type: 'string' },
        subtitle: { type: 'string' },
        purpose: { type: 'string' },
        blocks: {
          type: 'array',
          minItems: 1,
          maxItems: 500,
          items: { $ref: '#/$defs/block' },
        },
        freeze: { $ref: '#/$defs/freeze' },
        page: { $ref: '#/$defs/page' },
      },
    },
    block: {
      oneOf: [
        { $ref: '#/$defs/textBlock' },
        { $ref: '#/$defs/tableBlock' },
        { $ref: '#/$defs/matrixBlock' },
        { $ref: '#/$defs/spacerBlock' },
      ],
    },
    textBlock: {
      type: 'object',
      additionalProperties: false,
      required: ['type', 'value'],
      properties: {
        type: { const: 'text' },
        value: { type: 'string' },
        style: { $ref: '#/$defs/cellStyle' },
        mergeAcross: positiveInteger,
        height: positiveNumber,
        spacingAfter: nonNegativeInteger,
      },
    },
    tableBlock: {
      type: 'object',
      additionalProperties: false,
      required: ['type', 'table'],
      properties: {
        type: { const: 'table' },
        table: { $ref: '#/$defs/table' },
        startColumn: positiveInteger,
      },
    },
    matrixBlock: {
      type: 'object',
      additionalProperties: false,
      required: ['type', 'matrix'],
      properties: {
        type: { const: 'matrix' },
        matrix: { $ref: '#/$defs/matrix' },
        merges: { $ref: '#/$defs/merges' },
        startColumn: positiveInteger,
        style: { $ref: '#/$defs/cellStyle' },
      },
    },
    spacerBlock: {
      type: 'object',
      additionalProperties: false,
      required: ['type'],
      properties: {
        type: { const: 'spacer' },
        rows: { type: 'integer', minimum: 1, maximum: 100 },
      },
    },
    table: {
      type: 'object',
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        title: { type: 'string' },
        caption: { type: 'string' },
        columns: {
          type: 'array',
          minItems: 1,
          maxItems: 300,
          items: { $ref: '#/$defs/column' },
        },
        rows: {
          type: 'array',
          maxItems: 100000,
          items: { type: 'object', additionalProperties: true },
        },
        summaryRows: {
          type: 'array',
          maxItems: 100000,
          items: { type: 'object', additionalProperties: true },
        },
        matrix: { $ref: '#/$defs/matrix' },
        merges: { $ref: '#/$defs/merges' },
        showHeader: { type: 'boolean' },
        autoFilter: { type: 'boolean' },
        freezeHeader: { type: 'boolean' },
        striped: { type: 'boolean' },
        compact: { type: 'boolean' },
        autoFit: { type: 'boolean' },
        note: { type: 'string' },
        styles: { $ref: '#/$defs/tableStyles' },
      },
      anyOf: [
        { required: ['matrix'] },
        { required: ['columns', 'rows'] },
        { required: ['columns', 'summaryRows'] },
      ],
    },
    column: {
      type: 'object',
      additionalProperties: false,
      required: ['key', 'header'],
      properties: {
        key: { type: 'string', minLength: 1 },
        header: { type: 'string' },
        type: { enum: SPREADSHEET_RENDER_PLAN_VALUE_TYPES },
        width: positiveNumber,
        minWidth: positiveNumber,
        maxWidth: positiveNumber,
        formula: { type: 'string', minLength: 1 },
        style: { $ref: '#/$defs/cellStyle' },
        headerStyle: { $ref: '#/$defs/cellStyle' },
        summaryStyle: { $ref: '#/$defs/cellStyle' },
        hidden: { type: 'boolean' },
      },
    },
    matrix: {
      type: 'array',
      minItems: 1,
      maxItems: 100000,
      items: {
        type: 'array',
        items: { $ref: '#/$defs/cell' },
      },
    },
    cell: {
      anyOf: [
        { type: ['string', 'number', 'boolean', 'null'] },
        { type: 'array' },
        { $ref: '#/$defs/cellSpec' },
        { $ref: '#/$defs/jsonObjectCellValue' },
      ],
    },
    cellValue: {
      anyOf: [
        { type: ['string', 'number', 'boolean', 'null'] },
        { type: 'array' },
        { type: 'object', additionalProperties: true },
      ],
    },
    cellSpec: {
      type: 'object',
      additionalProperties: false,
      minProperties: 1,
      properties: {
        kind: { enum: ['value', 'formula'] },
        value: { $ref: '#/$defs/cellValue' },
        text: { type: 'string' },
        formula: { type: 'string', minLength: 1 },
        result: { type: ['string', 'number', 'boolean', 'null'] },
        cachedResult: { type: ['string', 'number', 'boolean', 'null'] },
        type: { enum: SPREADSHEET_RENDER_PLAN_VALUE_TYPES },
        style: { $ref: '#/$defs/cellStyle' },
        note: { type: 'string' },
        hyperlink: { type: 'string' },
        colSpan: positiveInteger,
        rowSpan: positiveInteger,
        width: positiveNumber,
        height: positiveNumber,
      },
      allOf: [
        { not: { required: ['value', 'text'] } },
        {
          if: { required: ['formula'] },
          then: {
            not: {
              anyOf: [
                { required: ['value'] },
                { required: ['text'] },
                { required: ['hyperlink'] },
              ],
            },
          },
        },
        {
          if: { required: ['result'] },
          then: { required: ['formula'] },
        },
        {
          if: { required: ['cachedResult'] },
          then: { required: ['formula'] },
        },
        {
          if: {
            required: ['kind'],
            properties: { kind: { const: 'formula' } },
          },
          then: { required: ['formula'] },
        },
        {
          if: {
            required: ['type'],
            properties: { type: { const: 'formula' } },
          },
          then: { required: ['formula'] },
        },
      ],
    },
    jsonObjectCellValue: {
      type: 'object',
      additionalProperties: true,
      not: {
        anyOf: [
          { required: ['value'] },
          { required: ['text'] },
          { required: ['formula'] },
          { required: ['result'] },
          { required: ['type'] },
          { required: ['style'] },
          { required: ['note'] },
          { required: ['hyperlink'] },
          { required: ['colSpan'] },
          { required: ['rowSpan'] },
          { required: ['width'] },
          { required: ['height'] },
        ],
      },
    },
    cellStyle: {
      type: 'object',
      additionalProperties: false,
      properties: {
        fontName: { type: 'string', minLength: 1 },
        fontSize: positiveNumber,
        bold: { type: 'boolean' },
        italic: { type: 'boolean' },
        underline: { type: 'boolean' },
        strike: { type: 'boolean' },
        color: { type: 'string' },
        fill: { type: 'string' },
        numFmt: { type: 'string' },
        align: { enum: SPREADSHEET_PLAN_HORIZONTAL_ALIGNMENTS },
        verticalAlign: { enum: SPREADSHEET_PLAN_VERTICAL_ALIGNMENTS },
        wrapText: { type: 'boolean' },
        border: {
          anyOf: [
            { type: 'boolean' },
            { $ref: '#/$defs/cellBorder' },
          ],
        },
      },
    },
    cellBorder: {
      type: 'object',
      additionalProperties: false,
      properties: {
        top: { $ref: '#/$defs/borderEdge' },
        left: { $ref: '#/$defs/borderEdge' },
        bottom: { $ref: '#/$defs/borderEdge' },
        right: { $ref: '#/$defs/borderEdge' },
      },
    },
    borderEdge: {
      type: 'object',
      additionalProperties: false,
      properties: {
        style: { enum: SPREADSHEET_PLAN_BORDER_STYLES },
        color: { type: 'string' },
      },
    },
    tableStyles: {
      type: 'object',
      additionalProperties: false,
      properties: {
        title: { $ref: '#/$defs/cellStyle' },
        header: { $ref: '#/$defs/cellStyle' },
        body: { $ref: '#/$defs/cellStyle' },
        summary: { $ref: '#/$defs/cellStyle' },
        caption: { $ref: '#/$defs/cellStyle' },
      },
    },
    merges: {
      type: 'array',
      items: { $ref: '#/$defs/mergeRange' },
    },
    mergeRange: {
      type: 'object',
      additionalProperties: false,
      required: ['from', 'to'],
      properties: {
        from: { type: 'string', minLength: 1 },
        to: { type: 'string', minLength: 1 },
      },
    },
    freeze: {
      type: 'object',
      additionalProperties: false,
      properties: {
        row: nonNegativeInteger,
        column: nonNegativeInteger,
      },
    },
    pageMargins: {
      type: 'object',
      additionalProperties: false,
      properties: {
        left: positiveNumber,
        right: positiveNumber,
        top: positiveNumber,
        bottom: positiveNumber,
        header: positiveNumber,
        footer: positiveNumber,
      },
    },
    page: {
      type: 'object',
      additionalProperties: false,
      properties: {
        paperSize: { enum: SPREADSHEET_PLAN_PAPER_SIZES },
        orientation: { enum: ['portrait', 'landscape'] },
        fitToPage: { type: 'boolean' },
        fitToWidth: nonNegativeInteger,
        fitToHeight: nonNegativeInteger,
        margins: { $ref: '#/$defs/pageMargins' },
        header: { type: 'string' },
        footer: { type: 'string' },
        showPageNumber: { type: 'boolean' },
      },
    },
    design: {
      type: 'object',
      additionalProperties: false,
      required: [
        'fontName',
        'fontSize',
        'freezeHeader',
        'autoFilter',
        'autoFit',
        'striped',
        'compact',
        'wrapText',
        'defaultColumnWidth',
        'minColumnWidth',
        'maxColumnWidth',
      ],
      properties: {
        intent: { type: 'string' },
        fontName: { type: 'string', minLength: 1 },
        fontSize: positiveNumber,
        primaryColor: { type: 'string' },
        accentColor: { type: 'string' },
        headerFill: { type: 'string' },
        textColor: { type: 'string' },
        mutedColor: { type: 'string' },
        borderColor: { type: 'string' },
        summaryFill: { type: 'string' },
        zebraFill: { type: 'string' },
        freezeHeader: { type: 'boolean' },
        autoFilter: { type: 'boolean' },
        autoFit: { type: 'boolean' },
        striped: { type: 'boolean' },
        compact: { type: 'boolean' },
        wrapText: { type: 'boolean' },
        currencySymbol: { type: 'string' },
        defaultColumnWidth: positiveNumber,
        minColumnWidth: positiveNumber,
        maxColumnWidth: positiveNumber,
        defaultRowHeight: positiveNumber,
        page: { $ref: '#/$defs/page' },
      },
    },
    output: {
      type: 'object',
      additionalProperties: false,
      required: ['format', 'filename'],
      properties: {
        format: { const: 'xlsx' },
        filename: { type: 'string', minLength: 1 },
      },
    },
  },
};
