export const en = {
  'app.rendererFailed': 'Page rendering failed',
  'app.rendererLogHint': 'Open Developer Tools to inspect the renderer logs.',
  'app.startupFailed': 'SEEKMORE could not start the local session.',
  'app.desktopBridgeFailed': 'Desktop bridge failed to load. Restart SEEKMORE.',

  'settings.general': 'General',
  'settings.model': 'Model Settings',
  'settings.data': 'Data Management',
  'settings.help': 'Feedback & Help',
  'settings.moreComing': 'More settings are coming…',
  'settings.appearance': 'Appearance',
  'settings.appearance.light': 'Light',
  'settings.appearance.dark': 'Dark',
  'settings.language': 'Language',
  'settings.languageDescription': 'Choose the SEEKMORE interface language. Follow system uses your current device language.',
  'settings.followSystem': 'Follow system',
  'settings.simplifiedChinese': '简体中文',
  'settings.traditionalChinese': '繁體中文',
  'settings.english': 'English',
  'common.cancel': 'Cancel',
  'common.notAvailable': 'Not available',

  'chat.newConversation': 'New conversation',
  'chat.toggleSidebar': 'Toggle sidebar',
  'chat.openTimeRecords': 'Open time records',
  'chat.latestConversation': 'Already on the latest conversation',
  'chat.titleGenerating': 'Generating title',
  'chat.expand': 'Expand',

  'runtime.currentTask': 'Working on the current task',
  'runtime.tool.queued': '{{tool}} is waiting to run',
  'runtime.tool.running': 'Running {{tool}}',
  'runtime.tool.succeeded': '{{tool}} completed',
  'runtime.tool.failed': '{{tool}} failed',
  'runtime.clarification.waiting': 'Waiting for more information',
  'runtime.clarification.title': 'More information needed',
  'runtime.step.analysisFirst': 'Analyzing the task and planning execution',
  'runtime.step.analysisNext': 'Analyzing results from execution round {{round}}',
  'runtime.step.turnStart': 'Starting agent execution',
  'runtime.step.verification': 'Verifying execution result',
  'runtime.step.completed': 'Execution completed',
  'runtime.step.waiting': 'Waiting for continuation conditions',
  'runtime.step.failed': 'Execution failed: {{message}}',
  'runtime.result.failed': 'Tool execution failed',
  'runtime.result.completed': 'Tool execution completed',
  'runtime.result.confirmation': 'Waiting for confirmation',

  'runtime.status.queued': 'Queued',
  'runtime.status.running': 'Running',
  'runtime.status.waiting': 'Waiting',
  'runtime.status.blocked': 'Blocked',
  'runtime.status.succeeded': 'Completed',
  'runtime.status.failed': 'Failed',
  'runtime.status.partial': 'Partially completed',
  'runtime.status.cancelled': 'Cancelled',
  'runtime.status.skipped': 'Skipped',
  'runtime.detail.input': 'Input',
  'runtime.detail.output': 'Output',
  'runtime.detail.error': 'Error',
  'runtime.detail.evidence': 'Evidence',
  'runtime.clarification.inputNeeded': 'Your input is needed',

  'time.title': 'Time',
  'time.description': 'Reminders, events, alarms, and timers',
  'time.refresh': 'Refresh',
  'time.refreshing': 'Refreshing',
  'time.section.due': 'Due items',
  'time.section.records': 'Time records',
  'time.empty.due': 'No due items',
  'time.empty.records': 'No time records',
  'time.defaultReminderTitle': 'Time reminder',
  'time.reminderDue': 'Reminder is due',
  'time.kind.alarm': 'Alarm',
  'time.kind.reminder': 'Reminder',
  'time.kind.event': 'Event',
  'time.kind.countdown': 'Countdown',
  'time.kind.stopwatch': 'Stopwatch',
  'time.status.triggered': 'Due',
  'time.status.paused': 'Paused',
  'time.status.running': 'Running',
  'time.status.scheduled': 'Scheduled',
  'time.action.processing': 'Processing',
  'time.action.snooze5': 'Snooze 5 min',
  'time.action.snooze5Full': 'Remind me again in 5 minutes',
  'time.action.complete': 'Complete',
  'time.action.resume': 'Resume',
  'time.action.stop': 'Stop',
  'time.action.pause': 'Pause',
  'time.action.cancel': 'Cancel',

  'skills.source.BUILTIN': 'Official',
  'skills.source.REPOSITORY': 'Imported from GitHub',
  'skills.source.UPLOAD': 'Local import',
  'skills.source.INLINE': 'Created locally',
  'skills.source.IMPORTED': 'Local import',
  'skills.source.AI_GENERATED': 'Created by AI',
  'skills.source.UNKNOWN': 'Unknown source',
  'skills.activation.MANUAL': 'Manual only',
  'skills.activation.AUTOMATIC': 'Automatic',
  'skills.activation.ALWAYS': 'Always',
  'skills.activation.DISABLED': 'Disabled',
  'skills.version.DRAFT': 'Draft',
  'skills.version.VALIDATING': 'Validating',
  'skills.version.PUBLISHED': 'Available version',
  'skills.version.REJECTED': 'Rejected',
  'skills.version.SUPERSEDED': 'Previous version',
  'skills.agentActivation.INHERIT': 'Follow agent settings',
  'skills.agentActivation.MANUAL': 'Manual only',
  'skills.agentActivation.AUTOMATIC': 'Automatic',
  'skills.agentActivation.ALWAYS': 'Always',
  'skills.agentActivationDescription.INHERIT': 'Use the agent default Skill behavior',
  'skills.agentActivationDescription.MANUAL': 'Use only when explicitly selected by the user',
  'skills.agentActivationDescription.AUTOMATIC': 'Let the agent use it automatically when relevant',
  'skills.agentActivationDescription.ALWAYS': 'Load it for every task the agent performs',
  'skills.agentActivation.current': 'Currently {{mode}}',
  'skills.binding.summary': 'Linked Skills are ordered by enabled state and priority.',
  'skills.binding.count': '{{count}} items',
  'skills.binding.fallbackName': 'Linked Skill',
  'skills.binding.deleted': 'Deleted',
  'skills.binding.unavailable': 'Skill information is unavailable',
  'skills.binding.unlink': 'Unlink',
  'skills.binding.usageMode': 'Usage mode',
  'skills.binding.deletedPreserved': 'The link and settings are preserved and will resume after the Skill is restored',
  'skills.binding.priority': 'Priority',
  'skills.binding.priorityHint': '1 is first; smaller numbers have higher priority.',
  'skills.binding.restoreFirst': 'This Skill was deleted. Restore it first.',
  'skills.binding.enabledDeleted': 'Enabled (paused while deleted)',
  'skills.binding.pausedDeleted': 'Paused (Skill deleted)',
  'skills.binding.enabled': 'Enabled',
  'skills.binding.paused': 'Paused',

  'skills.settings.title': 'Skill usage settings',
  'skills.settings.defaultMode': 'Default agent usage mode',
  'skills.settings.defaultHint': 'Skills set to “Follow agent settings” use this default mode.',
  'skills.settings.linked': 'Linked Skills',
  'skills.settings.add': 'Add Skill',
  'skills.version.none': 'No version',
  'skills.loadingBindings': 'Loading linked Skills…',
  'agents.type.cognitive': 'Cognitive Agent',
  'agents.knowledge.status.READY': 'Ready',
  'agents.knowledge.status.PARSING': 'Parsing',
  'agents.knowledge.status.FAILED': 'Failed',
  'agents.knowledge.status.PENDING': 'Waiting to parse',

  'recycle.unnamedConversation': 'Untitled conversation',
  'recycle.messageCount': '{{count}} messages',
  'recycle.deletedAt': 'Deleted {{date}}',
  'recycle.purgeAt': 'Permanent deletion: {{date}}',
  'recycle.waitingCleanup': 'Waiting for cleanup',
  'recycle.remainingDays': '{{count}} day(s) remaining',
  'recycle.purgeSoon': 'Will be permanently deleted soon',
  'recycle.collapse': 'Collapse',
  'recycle.view': 'View',
  'recycle.restoring': 'Restoring…',
  'recycle.restore': 'Restore',
  'recycle.deleting': 'Deleting…',
  'recycle.deletePermanently': 'Delete permanently',
  'recycle.loadingMessages': 'Loading messages…',
  'recycle.noMessages': 'No messages to display.',
  'recycle.emptyMessage': '(empty message)',
  'recycle.download': 'Download',
  'common.role.USER': 'User',
  'common.role.ASSISTANT': 'Assistant',
  'common.role.SYSTEM': 'System',
  'common.role.TOOL': 'Tool',

  'agents.recycle.deleted': 'Deleted',
  'agents.recycle.noDescription': 'No description',
  'agents.recycle.conversationCount': '{{count}} conversations',
  'agents.recycle.messageCount': '{{count}} messages',
  'agents.recycle.restore': 'Restore',
  'agents.recycle.restoring': 'Restoring…',
  'agents.recycle.delete': 'Delete permanently',
  'agents.recycle.deleting': 'Deleting…',
  'agents.recycle.coverAlt': '{{name}} cover',
  'agents.recycle.avatarAlt': '{{name}} avatar',

  'memory.status.active': 'Active',
  'memory.status.pending_confirmation': 'Candidate',
  'memory.status.superseded': 'Superseded',
  'memory.status.deleted': 'Deleted',
  'memory.status.conflicted': 'Conflict',
  'memory.kind.identity': 'Identity',
  'memory.kind.preference': 'Preference',
  'memory.kind.constraint': 'Constraint',
  'memory.kind.project_state': 'Project state',
  'memory.kind.goal': 'Goal',
  'memory.kind.relationship': 'Relationship',
  'memory.kind.workflow': 'Workflow',
  'memory.kind.tool_preference': 'Tool preference',
  'memory.kind.event': 'Event',
  'memory.kind.episode': 'Episode',
  'memory.scope.user': 'User',
  'memory.scope.agent': 'Agent',
  'memory.scope.conversation': 'Conversation',
  'memory.source.user': 'Global memory',
  'memory.source.agent': 'Agent {{id}}',
  'memory.source.conversation': 'Conversation {{id}}',
  'memory.sensitivity.normal': 'Normal',
  'memory.sensitivity.private': 'Private',
  'memory.sensitivity.sensitive': 'Sensitive',
  'memory.sensitivity.restricted': 'Restricted',
  'memory.updatedAt': 'Updated {{date}}',
  'memory.usageCount': 'Used {{count}}',
  'memory.action.promote': 'Promote',
  'memory.action.restore': 'Restore',
  'memory.action.purge': 'Clear',
  'memory.action.delete': 'Delete',

  'skills.picker.deleted': 'Deleted',
  'skills.picker.deletedLinkedHint': 'The link and settings are preserved and will resume after restore',
  'skills.picker.deletedUnlinkedHint': 'This Skill is deleted. Restore it before linking',
  'skills.picker.createdAt': 'Created {{date}}',
  'skills.picker.unlink': 'Unlink',
  'skills.picker.deletedCannotLink': 'Deleted Skills cannot be linked',
  'skills.picker.linkTitle': 'Link Skill',
  'skills.picker.link': 'Link',

  'tools.file.search.name': 'Search files',
  'tools.file.read.name': 'Read file',
  'tools.file.write.name': 'Write file',
  'tools.file.patch.name': 'Patch file',
  'tools.file.delete.name': 'Delete file',
  'tools.terminal.run.name': 'Run terminal command',
  'tools.python.execute.name': 'Run Python',
  'tools.knowledge.search.name': 'Search knowledge',
  'tools.web.search.name': 'Search the web',

  'tools.skill_search.name': 'Search Skills',
  'tools.skill_view.name': 'Load Skill',
  'tools.skill_read_resource.name': 'Read Skill Resource',
  'tools.time.name': 'Time',
  'tools.automation.name': 'Automation',
  'tools.image.generate.name': 'Generate Image',
  'tools.speech.synthesize.name': 'Generate Speech',
  'tools.voice.clone.name': 'Clone Voice',
  'tools.music.generate.name': 'Generate Music',
  'tools.video.general.name': 'Generate Video',
  'tools.video.generate.name': 'Generate Video',
  'tools.location.name': 'Location',
  'tools.vision.analyze.name': 'Analyze Image',
  'tools.web.read.name': 'Web Read',
  'tools.repository.inspect.name': 'Inspect Repository',
  'tools.repository.list_tree.name': 'List Repository Tree',
  'tools.repository.read_file.name': 'Read Repository File',
  'tools.workspace.inspect.name': 'Inspect Workspace',
  'tools.terminal.read.name': 'Read Terminal Session',
  'tools.terminal.kill.name': 'Stop Terminal Session',
  'tools.git.status.name': 'Git Status',
  'tools.git.diff.name': 'Git Diff',
  'tools.document.parse.name': 'Parse Document',
  'tools.object.search.name': 'Search Uploaded Files',
  'tools.object.inspect.name': 'Inspect Uploaded File',
  'tools.code_project.inspect.name': 'Inspect Code Project',
  'tools.document.render.docx.name': 'Render DOCX',
  'tools.document.render.pdf.name': 'Render PDF',
  'tools.spreadsheet.render.xlsx.name': 'Render XLSX',
  'tools.presentation.create.name': 'Create Presentation',
  'tools.presentation.slides.upsert.name': 'Create or Update Slides',
  'tools.presentation.inspect.name': 'Inspect Presentation',
  'tools.presentation.finalize.name': 'Finalize Presentation',
  'tools.presentation.render.pptx.name': 'Render PPTX',
  'tools.package.render.zip.name': 'Render ZIP Package',
  'tools.plugins.mcp_manage.name': 'Manage MCP',

                                        

  'agents.system.seekmore-system-agent.description': 'Work easy Live easy.',

  'explore.action.added': 'Added',
  'explore.action.authorize': 'Authorize',
  'explore.action.add': 'Add',
  'explore.action.installed': 'Installed',
  'explore.action.install': 'Install',
  'explore.action.connected': 'Connected',
  'explore.action.connecting': 'Connecting',
  'explore.action.reconnect': 'Reconnect',
  'explore.action.configure': 'Configure',
  'explore.action.reconfigure': 'Reconfigure',
  'explore.action.setup': 'Set up',
  'explore.action.disabled': 'Disabled',
  'explore.action.connect': 'Connect',
  'explore.type.agent': 'Cognitive Agent',
  'explore.type.skill': 'SKILL',
  'explore.coverAlt': '{{name}} cover',
  'explore.avatarAlt': '{{name}} avatar',
  'explore.noProductIntroduction': 'No product introduction',
  'explore.noMcpDescription': 'No MCP capability description',
  'common.noDescription': 'No description',

  'agents.loading': 'Loading agents…',
  'agents.empty': 'No agents yet.',
  'agents.goChat': 'Go to chat',
  'agents.processing': 'Processing…',
  'agents.systemDefault': 'System default',
  'agents.coverAlt': '{{name}} cover',
  'agents.avatarAlt': '{{name}} avatar',
  'common.back': 'Back',

  'mcp.status.disabled': 'Disabled',
  'mcp.status.authorizationRequired': 'Authorization required',
  'mcp.status.setupRequired': 'Setup required',
  'mcp.status.configurationRequired': 'Configuration required',
  'mcp.status.connected': 'Connected',
  'mcp.status.connecting': 'Connecting',
  'mcp.status.failed': 'Connection failed',
  'mcp.status.disconnected': 'Not connected',
  'mcp.action.waitingAuthorization': 'Waiting for authorization…',
  'mcp.action.authorize': 'Authorize',
  'mcp.action.setup': 'Set up',
  'mcp.action.reconfigure': 'Reconfigure',
  'mcp.action.configure': 'Configure',
  'mcp.action.connecting': 'Connecting…',
  'mcp.action.reconnect': 'Reconnect',
  'mcp.action.connect': 'Connect',
  'mcp.action.reauthorize': 'Reauthorize',
  'mcp.action.refreshing': 'Refreshing',
  'mcp.action.refresh': 'Refresh',
  'mcp.action.revoke': 'Disconnect account',
  'mcp.action.uninstall': 'Uninstall',
  'mcp.action.disable': 'Disable',
  'mcp.action.enable': 'Enable',
  'approval.timeline.waiting.title': 'Approval required',
  'approval.timeline.waiting.summary': 'Tool {{tool}} will perform a controlled operation',
  'approval.timeline.resolved.approved': 'Execution approved',
  'approval.timeline.resolved.cancelled': 'Execution cancelled',
  'approval.timeline.resolved.workspaceChanged': 'The workspace changed, so pending operations for the previous workspace were cancelled',
  'approval.timeline.resolved.policyChanged': 'The approval mode changed, so the current operation was handled under the updated policy',
  'approval.card.title': 'Approval required',
  'approval.action.allowOnce': 'Allow once',
  'approval.action.auditOnly': 'Approve for me',
  'approval.action.fullAccessTask': 'Full access for this task',
  'approval.action.reject': 'Reject',
  'approval.checkpointCreating': 'Creating a recoverable approval checkpoint…',
  'errors.requestFailed': 'Request failed. Please try again.',
  'errors.UNAUTHORIZED': 'The local session is unavailable. Please retry.',
  'errors.AUTHORIZATION_HEADER_INVALID': 'Authorization header is missing or invalid.',
  'errors.ACCESS_TOKEN_REQUIRED': 'Access token is required.',
  'errors.ACCESS_TOKEN_INVALID': 'The access token is invalid or has expired.',
  'errors.WORKSPACE_PARENT_UNAVAILABLE': 'The selected parent folder does not exist or cannot be accessed.',
  'errors.WORKSPACE_PARENT_OUTSIDE_ROOT': 'The parent folder is outside the allowed workspace root.',
  'errors.WORKSPACE_PROJECT_EXISTS': 'The project folder already exists.',
  'errors.WORKSPACE_CREATE_FAILED': 'The project folder could not be created.',
  'errors.WORKSPACE_UNREADABLE': 'The project folder cannot be read after creation.',
  'errors.WORKSPACE_UNAVAILABLE': 'The selected workspace folder does not exist or cannot be accessed.',
  'errors.WORKSPACE_ROOT_FORBIDDEN': 'The filesystem root cannot be registered as a workspace.',
  'errors.WORKSPACE_SENSITIVE_PATH_FORBIDDEN': 'A system-sensitive folder cannot be registered as a workspace.',
  'errors.WORKSPACE_PROJECT_NAME_INVALID': 'The project name is invalid.',
  'errors.WORKSPACE_PATH_INVALID': 'The project path is invalid.',
  'errors.AGENT_NOT_FOUND': 'The agent does not exist.',
  'errors.AGENT_ACCESS_DENIED': 'You do not have access to this agent.',
  'errors.SYSTEM_AGENT_REMOVE_FORBIDDEN': 'The SEEKMORE system assistant cannot be removed.',
  'errors.SYSTEM_AGENT_DELETE_FORBIDDEN': 'The SEEKMORE system assistant cannot be deleted.',
  'errors.COGNITIVE_AGENT_NOT_FOUND': 'The cognitive agent does not exist.',
  'errors.COGNITIVE_AGENT_ACCESS_DENIED': 'You do not have access to this cognitive agent.',
  'errors.COGNITIVE_AGENT_OWNER_REQUIRED': 'Only the owner can perform this action.',
  'errors.COGNITIVE_AGENT_SYSTEM_MANAGED': 'The SEEKMORE system assistant is managed by the system and cannot be modified.',
  'errors.KNOWLEDGE_FILE_NOT_FOUND': 'The knowledge-base file does not exist.',
  'errors.KNOWLEDGE_FILE_EMPTY': 'No searchable content could be parsed from the knowledge-base file.',
  'errors.CONVERSATION_NOT_FOUND': 'The conversation does not exist.',
  'errors.CONVERSATION_ACCESS_DENIED': 'You do not have access to this conversation.',
  'errors.MESSAGE_NOT_FOUND': 'The message does not exist.',
  'agents.capability.chat.name': 'Chat',
  'agents.capability.chat.description': 'Allow the agent to handle basic conversation and Q&A.',
  'agents.capability.file_reading.name': 'Read files',
  'agents.capability.file_reading.description': 'Allow the agent to read uploaded knowledge-base and file content.',
  'agents.capability.file_render.name': 'Generate files',
  'agents.capability.file_render.description': 'Allow the agent to use internal rendering capabilities to create deliverable files.',
  'agents.capability.docx_generation.name': 'Generate Word documents',
  'agents.capability.docx_generation.description': 'Allow the agent to generate Word documents.',
  'agents.capability.xlsx_generation.name': 'Generate Excel workbooks',
  'agents.capability.xlsx_generation.description': 'Allow the agent to generate Excel workbooks.',
  'agents.capability.web_search.name': 'Web search',
  'agents.capability.web_search.description': 'Allow the agent to use external search when current, official, or source-backed information is needed.',
  'agents.capability.image_generation.name': 'Image generation',
  'agents.capability.image_generation.description': 'Allow the agent to use external image-generation tools.',
  'agents.validation.NAME_TOO_SHORT': 'The name is too short.',
  'agents.validation.DESCRIPTION_WEAK': 'The description is too short; describe the intended use and core capabilities.',
  'agents.validation.ROLE_PROMPT_WEAK': 'The role instructions are too short to establish stable behavior.',
  'agents.validation.NO_CAPABILITIES': 'Configure at least one capability.',
  'agents.validation.KNOWLEDGE_PARSE_FAILED': '{{count}} knowledge-base file(s) failed to parse.',
  'agents.validation.KNOWLEDGE_PARSE_PENDING': '{{count}} knowledge-base file(s) are waiting to be parsed.',
  'errors.KNOWLEDGE_FILE_SELECTION_REQUIRED': 'Select at least one knowledge-base file to upload.',
  'errors.COGNITIVE_AGENT_DELETED_NOT_FOUND': 'The deleted cognitive agent does not exist.',
  'errors.COGNITIVE_AGENT_RETENTION_EXPIRED': 'This cognitive agent is past its 30-day retention period and cannot be restored.',
  'errors.COGNITIVE_AGENT_OWNER_RELATION_MISSING': 'The ownership relation is missing, so this cognitive agent cannot be restored.',
  'errors.AGENT_PROFILE_FILE_EMPTY': 'The {{field}} file is empty.',
  'errors.AGENT_PROFILE_FILE_WRITE_FAILED': 'The {{field}} file could not be written.',
  'errors.KNOWLEDGE_FILE_CONTENT_EMPTY': 'Knowledge-base file {{fileName}} is empty.',
  'errors.KNOWLEDGE_FILE_WRITE_FAILED': 'Knowledge-base file {{fileName}} could not be written.',
  'errors.operationFailed': 'Operation failed.',
  'errors.explore.loadFailed': 'Explore could not be loaded.',
  'errors.mcp.operationFailed': 'MCP operation failed.',
  'errors.mcp.statusLoadFailed': 'MCP status could not be loaded.',
  'errors.mcp.globalToggleFailed': 'The MCP global switch could not be updated.',
  'errors.mcp.toggleFailed': 'The MCP switch could not be updated.',
  'errors.mcp.loadFailed': 'MCP could not be loaded.',
  'errors.mcp.refreshFailed': 'MCP status could not be refreshed.',
  'errors.mcp.connectStartFailed': 'The MCP connection could not be started.',
  'errors.mcp.oauthFailed': 'MCP OAuth authorization failed.',
  'errors.mcp.directoryLoadFailed': 'The MCP directory could not be loaded.',
  'errors.MCP_CONFIGURATION_REQUIRED': 'Complete the MCP connection configuration first.',
  'errors.MCP_GLOBALLY_DISABLED': 'The MCP global switch is off. Turn it on first.',
  'errors.MCP_INSTALLATION_DISABLED': 'This MCP is disabled. Enable it before connecting.',
  'errors.MCP_CREDENTIAL_NOT_REQUIRED': 'This MCP does not require access credentials.',
  'errors.MCP_CREDENTIAL_VALUES_INVALID': 'The connection configuration is incomplete or invalid.',
  'errors.MCP_CREDENTIAL_KEY_NOT_DECLARED': 'The supplied configuration field is not declared by this MCP.',
  'errors.MCP_CREDENTIAL_DECLARATION_INCOMPLETE': 'Complete all required connection fields.',
  'errors.MCP_BEARER_TOKEN_REQUIRED': 'Enter an access token.',
  'errors.MCP_API_KEY_REQUIRED': 'Enter an API key.',
  'errors.MCP_HEADER_VALUE_INVALID': 'The request-header configuration is invalid.',
  'errors.MCP_AUTHORIZATION_REQUIRED': 'Sign in and authorize this MCP service first.',
  'errors.MCP_OAUTH_AUTHORIZATION_REQUIRED': 'Sign in and authorize this MCP service first.',
  'errors.MCP_LOCAL_SETUP_REQUIRED': 'Complete the local or self-hosted service setup first.',
  'errors.MCP_CREDENTIAL_INVALID': 'The current credential is invalid. Reconfigure it.',
  'errors.MCP_CONNECTION_FAILED': 'MCP connection failed. Check the service address and access credentials.',
  'errors.MCP_DESKTOP_BRIDGE_UNAVAILABLE': 'The desktop connection service is unavailable. Use SEEKMORE Desktop for this action.',
  'common.actions.collapse': 'Collapse',
  'common.actions.expandAll': 'Expand all',
  'common.actions.edit': 'Edit',
  'common.actions.pause': 'Pause',
  'common.actions.resume': 'Resume',
  'common.actions.save': 'Save',
  'automation.errors.actionFailed': 'Automation action failed. Please try again.',
  'automation.errors.required': 'Task name and instructions are required.',
  'automation.errors.invalidRunAt': 'Choose a valid run time.',
  'automation.cancel.confirmTitle': 'End “{{title}}”?',
  'automation.cancel.confirmDescription': 'This task will no longer run automatically. Message history will be kept.',
  'automation.actions.end': 'End task',
  'automation.fields.frequency': 'Frequency',
  'automation.fields.delivery': 'Reporting',
  'automation.fields.endAt': 'End time',
  'automation.fields.maxRuns': 'Maximum runs',
  'automation.fields.completionCondition': 'Completion condition',
  'automation.fields.validity': 'Validity',
  'automation.fields.nextRun': 'Next run',
  'automation.fields.remaining': 'Remaining',
  'automation.fields.completedAt': 'Completed at',
  'automation.fields.title': 'Task name',
  'automation.fields.instruction': 'Instructions',
  'automation.fields.every': 'Every',
  'automation.fields.unit': 'Unit',
  'automation.fields.maxRunsInput': 'Maximum run count',
  'automation.fields.runAt': 'Run time',
  'automation.fields.nextStartOptional': 'Next start time (optional)',
  'automation.delivery.always': 'Report after every run',
  'automation.delivery.onCompletion': 'Report when completion condition is met',
  'automation.validity.indefinite': 'Until manually ended',
  'automation.validity.indefiniteLong': 'Run indefinitely until I end it manually',
  'automation.status.ACTIVE': 'Running',
  'automation.status.PAUSED': 'Paused',
  'automation.status.COMPLETED': 'Completed',
  'automation.status.CANCELLED': 'Ended',
  'automation.unit.minute': 'minute',
  'automation.unit.hour': 'hour',
  'automation.unit.day': 'day',
  'automation.unit.week': 'week',
  'automation.frequency.once': 'Once · {{time}}',
  'automation.frequency.everyOne': 'Every {{unit}}',
  'automation.frequency.everyMany': 'Every {{count}} {{unit}}',
  'automation.completion.default': 'End automatically when the configured condition is met',
  'automation.remaining.soon': 'Ending soon',
  'automation.remaining.days': '{{count}} day(s)',
  'automation.remaining.hours': '{{count}} hour(s)',
  'automation.unit.times': 'times',
  'common.actions.deleting': 'Deleting…',
  'common.actions.delete': 'Delete',
  'common.actions.title': 'Actions',
  'common.iconAlt': '{{name}} icon',
  'common.status.deleted': 'Deleted',
  'common.priority': 'Priority',
  'common.basicInfo': 'Basic information',
  'common.type': 'Type',
  'common.visibility': 'Visibility',
  'common.createdAt': 'Created',
  'common.updatedAt': 'Updated',
  'common.untitledFile': 'Untitled file',
  'agents.skills.loadFailed': 'Failed to load linked Skills',
  'agents.detail.unsupportedEditor': 'This agent type is not connected to an editor yet.',
  'agents.detail.unsupportedDelete': 'Deletion for this agent type is not available yet.',
  'agents.detail.deleteFailed': 'Delete failed. Please try again.',
  'agents.knowledge.title': 'Knowledge',
  'agents.knowledge.search': 'Knowledge search',
  'agents.knowledge.available': 'Available',
  'agents.knowledge.waitingReady': 'Waiting for files to be ready',
  'agents.knowledge.noSearchable': 'No searchable files yet',
  'agents.knowledge.fileCount': '{{count}} file(s)',
  'agents.knowledge.parsing': 'Parsing…',
  'agents.knowledge.reparse': 'Reparse',
  'agents.knowledge.uploading': 'Uploading…',
  'agents.knowledge.add': 'Add files',
  'agents.knowledge.loading': 'Loading knowledge…',
  'agents.knowledge.empty': 'No knowledge files have been uploaded for this agent.',
  'agents.knowledge.deleteConfirmTitle': 'Delete this knowledge file?',
  'agents.knowledge.deleteConfirmDescription': 'Remove “{{name}}” from this agent’s knowledge base? It will no longer be used for knowledge search.',
  'agents.skills.title': 'Linked Skills',
  'agents.skills.count': '{{count}}',
  'agents.skills.empty': 'No Skills are linked to this cognitive agent.',
  'agents.role.title': 'Role instructions',
  'agents.role.empty': 'No role instructions',
  'agents.actions.goChat': 'Go to chat',
  'agents.actions.edit': 'Edit agent',
  'agents.actions.delete': 'Delete agent',
  'agents.delete.confirmTitle': 'Delete this agent?',
  'agents.delete.confirmDescription': 'The agent will be disabled and moved to Deleted. Its settings and history will be kept for 30 days and can be restored during that period. After retention expires, it will be permanently deleted.',
  'agents.title': 'Cognitive Agents',
  'agents.library.mine': 'My cognitive agents',
  'agents.library.deletedDescription': 'Deleted agents are retained for 30 days and can be restored during that period. After retention expires they are permanently deleted.',
  'agents.library.description': 'Manage the cognitive, reasoning, and collaborative agents you create.',
  'agents.actions.create': '+ Create cognitive agent',
  'agents.library.count': '{{count}} cognitive agent(s)',
  'agents.purge.confirmTitle': 'Permanently delete this cognitive agent?',
  'agents.purge.confirmDescription': 'This permanently deletes all settings for “{{name}}”, {{conversationCount}} conversation(s), {{messageCount}} message(s), knowledge, Skill links, and runtime data. This cannot be undone.',
  'agents.actions.purge': 'Permanently delete',
  'common.coverAlt': '{{name}} cover',
  'common.processing': 'Processing…',
  'common.author': 'Author',
  'common.source': 'Source',
  'skills.detail.loadFailed': 'Failed to load Skill',
  'skills.detail.restoreFailed': 'Failed to restore Skill',
  'skills.detail.statusUpdateFailed': 'Failed to update Skill status',
  'skills.detail.deleteFailed': 'Failed to delete Skill',
  'skills.detail.loading': 'Loading Skill…',
  'skills.detail.draftVersion': 'Draft version',
  'skills.detail.unknownAuthor': 'Unknown author',
  'skills.detail.activationMode': 'Activation mode',
  'skills.detail.bindingCount': 'Bindings',
  'skills.detail.usageCount': 'Uses',
  'skills.detail.versionCount': 'Versions',
  'skills.detail.retentionInfo': 'Deletion retention',
  'skills.detail.retention30Days': 'Retained for 30 days',
  'skills.detail.deletedAt': 'Deleted at',
  'skills.detail.purgeAt': 'Scheduled permanent deletion',
  'skills.detail.restoreScopeHint': 'Restoring only restores the Skill itself. Agent bindings, conversation activations, and installation records that were disabled by deletion are not automatically re-enabled.',
  'skills.detail.noMarkdown': 'No SKILL.md content',
  'skills.detail.restoring': 'Restoring…',
  'skills.detail.restore': 'Restore',
  'skills.detail.edit': 'Edit Skill',
  'skills.detail.archive': 'Archive Skill',
  'skills.detail.delete': 'Delete Skill',
  'skills.detail.currentVersion': 'Current version',
  'skills.detail.trustLevel': 'Trust level',
  'skills.detail.installCount': 'Installations',
  'skills.detail.lastUsed': 'Last used',
  'skills.detail.versionHistory': 'Version history',
  'skills.detail.versionCountValue': '{{count}} version(s)',
  'skills.detail.noVersionRecords': 'No version history.',
  'skills.detail.deleteConfirmTitle': 'Delete this Skill?',
  'skills.detail.deleteConfirmDescription': 'The Skill will move to Deleted and be removed from My Skills and active usage locations. It can be restored during the retention period.',
  'common.actions.close': 'Close',
  'common.loading': 'Loading…',
  'common.optional': 'Optional',
  'common.files': 'Files',
  'common.saving': 'Saving…',
  'skills.editor.templateDescription': 'Describe what this Skill does and when it should be used.',
  'skills.editor.templateHeading': 'Instructions',
  'skills.editor.templateBody': 'Write reusable execution steps here.',
  'skills.editor.loadFailed': 'Failed to load Skill',
  'skills.editor.prepareDraftFailed': 'Failed to prepare an editable draft version',
  'skills.editor.fileRefreshFailed': 'Failed to refresh files',
  'skills.editor.saveFailed': 'Failed to save Skill',
  'skills.editor.editTitle': 'Edit Skill',
  'skills.editor.createTitle': 'Create Skill',
  'skills.editor.description': 'Edit the native SKILL.md and version files. Published versions are copied into a new editable draft first.',
  'skills.editor.name': 'Skill name',
  'skills.editor.namePlaceholder': 'For example: Frontend Design - General',
  'skills.editor.nameHint': 'Use a clear display name. The system maintains the internal identifier.',
  'skills.editor.editSource': 'Editing source',
  'skills.editor.newDocument': 'New document',
  'skills.editor.versionFiles': 'Version files',
  'skills.editor.fileCount': '{{count}} file(s)',
  'skills.editor.noVersionYet': 'No version created yet',
  'skills.editor.changeLog': 'Version notes',
  'skills.editor.package.main': 'SKILL.md · Main instruction document',
  'skills.editor.package.reference': 'REFERENCE · Reference material',
  'skills.editor.package.script': 'SCRIPT · Executable scripts',
  'skills.editor.package.asset': 'ASSET · Static assets',
  'skills.editor.package.other': 'LICENSE / OTHER · Other files',
  'skills.editor.diagnostics': 'Validation diagnostics',
  'skills.editor.diagnosticLocation': 'Line {{line}}{{column}} · ',
  'skills.editor.filesCreateFirst': 'Create the Skill draft first, then upload reference, script, asset, license, and other version files.',
  'skills.editor.preparingDraft': 'Creating an editable draft version…',
  'skills.editor.currentVersionLocked': 'The current version cannot be edited directly. A new draft is being prepared from it.',
  'skills.editor.saveNewVersion': 'Save new version',
  'common.actions.add': '+ Add',
  'skills.create.recognition.waiting': 'Waiting for automatic detection…',
  'skills.create.recognition.inspecting': 'Detecting Skill Package…',
  'skills.create.recognition.standard': 'Detected · Standard compatible',
  'skills.create.recognition.compatible': 'Detected · Compatibility mode',
  'skills.create.recognition.rejected': 'Detection complete · Blocking errors found',
  'skills.create.recognition.idle': 'Detection starts after upload or input',
  'skills.create.importTitle': 'Import Skill',
  'skills.create.nameHint': 'Use a clear name in your preferred language. The system generates and maintains the stable internal identifier.',
  'skills.create.instructions': 'Instructions',
  'skills.create.instructionsPlaceholder': 'Describe what the Skill does and when the Agent should use it.',
  'skills.create.license': 'Open-source license',
  'skills.create.compatibility': 'Compatibility notes',
  'skills.create.compatibilityPlaceholder': 'Only fill this in when explicit runtime environment requirements exist.',
  'skills.create.metadataHint': 'Keys and values are stored as strings.',
  'skills.create.allowedTools': 'Allowed tools',
  'skills.create.optionalExperimental': 'Optional · Experimental',
  'skills.create.allowedToolsHint': 'This experimental field is only a portable declaration and does not replace runtime permissions or security controls.',
  'skills.create.autoRecognizeAfterInput': 'Detection starts after you stop typing.',
  'skills.create.rawMarkdown': 'Raw SKILL.md',
  'skills.create.importPlaceholder': '---\nname: imported-skill\ndescription: Describe what this Skill is for.\n---\n\n# Instructions',
  'skills.create.importPreserveHint': 'Import keeps the original Skill Package. Non-critical specification differences are shown as compatibility notices; AI does not rewrite the content.',
  'mcp.definition.editTitle': 'Edit MCP',
  'mcp.definition.addTitle': 'Add MCP',
  'mcp.definition.description': 'Create an MCP Definition that can be reused by all Agents.',
  'mcp.definition.namePlaceholder': 'Name',
  'mcp.transport.streamableHttp': 'Remote Streamable HTTP',
  'mcp.transport.stdio': 'Local stdio',
  'mcp.definition.descriptionPlaceholder': 'Description',
  'mcp.definition.commandPlaceholder': 'Command, for example uvx',
  'mcp.definition.workingDirectoryPlaceholder': 'Working directory (optional)',
  'mcp.definition.argsPlaceholder': 'One argument per line\nFor example: --stdio',
  'mcp.auth.none': 'No authentication',
  'mcp.auth.environment': 'Environment variable secret',
  'mcp.auth.oauth2': 'OAuth browser authorization',
  'mcp.auth.customHeaders': 'Custom headers',
  'mcp.definition.apiKeyHeaderPlaceholder': 'API key header name, for example X-API-Key',
  'mcp.definition.headerNamesPlaceholder': 'One allowed header name per line',
  'mcp.definition.environmentKeysPlaceholder': 'One allowed environment variable per line, for example SERVICE_API_TOKEN',
  'mcp.definition.stdioHint': 'Saving only creates the Definition. When connecting, the Electron Desktop Connector Host will ask for confirmation before starting the command.',
  'mcp.definition.oauthHint': 'After installation, choose Authorize. SEEKMORE discovers the authorization service through the MCP OAuth flow and completes sign-in in the system browser.',
  'mcp.import.title': 'Import MCP',
  'mcp.import.description': 'Paste an MCP JSON configuration with live syntax-highlighted preview.',
  'mcp.import.safetyHint': 'Import only creates Definitions. It does not connect or execute local commands, and secret values are not stored in the Definition.',
  'mcp.import.willCreate': 'Will create: {{names}}',
  'mcp.import.importing': 'Importing…',
  'mcp.import.confirm': 'Confirm import',
  'mcp.detail.selectInstallation': 'Select an installed MCP to view its connection status and tools.',
  'mcp.detail.toolCount': '{{count}} available tool(s)',
  'mcp.detail.editDefinition': 'Edit Definition',
  'mcp.detail.availableTools': 'Available tools',
  'mcp.detail.toolsHint': 'After this MCP connects, all discovered tools enter the available tool pool. Calls still pass through the unified permission policy.',
  'mcp.detail.noTools': 'No tools discovered yet. Connect and refresh first.',
  'mcp.connectionFailed': 'Failed to connect to {{name}}',
  'mcp.panel.description': 'Manage installed services, custom Definitions, connection configuration, and available tools.',
  'mcp.panel.create': '+ Create MCP',
  'mcp.panel.import': 'Import MCP',
  'mcp.panel.installedCount': '{{count}} installed MCP server(s)',
  'mcp.panel.loading': 'Loading MCP…',
  'mcp.panel.emptyInstalled': 'No MCP servers installed.',
  'mcp.confirm.revokeAuthorization': 'Revoke authorization for {{name}}?',
  'mcp.confirm.uninstall': 'Uninstall {{name}}?',
  'mcp.panel.userDefinitionsCount': 'User-created MCP Definitions · {{count}}',
  'mcp.panel.custom': 'Custom',
  'mcp.transport.localStdio': 'Local stdio',
  'mcp.actions.install': 'Install',
  'mcp.confirm.deleteDefinition': 'Delete {{name}}?',
  'mcp.panel.emptyDefinitions': 'No user-created MCP Definitions.',
  'mcp.credential.token': 'Access token',
  'mcp.credential.endpoint': 'MCP service endpoint',
  'mcp.credential.connectionString': 'Connection string',
  'mcp.credential.environmentId': 'Environment ID',
  'mcp.credential.username': 'Username',
  'mcp.credential.authorizationHeader': 'Authorization header',
  'mcp.credential.endpointDescription': 'Enter the complete MCP endpoint provided by the vendor console or self-hosted service.',
  'mcp.credential.connectionStringDescription': 'Enter the complete connection string provided by the service.',
  'mcp.credential.redisUrlDescription': 'Enter the Redis service connection URL.',
  'mcp.credential.environmentIdDescription': 'Enter the cloud environment identifier to connect.',
  'mcp.credential.usernameDescription': 'Enter the username required by this service.',
  'mcp.credential.authorizationDescription': 'Enter the complete Authorization value required by the vendor.',
  'mcp.credential.secretDescription': 'Used only to connect this MCP. Saved secrets are not returned in plaintext in the UI.',
  'common.inputPlaceholder': 'Enter a value…',
  'mcp.credential.setupTitle': 'Set up {{name}}',
  'mcp.credential.updateTitle': 'Update {{name}} configuration',
  'mcp.credential.configureTitle': 'Configure {{name}}',
  'mcp.credential.storageHint': 'Local stdio secrets are written only to Electron safeStorage; remote credentials are encrypted by the backend.',
  'mcp.credential.freeformHintBefore': 'This custom Definition does not declare fixed fields. Enter one',
  'mcp.credential.freeformHintAfter': 'entry per line.',
  'mcp.credential.save': 'Save configuration',
  'errors.MCP_OAUTH_REVOKED': 'MCP OAuth authorization was revoked.',
  'errors.MCP_OAUTH_PENDING': 'MCP OAuth authorization is not complete. Choose Authorize again to continue.',
  'common.name': 'Name',
  'common.description': 'Description',
  'common.actions.cancel': 'Cancel',
  'common.actions.done': 'Done',
  'common.actions.removeFile': 'Remove file',
  'common.listSeparator': ', ',
  'agents.edit.loadFailed': 'Failed to load cognitive agent',
  'agents.edit.saveFailed': 'Failed to save cognitive agent',
  'agents.edit.title': 'Edit cognitive agent',
  'agents.edit.description': 'Update the role, knowledge, and linked Skills.',
  'agents.edit.namePlaceholder': 'What should it be called?',
  'agents.edit.descriptionPlaceholder': 'Describe when to use this agent',
  'agents.role.placeholder': 'Identity, personality, behavioral guidelines, speaking style, and more',
  'agents.knowledge.contentLibrary': 'Knowledge content',
  'agents.knowledge.reparseAll': 'Reparse all',
  'agents.knowledge.existingFiles': 'Existing files',
  'agents.knowledge.loadingExisting': 'Loading existing knowledge…',
  'agents.knowledge.newFiles': 'New files this time',
  'agents.knowledge.uploadContent': 'Upload content',
  'agents.knowledge.uploadDescription': 'Upload project materials, policy documents, and references for knowledge retrieval.',
  'agents.knowledge.contentMaterials': 'Content materials',
  'agents.knowledge.contentMaterial': 'Content material',
  'agents.create.failed': 'Failed to create cognitive agent',
  'agents.create.title': 'Create cognitive agent',
  'agents.create.description': 'Define the role, knowledge, and linked Skills.',
  'agents.create.name': 'My name',
  'agents.create.namePlaceholder': 'Give me a name',
  'agents.create.descriptionPlaceholder': 'What should I do?',
  'agents.create.role': 'My role',
  'agents.create.rolePlaceholder': 'My identity, personality, behavioral guidelines, speaking style, and more',
  'agents.create.creating': 'Creating…',
  'agents.create.create': 'Create',
  'skills.picker.addTitle': 'Add Skill',
  'skills.picker.description': 'Choose from My Skills and link them',
  'skills.picker.searchPlaceholder': 'Search My Skills',
  'skills.picker.loading': 'Loading Skills…',
  'skills.picker.empty': 'No linkable Skills found',
  'skills.picker.linkedCount': '{{count}} linked',
  'settings.model.currentPrimary': 'Current primary model',
  'settings.model.primarySupportsVision': '{{model}} already supports image understanding. You can still choose a different service; your selection will take priority after saving.',
  'settings.model.primarySupportsImageGeneration': '{{model}} already supports image generation. You can still choose a different service; your selection will take priority after saving.',
  'settings.model.capability.speechGeneration': 'speech generation',
  'settings.model.capability.voiceCloning': 'voice cloning',
  'settings.model.capability.musicGeneration': 'music generation',
  'settings.model.primarySupportsAudio': '{{model}} already supports {{capabilities}}. You can still choose a different service; your selection will take priority after saving.',
  'settings.model.validatingAndSaving': 'Validating and saving…',
  'settings.model.saved': 'Settings saved.',
  'settings.model.clearing': 'Clearing settings…',
  'settings.model.cleared': 'Settings cleared.',
  'settings.model.clearConfirmTitle': 'Clear these settings?',
  'settings.model.clearConfirmDescription': 'This will clear the saved settings for this capability and take effect immediately.',
  'settings.model.title': 'Model settings',
  'settings.model.description': 'Choose services for the primary model, vision, image generation, video generation, audio generation, and web search.',
  'settings.model.loadingCatalog': 'Loading model catalog…',
  'settings.model.primary.title': 'Primary model',
  'settings.model.primary.description': 'Handles conversation, reasoning, and tool calls.',
  'settings.model.vision.title': 'Vision',
  'settings.model.vision.description': 'Use the vision model you choose first; when none is selected, use the primary model’s native vision capability.',
  'settings.model.image.title': 'Image generation',
  'settings.model.image.description': 'Provides text-to-image, reference-image generation, and image editing for image.generate.',
  'settings.model.video.title': 'Video generation',
  'settings.model.video.description': 'Choose the video generation service and model used by video.generate.',
  'settings.model.video.service': 'Video generation service',
  'settings.model.video.model': 'Video generation model',
  'settings.model.video.apiKey': 'Video generation API Key',
  'settings.model.video.apiKeyHint': 'The saved service and model become the default route for video.generate. The API Key reuses the existing credential for that service.',
  'settings.model.capability.textToVideo': 'Text to video',
  'settings.model.capability.imageToVideo': 'Image to video',
  'settings.model.capability.firstLastFrame': 'First/last frame',
  'settings.model.capability.referenceImages': 'Reference images',
  'settings.model.capability.generatedAudio': 'Native audio',
  'recycle.confirmPermanentTitle': 'Permanently delete this conversation?',
  'recycle.confirmPermanentDescription': '“{{title}}” and its messages, files, and generated results that are not referenced by other conversations will be permanently deleted. This cannot be undone.',
  'recycle.title': 'Recycle bin',
  'recycle.description': 'Individually deleted conversations are grouped by agent and retained for 30 days, during which they can be restored.',
  'recycle.agentInUse': 'In use',
  'recycle.deletedConversationCount': '{{count}} deleted conversation(s)',
  'chat.agentActions.remarkPrompt': 'Edit remark:',
  'chat.agentActions.remarkFailed': 'Failed to update remark. Please try again.',
  'chat.agentActions.pinFailed': 'Failed to update pin. Please try again.',
  'chat.agentActions.shareComingSoon': 'Sharing is coming soon.',
  'chat.agentActions.reportComingSoon': 'Reporting is coming soon.',
  'chat.agentActions.systemAgentCannotRemove': 'The SEEKMORE system assistant cannot be removed.',
  'chat.agentActions.removeConfirm': 'Remove this assistant from the chat list? You can still find it in My Agents.',
  'chat.agentActions.removeFailed': 'Failed to remove assistant. Please try again.',
  'common.actions.back': '← Back',
  'common.actions.refresh': 'Refresh',
  'common.actions.clear': 'Clear',
  'skills.library.mine': 'My Skills',
  'skills.library.drafts': 'Drafts',
  'skills.library.archived': 'Archived',
  'skills.library.deleted': 'Deleted',
  'skills.library.actionFailed': 'Skill action failed',
  'skills.library.purgeTitle': 'Permanently delete Skill?',
  'skills.library.purgeDescription': 'This immediately and permanently deletes “{{name}}” from the database, including all versions, files, and related records. This cannot be undone.',
  'skills.library.purge': 'Permanently delete',
  'skills.library.deletedDescription': 'View and restore Skills that are still within the retention period.',
  'skills.library.description': 'Create, import, validate, and manage local Skills available to cognitive agents.',
  'skills.library.create': '+ Create Skill',
  'skills.library.searchDeleted': 'Search deleted Skills',
  'skills.library.search': 'Search name or description',
  'skills.library.count': '{{count}} Skill(s)',
  'skills.library.retentionWarning': 'Deleted Skills are retained for 30 days. After that they are permanently removed from the database, including all versions, files, and related records, and cannot be restored.',
  'skills.library.loading': 'Loading Skills…',
  'skills.library.emptyDeleted': 'No deleted Skills currently within the retention period.',
  'skills.library.empty': 'No matching Skills.',
  'settings.model.audio.title': 'Audio generation',
  'settings.model.audio.description': 'Choose a service for speech generation, voice cloning, and music generation.',
  'settings.model.audio.service': 'Audio generation service',
  'settings.model.selectService': 'Select a service',
  'settings.model.audio.apiKey': 'Audio generation API Key',
  'settings.model.audio.apiKeyHint': 'Saving an API Key does not validate subscription plans or endpoint permissions. At runtime, only unavailable capabilities are restricted; other audio capabilities remain usable.',
  'settings.model.saveSettings': 'Save settings',
  'settings.model.configured': 'Configured',
  'settings.model.capability.unsupported': 'Unsupported',
  'settings.model.capability.paidOnly': 'Paid subscription required',
  'settings.model.capability.planDependent': 'Depends on account access',
  'settings.model.capability.freeCredits': 'Free credits available',
  'settings.model.capability.available': 'Available',
  'settings.model.web.title': 'Web search',
  'settings.model.web.description': 'Configure your own search service for web.search. When not configured, the primary model receives only an unavailable-capability state.',
  'settings.model.web.service': 'Search service',
  'settings.model.web.apiKey': 'Web search API Key',
  'explore.empty': 'No resources available',
  'explore.searchResults': 'Search results',
  'explore.featured': 'Featured',
  'explore.popular': 'Popular',
  'tools.library.title': 'Tools',
  'tools.library.description': 'SEEKMORE system tools',
  'tools.library.count': '{{count}} tool(s)',
  'workspace.readOnly': 'Read-only',
  'workspace.none': 'No project',
  'workspace.unavailable': 'Project unavailable',
  'workspace.loadFailed': 'Failed to load workspaces',
  'workspace.desktopOnly': 'This feature is available only in the SEEKMORE desktop app.',
  'workspace.bridgeLoading': 'The desktop bridge is loading. Please try again shortly.',
  'workspace.bridgeFailed': 'The desktop bridge failed to load. Please restart SEEKMORE.',
  'workspace.pickerFailed': 'Could not open the folder picker. Check the desktop runtime logs.',
  'workspace.openFolderFailed': 'Failed to open folder',
  'workspace.searchPlaceholder': 'Search work projects',
  'workspace.empty': 'No projects',
  'workspace.newProject': 'New work project',
  'workspace.createBlank': 'Create blank project',
  'workspace.useExistingFolder': 'Use existing folder',
  'skills.preview.standard': 'Standards compatible',
  'skills.preview.compatible': 'Compatibility mode',
  'skills.preview.rejected': 'Cannot create',
  'skills.preview.inspecting': 'Detecting',
  'skills.preview.waiting': 'Waiting for detection',
  'skills.preview.standardHint': '“Save draft” and “Use directly” use only the raw content shown here.',
  'skills.preview.importHint': 'Automatically detect after upload or input and show the actual parsed SKILL.md.',
  'skills.preview.template': '---\nname: skill-draft\ndescription: Describe what this Skill does and when it should be used.\n---\n\n# Instructions\n',
  'skills.preview.packageContent': 'Package contents',
  'skills.preview.untitled': 'Untitled Skill',
  'skills.preview.onlySkillMd': 'SKILL.md only',
  'skills.preview.canRunStandard': 'Can be created and run · Agent Skills compliant',
  'skills.preview.canRun': 'Can be created and run',
  'skills.preview.warningCount': ' · {{count}} standards compatibility warning(s)',
  'skills.preview.compatibleSuffix': ' · Compatibility mode',
  'skills.preview.blockingCount': ' · {{count}} blocking error(s)',
  'skills.preview.diagnostics': 'Validation diagnostics',
  'skills.preview.linePrefix': 'Line {{line}}{{column}} · ',
  'skills.preview.warningNonBlocking': 'Does not block creation or execution',
  'chat.missingModel.title': 'No model configured',
  'chat.missingModel.description': 'Choose a model and enter an API Key in Model settings before sending messages.',
  'chat.missingModel.openSettings': 'Open settings',
  'chat.missingModel.later': 'Later',
  'chat.restore.failed': 'Failed to restore conversation',
  'chat.restore.loading': 'Restoring conversation',
  'common.actions.retry': 'Retry',
  'mcp.dropdown.globalToggle': 'MCP master switch',
  'mcp.dropdown.searchPlaceholder': 'Search MCP services',
  'agents.image.avatarPreview': 'Cognitive agent avatar preview',
  'agents.image.avatar': 'Avatar',
  'agents.image.coverPreview': 'Cognitive agent cover preview',
  'agents.image.cover': 'Cover',
  'skills.create.modalTitle': 'Create Skill',
  'skills.create.modalDescription': 'Create, generate with AI, or import an Agent Skill Package',
  'runtime.status.completed': 'Completed',
  'common.actions.view': 'View',
  'common.actions.download': 'Download',
  'chat.attachments.add': 'Add attachment',
  'chat.attachments.count': '{{count}} attachment(s)',
  'chat.branch.startHere': 'Start a new conversation branch here',
  'chat.branch.createHere': 'Create a branch from here',
  'chat.branch.create': 'Create conversation branch',
  'chat.image.generating': 'Generating image',
  'chat.history.empty': 'No conversation history',
  'chat.contact.remarkPlaceholder': 'Enter remark…',
  'chat.search.conversations': 'Conversations',
  'chat.search.browserTitle': 'Search “{{query}}”',
  'chat.search.browserSubtitle': 'Search in browser',
  'chat.search.agents': 'Assistants',
  'chat.audio.unsupportedBrowser': 'Your browser does not support audio playback.',
  'chat.jumpToBottom': 'Jump to bottom',
  'explore.categories': 'Explore categories',
  'explore.searchPlaceholder': 'Search cognitive agents or SKILL',
  'webSearch.card.query': 'Search query',
  'webSearch.card.sources': 'Highly relevant sources',
  'webSearch.card.openBrowser': 'Open in browser',
  'workspace.create.namePlaceholder': 'Project name, for example test',
  'workspace.create.name': 'Project name',
  'charts.config': 'Chart configuration',
  'charts.themeColor': 'Theme color',
  'skills.files.title': 'Files',
  'skills.files.versionFileCount': '{{count}} version file(s)',
  'skills.files.uploadHint': 'Upload a single file, multiple files, or a complete folder. When a complete Skill root is selected, SKILL.md is still managed in the document editor.',
  'memory.savedTitle': 'Saved memories',
  'memory.savedDescription': 'Data management · Candidate memories are not injected into context by default.',
  'memory.backToData': 'Back to data management',
  'sidebar.extensions.reading': 'Reading',
  'sidebar.extensions.shortVideo': 'Short video',
  'sidebar.extensions.community': 'Community',
  'sidebar.user.avatarAlt': 'User avatar',
  'sidebar.user.changeAvatar': 'Change avatar',
  'sidebar.user.editProfile': 'Click to edit profile',
  'sidebar.user.profileTitle': 'Profile',
  'sidebar.user.username': 'Username',
  'sidebar.user.usernamePlaceholder': 'Enter username',
  'sidebar.user.saveFailed': 'Failed to save profile',
  'common.search': 'Search',
  'common.pagination.previous': 'Previous page',
  'common.pagination.next': 'Next page',
  'chat.input.dropFiles': 'Drop files here to upload',
  'mcp.dropdown.disableGlobal': 'Turn off MCP master switch',
  'mcp.dropdown.enableGlobal': 'Turn on MCP master switch',
  'mcp.dropdown.enabled': 'On',
  'mcp.dropdown.disabled': 'Off',
  'mcp.dropdown.empty': 'No MCP services',
  'mcp.dropdown.noMatch': 'No matching MCP services',
  'workspace.permission.confirm.title': 'Request approval',
  'workspace.permission.confirm.description': 'Reads run directly; writes, changes, commands, and external side effects require approval each time.',
  'workspace.permission.audit.title': 'Approve for me',
  'workspace.permission.audit.description': 'Low- and medium-risk operations run automatically; only high-risk operations require approval.',
  'workspace.permission.full.title': 'Full access',
  'workspace.permission.full.description': 'Run automatically within the current workspace and enabled tools without requesting approval for each operation.',
  'workspace.permission.approveSeekmore': 'Approve SEEKMORE operations',
  'workspace.create.failed': 'Creation failed',
  'workspace.create.desktopOnly': 'This feature is available only in the SEEKMORE desktop app.',
  'workspace.create.bridgeLoading': 'The desktop bridge is loading. Please try again shortly.',
  'workspace.create.bridgeFailed': 'The desktop bridge failed to load. Please restart SEEKMORE.',
  'workspace.create.openPickerFailed': 'Unable to open the folder picker. Check the desktop runtime logs.',
  'workspace.create.nameRequired': 'Enter a project name.',
  'workspace.create.locationRequired': 'Choose where to create the project.',
  'workspace.create.locationUnset': 'No creation location selected',
  'workspace.create.selecting': 'Selecting…',
  'workspace.create.selectLocation': 'Choose location',
  'workspace.create.creating': 'Creating…',
  'workspace.create.createAndSelect': 'Create and select',
  'explore.loading': 'Loading…',
  'markdown.code.preview': 'Preview',
  'markdown.code.code': 'Code',
  'markdown.code.showCode': 'Show code',
  'markdown.code.previewTitle': 'HTML preview',
  'markdown.mermaid.pending': 'Mermaid will render after generation completes',
  'markdown.mermaid.renderFailed': 'Mermaid rendering failed',
  'markdown.textBlock.prompt': 'Prompt',
  'markdown.textBlock.text': 'Text',
  'embodied.title': 'Embodied agents',
  'embodied.description': 'Humanoid robots and embodied terminals · Planned for the next stage',
  'tools.uncategorized': 'Uncategorized',
  'tools.requiresConfirmation': 'Confirmation required',
  'tools.enable': 'Enable tool {{name}}',
  'tools.disable': 'Disable tool {{name}}',
  'skills.files.loadFailed': 'Failed to load files',
  'skills.files.uploading': 'Uploading {{count}} file(s)…',
  'skills.files.uploadedOne': 'Uploaded {{path}}',
  'skills.files.uploadedMany': 'Uploaded {{count}} file(s) and preserved the actual directory structure.',
  'skills.files.uploadFailed': 'Upload failed',
  'skills.files.deletingOne': 'Deleting file…',
  'skills.files.deletingMany': 'Deleting {{count}} file(s)…',
  'skills.files.deleteFailed': 'Delete failed',
  'skills.files.confirmDeleteFile': 'Delete file {{path}}?',
  'skills.files.deletedFile': 'Deleted {{path}}',
  'skills.files.confirmDeleteDirectory': 'Delete folder {{path}} and its {{count}} file(s)?',
  'skills.files.deletedDirectory': 'Deleted folder {{path}}',
  'skills.files.emptyEditable': 'No version files yet. Click “Upload” to add references, scripts, assets, licenses, or other resources.',
  'skills.files.emptyReadonly': 'This version has no other files.',
  'skills.status.deleted': 'Deleted',
  'skills.status.blocked': 'Blocked',
  'skills.status.quarantined': 'Quarantined',
  'skills.status.reviewRequired': 'Review required',
  'skills.status.ACTIVE': 'Enabled',
  'skills.status.DRAFT': 'Draft',
  'skills.status.VALIDATING': 'Validating',
  'skills.status.REJECTED': 'Needs revision',
  'skills.status.ARCHIVED': 'Archived',
  'skills.status.DISABLED': 'Disabled',
  'skills.status.STALE': 'Update needed',
  'skills.action.publish': 'Publish',
  'skills.action.restore': 'Restore',
  'skills.action.enabled': 'Enabled',
  'skills.unknownAuthor': 'Unknown author',
  'skills.noVersion': 'No version',
  'skills.noDescription': 'No description',
  'skills.author': 'Author: {{name}}',
  'skills.processing': 'Processing…',
  'skills.deleting': 'Deleting…',
  'skills.permanentDelete': 'Delete permanently',
  'memory.empty': 'No memories',
  'memory.loadMore': 'Load more',
  'memory.searchPlaceholder': 'Search memory content, topic, or source…',
  'memory.refresh': 'Refresh',
  'settings.model.apiKey.saved': 'Saved ••••{{hint}}',
  'settings.model.apiKey.paste': 'Paste API Key',
  'settings.model.apiKey.get': 'Get',
  'settings.model.selectModel': 'Select a model',
  'settings.model.noModels': 'No models available',
  'settings.model.expandList': 'Expand model list',
  'settings.model.providerListLabel': '{{label}} list',
  'settings.model.recommended': 'Recommended',
  'settings.model.roleModel': '{{title}} model',
  'settings.model.saving': 'Validating and saving…',
  'settings.model.save': 'Save settings',
  'settings.model.clear': 'Clear',
  'sidebar.user.defaultNickname': 'User',
  'conversation.more.deleteTitle': 'Delete conversation',
  'conversation.more.deleteWithAutomations': 'This conversation has {{count}} active or paused automation task(s). Deleting the conversation will end them immediately. The conversation can be restored from the recycle bin, but automation tasks will not be restored automatically.',
  'conversation.more.deleteDescription': 'The conversation and all memories saved during it will move to the recycle bin and can be restored within 30 days.',
  'conversation.more.deleteAndEnd': 'Delete conversation and end tasks',
  'conversation.more.remark': 'Remark',
  'conversation.more.delete': 'Delete',
  'conversation.more.report': 'Report',
  'conversation.more.reportMessage': 'Report {{id}}',
  'conversation.more.processing': 'Processing…',
  'conversation.more.moreActions': 'More actions',
  'conversation.more.deleteFailed': 'Failed to delete. Please try again later.',
  'common.confirm.delete': 'Delete',
  'common.confirm.cancel': 'Cancel',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.copyFailed': 'Copy failed',
  'agent.unnamed': 'Unnamed agent',
  'agent.loadFailed': 'Failed to load agent',
  'chat.actions.addAttachment': 'Add attachment',
  'chat.actions.mcpManageEnabled': 'MCP master switch is on. Click to manage',
  'chat.actions.mcpManageDisabled': 'MCP master switch is off. Click to manage',
  'chat.actions.collapseWorkflow': 'Collapse Workflow',
  'chat.actions.expandWorkflow': 'Expand Workflow',
  'chat.uploadFailed': 'Upload failed',
  'chat.workflow.replyToContinue': 'Reply to the question above to continue the current Workflow…',
  'chat.input.addMore': 'Add more…',
  'chat.input.sendAnything': 'Send anything…',
  'chat.message.collapse': 'Click to collapse',
  'chat.message.expand': 'Click to expand',
  'chat.toolbar.branching': 'Creating branch',
  'chat.toolbar.createBranch': 'Create branch from here',
  'chat.reasoning.thinking': 'Let me think',
  'chat.reasoning.processed': 'Processed',
  'webSearch.local': 'Local web search',
  'webSearch.status.queued': 'Queued',
  'webSearch.status.searching': 'Searching',
  'webSearch.status.waiting': 'Waiting',
  'webSearch.status.blocked': 'Blocked',
  'webSearch.status.completed': 'Completed',
  'webSearch.status.failed': 'Failed',
  'webSearch.status.partial': 'Partially completed',
  'webSearch.status.cancelled': 'Cancelled',
  'webSearch.status.skipped': 'Skipped',
  'chat.sender.you': 'You',
  'chat.sender.system': 'System',
  'agent.context.edit': 'Edit',
  'agent.context.remark': 'Remark',
  'agent.context.unpin': 'Unpin',
  'agent.context.pin': 'Pin',
  'agent.context.share': 'Share',
  'agent.context.report': 'Report',
  'agent.context.remove': 'Remove',
  'chat.defaultGreeting': 'How can I help you today?',
  'chat.search.placeholder': 'Search',
  'chat.composer.stop': 'Stop current run',
  'chat.composer.stopPendingConnection': 'Stop requested. Waiting for a connection to send it.',
  'chat.composer.stopRequesting': 'Stopping this run. Waiting for confirmation.',
  'chat.composer.stopFailed': 'Stop was not confirmed. Sync the conversation and try again.',
  'chat.composer.send': 'Send message',
  'turn.jumpTo': 'Jump to turn {{index}}: {{preview}}',
  'turn.emptyMessage': 'Empty message',
  'object.generatedFile': 'Generated file',
  'object.validating': 'Validating',
  'object.uploadProgress': 'Uploading {{progress}}%',
  'object.preparingPreview': 'Preparing preview',
  'object.uploadOrProcessFailed': 'Upload or processing failed',
  'object.unsupportedType': 'Unsupported file type',
  'object.ready': 'Ready to send',
  'object.removeAfterProcessed': 'Can be removed after processing completes',
  'object.removeAttachment': 'Remove attachment',
  'object.imageLoadFailed': 'Image could not be loaded',
  'object.preview.open': 'Click to preview',
  'object.preview.download': 'Download file',
  'object.preview.expand': 'Expand preview',
  'object.preview.restore': 'Restore preview',
  'object.preview.close': 'Close preview',
  'object.preview.loading': 'Loading preview',
  'object.preview.failed': 'Preview failed to load',
  'object.preview.unavailable': 'Preview is unavailable. You can download the file instead.',
  'object.preview.empty': 'No preview content',
  'object.preview.previous': 'Previous file',
  'object.preview.next': 'Next file',
  'object.preview.index': '{{current}} / {{total}}',
  'runtime.executingTask': 'Executing the current task',
  'assistant.thinking': 'Thinking',
  'workflow.status.waiting': 'Waiting',
  'workflow.status.inProgress': 'In progress',
  'workflow.status.completed': 'Completed',
  'workflow.status.blocked': 'Blocked',
  'workflow.status.failed': 'Failed',
  'workflow.status.skipped': 'Skipped',
  'workflow.status.cancelled': 'Cancelled',
  'workflow.progress': 'Task progress',
  'workflow.blocked': 'Blocked',
  'workflow.wait.input': 'Waiting for input',
  'workflow.wait.approval': 'Waiting for approval',
  'workflow.wait.external': 'Waiting for external dependency',
  'workflow.wait.resourceConflict': 'Resource conflict',
  'workflow.wait.continue': 'Waiting to continue',
  'time.loadFailed': 'Failed to load time data',
  'time.operationFailed': 'Operation failed',
  'time.notificationConfirmFailed': 'Failed to confirm notification',
  'welcome.heading': 'What would you like to do together today?',
  'welcome.presentation.label': 'Create a presentation',
  'welcome.presentation.prompt': 'Help me create a presentation',
  'welcome.game.label': 'Create a game',
  'welcome.game.prompt': 'Help me create a game',
  'welcome.petGif.label': 'Create a GIF sticker for a desktop pet',
  'welcome.petGif.prompt': 'Help me create a GIF sticker for a desktop pet',
  'welcome.blender.label': 'Create a 3D model',
  'welcome.blender.prompt': 'Help me create a 3D model with Blender',
  'welcome.github.label': 'Manage GitHub',
  'welcome.github.prompt': 'Help me work on GitHub',
  'welcome.image.label': 'Create an image',
  'welcome.image.prompt': 'Help me create an image',
  'welcome.music.label': 'Create some music',
  'welcome.music.prompt': 'Help me create a piece of music',
  'welcome.priceWatch.label': 'Price drop and restock alerts',
  'welcome.priceWatch.prompt': 'Monitor product prices and inventory on e-commerce platforms and notify me when a product drops in price or is restocked',
  'welcome.automation.label': 'Create a recurring task',
  'welcome.automation.prompt': 'Help me create a recurring task that runs every day',
  'explore.tabs.overview': 'Overview',
  'explore.tabs.agents': 'Agents',
  'explore.agent.directory': 'Agent directory',
  'explore.skill.directory': 'Skill directory',
  'markdown.error.defaultTitle': 'Rendering failed',
  'markdown.error.defaultMessage': 'Content could not be rendered safely.',
  'markdown.error.unknown': 'Unknown error',
  'markdown.loading': 'Generating content',
  'myagent.nav.cognitive.title': 'Agents',
  'myagent.nav.cognitive.description': 'Domain reasoning, collaboration, and task completion',
  'myagent.nav.embodied.title': 'Embodied',
  'myagent.nav.embodied.description': 'Devices and real-world execution',
  'myagent.nav.skill.title': 'Skill',
  'myagent.nav.skill.description': 'Reusable procedural knowledge',
  'myagent.nav.mcp.title': 'MCP',
  'myagent.nav.mcp.description': 'External applications and tool services',
  'myagent.nav.tool.title': 'Tools',
  'myagent.nav.tool.description': 'System application tools',
  'myagent.nav.recycle.title': 'Recycle bin',
  'myagent.nav.recycle.description': 'Manage deleted conversations by agent',
  'skills.security.SAFE': 'Safe',
  'skills.security.REVIEW_REQUIRED': 'Review required',
  'skills.security.QUARANTINED': 'Quarantined',
  'skills.security.BLOCKED': 'Blocked',
  'skills.files.noUploadable': 'No files to upload. Edit the root SKILL.md in the document editor.',
  'skills.files.chooseFailed': 'File selection failed',
  'skills.files.desktopChooseFailed': 'Desktop file selection failed',
  'skills.files.addToDirectory': 'Add files to {{directory}}',
  'skills.files.uploadFileOrFolder': 'Upload Skill files or folders',
  'skills.files.uploadFile': 'Upload Skill file',
  'skills.files.reading': 'Reading…',
  'skills.files.upload': 'Upload',
  'artifact.status.DRAFT': 'Draft',
  'artifact.status.GENERATING': 'Generating',
  'artifact.status.RENDERING': 'Rendering',
  'artifact.status.COMPLETED': 'Completed',
  'artifact.status.FAILED': 'Failed',
  'artifact.status.ARCHIVED': 'Archived',
  'sidebar.nav.chat': 'Chat',
  'sidebar.nav.myagent': 'My SEEKMORE',
  'sidebar.nav.explore': 'Explore SEEKMORE',
  'sidebar.nav.settings': 'Settings',
  'memory.loadFailed': 'Failed to load memories',
  'memory.confirm.forgetTitle': 'Forget memory',
  'memory.confirm.forgetDescription': 'Forgotten memories are not used for recall and can be restored from Deleted.',
  'memory.confirm.forget': 'Forget',
  'memory.confirm.purgeTitle': 'Delete memory permanently',
  'memory.confirm.purgeDescription': 'Permanent deletion cannot be undone.',
  'memory.confirm.purge': 'Delete permanently',
  'memory.operationFailed': 'Operation failed',
  'skills.security.CLEAR': 'Safe',
  'errors.branchMissingConversationId': 'Branch creation succeeded but no conversationId was returned.',
  'chat.openConversation': 'Open conversation: {{id}}',
  'chat.upload.missingObjectId': 'Upload succeeded but no objectId was returned.',
  'chat.upload.objectNotReady': 'The object is not ready yet and cannot be sent.',
  'chat.init.missingConversationId': 'No conversation ID was returned.',
  'chat.init.failed': 'Failed to initialize the conversation.',
  'chat.title.missingConversationId': 'Missing conversationId.',
  'chat.title.missingSeed': 'Missing title seed.',
  'chat.title.generateFailed': 'Failed to generate the title.',
  'chat.title.missingAgentId': 'Missing agentId.',
  'chat.title.createFailed': 'Failed to create the title.',
  'chat.title.empty': 'The title cannot be empty.',
  'chat.title.conflict': 'The title was updated elsewhere. Refresh and try again.',
  'chat.title.renameFailed': 'Failed to rename the conversation.',
  'chat.conversation.remarkFailed': 'Failed to rename the conversation.',
  'chat.conversation.deleteFailed': 'Failed to delete the conversation.',
  'chat.branch.unsaved': 'This conversation has not been saved yet, so a branch cannot be created.',
  'chat.branch.createFailed': 'Could not create a conversation branch. Try again later.',
  'chat.turn.blankMessage': 'Blank message',
  'chat.download.failedStatus': 'Download failed: HTTP {{status}}',
  'runtime.workspace.invalidResponse': 'The backend did not return a valid workspace.',
  'runtime.workspace.idRequired': 'Workspace ID is required.',
  'runtime.workspace.notFound': 'Workspace not found.',
  'runtime.workspace.conversationIdRequired': 'Conversation ID is required.',
  'cognitive.loadFailed': 'Failed to load cognitive agents.',
  'cognitive.deletedLoadFailed': 'Failed to load deleted cognitive agents.',
  'cognitive.knowledge.loadFailed': 'Failed to load the knowledge base.',
  'cognitive.knowledge.uploadFailed': 'Failed to upload the knowledge file.',
  'cognitive.knowledge.deleteFailed': 'Failed to delete the knowledge file.',
  'cognitive.knowledge.reparseFailed': 'Failed to reprocess the knowledge file.',
  'myagent.loadFailed': 'Failed to load cognitive agents.',
  'skills.validation.failedWithMessage': 'Skill validation failed: {{message}}',
  'skills.validation.failed': 'Skill validation failed.',
  'skills.deleted.restoreFirst': 'This Skill is deleted. Restore it first.',
  'skills.deleted.bindingBlocked': 'Deleted Skills cannot receive new bindings. Restore the Skill first.',
  'skills.create.templateDescription': 'Describe what this Skill can do and when it should be used.',
  'skills.create.templateHeading': 'Usage Instructions',
  'skills.create.templateBody': 'Write reusable execution steps here.',
  'skills.request.failed': 'Skill request failed.',
  'skills.import.blocked': 'The Skill Package contains blocking errors and cannot be imported yet.',
  'skills.import.standardRecognized': 'The Skill Package was recognized and complies with the Agent Skills standard.',
  'skills.import.compatibleRecognized': 'The Skill Package was recognized and can be imported in compatibility mode.',
  'skills.import.inspectFailed': 'Failed to inspect the Skill Package.',
  'skills.create.aiGenerated': 'AI generated a standard Skill. Review the content, then save it as a draft or use it directly.',
  'skills.activate.failed': 'The Skill could not be activated.',
  'skills.activate.draftSavedButFailed': 'The draft was saved, but direct activation failed: {{message}}',
  'skills.draft.missingVersionId': 'The Skill draft was created but no usable draft version ID was returned.',
  'skills.draft.saved': 'Skill saved as a draft.',
  'skills.active.saved': 'Skill saved and ready to use.',
  'skills.import.notInspected': 'The Skill Package has not finished automatic inspection.',
  'skills.import.stillBlocked': 'The import package still contains blocking errors.',
  'skills.import.missingVersionId': 'The Skill Package was imported but no usable draft version ID was returned.',
  'skills.import.standardDraftSaved': 'Standard Skill Package saved as a draft.',
  'skills.import.compatibleDraftSaved': 'Skill Package saved as a draft in compatibility mode.',
  'skills.import.standardActivated': 'Standard Skill Package imported and ready to use.',
  'skills.import.compatibleActivated': 'Skill Package imported in compatibility mode and ready to use.',
  'skills.actions.creating': 'Creating…',
  'skills.actions.aiCreate': 'Create with AI',
  'skills.actions.saving': 'Saving…',
  'skills.actions.saveDraft': 'Save draft',
  'skills.actions.activating': 'Activating…',
  'skills.actions.retryActivate': 'Retry direct use',
  'skills.actions.useDirectly': 'Use directly',
  'skills.error.nameConflict': 'The Skill internal identifier conflicts with another Skill. Create it again and retry.',
  'skills.error.nameReserved': 'The corresponding Skill is still in its deletion retention period. Restore it or wait until permanent deletion.',
  'skills.error.importChanged': 'The Skill Package changed after inspection, or the inspection result expired. Wait for automatic re-inspection.',
  'skills.error.importTokenInvalid': 'The current import inspection token is invalid. Wait for automatic re-inspection.',
  'skills.error.validationRequired': 'The Skill has not completed valid validation and cannot be used directly yet.',
  'skills.error.validationFailed': 'The Skill contains blocking validation errors and cannot be used directly yet.',
  'skills.error.securityReviewRequired': 'The Skill has not passed security review and cannot be used directly yet.',
  'skills.error.securityRejected': 'The Skill failed security review and cannot be used directly.',
  'skills.error.nameImmutable': 'The Skill internal identifier cannot be changed. The display name can be edited separately.',
  'skills.error.draftVersionNotFound': 'No Skill draft version was found for validation or publishing.',
  'skills.error.versionNotDraft': 'This Skill version is no longer a draft and cannot be published again.',
  'skills.error.versionAlreadyPublished': 'This Skill version is already published and does not need to be activated again.',
  'skills.error.alreadyActive': 'This Skill is already active.',
  'skills.error.revisionConflict': 'The Skill was updated elsewhere. Refresh and try again.',
  'skills.error.displayNameInvalid': 'Skill name is required and must be at most 120 characters.',
  'skills.error.packageRejected': 'The Skill Package contains blocking errors and cannot be saved or used directly.',
  'skills.error.resourceNotFound': 'A resource referenced by the Skill does not exist. The draft was kept, but this operation cannot complete.',
  'skills.error.notFound': 'The Skill could not be found and may have been deleted.',
  'skills.error.permissionDenied': 'You do not have permission to perform this Skill operation.',
  'skills.error.requestWithCode': 'Skill request failed ({{code}}).',
  'skills.error.stateConflict': 'The Skill state or name conflicts with another operation. Check for an existing draft or imported Skill with the same name.',
  'skills.error.badRequest': 'The Skill request is invalid. Review the validation diagnostics and update it.',
  'skills.error.versionMissing': 'The Skill or version could not be found.',
  'skills.error.packageTooLarge': 'The Skill Package exceeds the allowed file size.',
  'skills.error.metadataDuplicate': 'Duplicate metadata key: {{key}}',
  'skills.files.noneUploadable': 'No uploadable files were found. Edit the root SKILL.md in the document editor.',
  'skills.files.selectionFailed': 'Failed to select files.',
  'skills.files.desktopSelectionFailed': 'Desktop file selection failed.',
  'skills.files.uploadFilesOrFolder': 'Upload Skill files or folder',
  'skills.files.uploadFiles': 'Upload Skill files',
  'skills.files.pathRequired': 'File path is required.',
  'skills.files.invalidDirectory': 'The file path contains an invalid directory.',
  'skills.files.duplicatePath': 'The selection contains a duplicate path: {{path}}',
  'skills.loadFailed': 'Failed to load Skills.',
  'files.upload.partitionRequired': 'Uploading a file requires an explicit Agent and Conversation partition.',
  'files.upload.processFailed': 'File upload or processing failed.',
  'files.upload.missingObjectId': 'Upload succeeded but the backend did not return objectId.',
  'files.upload.objectNotReady': 'The object is not ready yet and cannot be sent.',
  'files.image.unsupportedFormat': 'This image format is not supported. Use PNG, JPEG, or WebP.',
  'files.image.decodeFailed': 'The image cannot be decoded or is corrupted.',
  'files.type.unsupported': 'This file type is not supported.',
  'http.refresh.missingAccessToken': 'The refresh endpoint did not return an access token.',
  'skills.error.withCode': '{{message}} ({{code}})',
  'skills.error.httpStatus': '{{message}} (HTTP {{status}})',
  'errors.AUTH_USER_ID_REQUIRED': 'User identity is required.',
  'errors.COGNITIVE_CAPABILITIES_INVALID': 'Capabilities must be an array or a comma-separated string.',
  'errors.COGNITIVE_CAPABILITY_UNSUPPORTED': 'Unsupported capability: {{capability}}',
  'errors.COGNITIVE_KNOWLEDGE_UPLOAD_BATCH_LIMIT': 'Upload at most {{limit}} knowledge files at a time.',
  'errors.COGNITIVE_KNOWLEDGE_FILE_TOO_LARGE': '{{fileName}} exceeds the {{maxMb}} MB limit.',
  'errors.COGNITIVE_KNOWLEDGE_FILE_TYPE_UNSUPPORTED': 'Unsupported file type: {{fileName}} ({{mimeType}})',
  'errors.COGNITIVE_IMAGE_FORMAT_UNSUPPORTED': 'Avatar and cover images support PNG, JPG, and WebP only: {{fileName}}',
  'errors.COGNITIVE_IMAGE_TOO_LARGE': '{{fileName}} exceeds the {{maxMb}} MB image limit.',
  'errors.AUTH_SESSION_EXPIRED': 'The local session has expired.',
  'errors.CHAT_LEGACY_CREATE_MESSAGE_DISABLED': 'This legacy message creation path is no longer available.',
  'errors.CHAT_LEGACY_CREATE_MESSAGE_WITH_AGENT_DISABLED': 'This legacy agent message creation path is no longer available.',
  'errors.BRANCH_SOURCE_MESSAGE_NOT_FOUND': 'Branch source message not found.',
  'errors.BRANCH_SOURCE_NOT_ASSISTANT': 'Branches can only be created from assistant messages.',
  'errors.BRANCH_SOURCE_NOT_COMPLETED': 'The message is not complete and cannot be branched yet.',
  'errors.BRANCH_MESSAGE_TREE_CYCLE': 'The message tree contains a cycle and cannot be branched.',
  'errors.BRANCH_CONTEXT_TOO_LONG': 'The branch context is too long to snapshot.',
  'errors.BRANCH_MESSAGE_CROSS_CONVERSATION': 'The message tree crosses another conversation.',
  'errors.BRANCH_PARENT_CHAIN_INCOMPLETE': 'The message parent chain is incomplete.',
  'errors.CONVERSATION_ARCHIVED_BRANCH_FORBIDDEN': 'Archived conversations cannot be branched.',
  'errors.BRANCH_CONTEXT_EMPTY': 'There is no conversation context to copy.',
  'errors.BRANCH_SNAPSHOT_CREATE_FAILED': 'Failed to create the branch message snapshot.',
  'errors.BRANCH_REQUEST_ID_CONFLICT': 'This requestId was already used for another branch request.',
  'errors.BRANCH_METADATA_INVALID': 'Branch conversation metadata is incomplete.',
  'errors.AGENT_UNAVAILABLE': 'The Agent does not exist or is disabled.',
  'errors.CONVERSATION_DELETE_DENIED': 'You do not have permission to delete this conversation.',
  'errors.CONVERSATION_DELETED_NOT_FOUND': 'Deleted conversation not found.',
  'errors.CONVERSATION_RETENTION_EXPIRED': 'This conversation is past its 30-day retention period and cannot be restored.',
  'errors.CONVERSATION_AGENT_DELETED': 'The owning Agent is deleted. Restore the Agent first.',
  'errors.CONVERSATION_NOT_IN_RECYCLE_BIN': 'Move the conversation to Deleted before permanent deletion.',
  'errors.MESSAGE_PARENT_CROSS_CONVERSATION': 'The parent message does not belong to this conversation.',
  'errors.DOCUMENT_BUFFER_INVALID': 'The file buffer is invalid.',
  'errors.DOCUMENT_EMPTY': 'The file is empty.',
  'errors.DOCUMENT_PARSE_SIZE_LIMIT': 'The file exceeds the {{maxMb}} MB parsing limit.',
  'errors.DOCUMENT_PARSER_INVALID_RESULT': 'The {{parserKind}} parser returned an invalid result.',
  'errors.DOCUMENT_CSV_EMPTY': 'CSV contains no parseable content: {{objectName}}',
  'errors.DOCUMENT_CSV_COLUMN_LIMIT': 'CSV exceeds the {{limit}} column limit.',
  'errors.DOCUMENT_CSV_FIELD_LIMIT': 'A CSV field exceeds the {{limit}} character limit.',
  'errors.DOCUMENT_CSV_UNCLOSED_QUOTE': 'CSV contains an unclosed quoted field.',
  'errors.DOCUMENT_JSON_INVALID': 'Invalid JSON file content: {{objectName}}',
  'errors.DOCUMENT_TEXT_INVALID': 'The file is not valid text: {{objectName}}',
  'errors.OBJECT_ID_REQUIRED': 'objectId is required.',
  'errors.OBJECT_ID_DUPLICATE': 'Duplicate objectId: {{objectId}}',
  'errors.OBJECT_POSITION_DUPLICATE': 'Duplicate Object position: {{position}}',
  'errors.MESSAGE_CONVERSATION_MISMATCH': 'The message does not belong to this conversation.',
  'errors.MESSAGE_OBJECT_ROLE_MISMATCH': 'The message role does not match the Object relationship role.',
  'errors.OBJECT_NOT_READY_OR_INACCESSIBLE': 'Objects are not ready or accessible: {{ids}}',
  'errors.OBJECT_NOT_FOUND_OR_INACCESSIBLE': 'Objects do not exist or are inaccessible: {{ids}}',

  'automation.message.expired': 'Automation ended\n“{{title}}” reached its configured end time and will no longer run automatically.',
  'automation.message.blocked': 'This automation needs user action and has been paused.',
  'automation.message.paused': 'The automation is paused. This run has stopped.',
  'automation.message.cancelled': 'The automation has ended. This run has stopped.',
  'automation.message.failed': 'This automation run failed.',
  'automation.message.interrupted': 'The automation was interrupted by an application restart and this run has ended.',
  'mcp.configuration.oauth': 'Sign in to {{displayName}} and complete authorization.',
  'mcp.configuration.credential': 'Configure access credentials for {{displayName}}.',
  'mcp.configuration.localSetup': 'Complete the local or self-hosted setup for {{displayName}} first.',
  'mcp.configuration.ready': 'No additional configuration is required. Connect after installation.',
  'common.avatarAlt': 'Avatar',
  'chat.reasoning.streaming': 'Streaming reasoning',
  'turn.minimap.ariaLabel': 'Conversation turn minimap',
  'explore.banner.ariaLabel': 'Explore banner',
  'mcp.definition.urlPlaceholder': 'MCP URL (HTTPS)',
  'mcp.auth.bearerToken': 'Bearer Token',
  'mcp.auth.apiKey': 'API Key',
  'common.apiKey': 'API Key',
  'errors.UNSUPPORTED_UI_LOCALE': 'This interface language is not supported.',
  'errors.LOCALIZATION_PREFERENCE_CHANGE_REQUIRED': 'Choose a language preference to update.',
  'errors.USER_IDENTITY_REQUIRED': 'The local session is missing user identity. Retry the session.',
  'errors.SKILL_DISPLAY_NAME_INVALID': 'Skill name must be at most 120 characters and cannot contain control characters.',
  'errors.SKILL_DELETED_CANNOT_BIND': 'A deleted Skill cannot be newly associated. Restore the Skill first.',
  'errors.SKILL_DELETED_RESTORE_REQUIRED': 'This Skill has been deleted. Restore it first.',

  'skills.diagnostic.SKILL_FRONTMATTER_REQUIRED': 'SKILL.md must begin with YAML frontmatter.',
  'skills.diagnostic.SKILL_FRONTMATTER_UNCLOSED': 'SKILL.md YAML frontmatter is not closed.',
  'skills.diagnostic.SKILL_FRONTMATTER_YAML_INVALID': 'Invalid YAML frontmatter: {{detail}}',
  'skills.diagnostic.SKILL_FRONTMATTER_MAPPING_REQUIRED': 'SKILL.md frontmatter must be a YAML mapping.',
  'skills.diagnostic.SKILL_FRONTMATTER_EXTENSION_FIELD': 'Non-standard frontmatter field {{field}} is preserved but ignored by the standard runtime projection.',
  'skills.diagnostic.SKILL_NAME_REQUIRED': 'name must be a non-empty string.',
  'skills.diagnostic.SKILL_NAME_UNSAFE': 'name cannot contain path separators, control characters, or path traversal values.',
  'skills.diagnostic.SKILL_NAME_STORAGE_LIMIT_EXCEEDED': 'name must not exceed {{maxLength}} characters.',
  'skills.diagnostic.SKILL_NAME_NON_STANDARD': 'name is usable in compatibility mode, but the Agent Skills specification recommends lowercase ASCII letters, digits, and single hyphens.',
  'skills.diagnostic.SKILL_ROOT_NAME_MISMATCH': 'Package root name {{rootName}} differs from frontmatter name {{name}}. The frontmatter name is used as the Skill identity.',
  'skills.diagnostic.SKILL_NAME_IMMUTABLE': 'An existing Skill cannot change its name. Create a new Skill instead.',
  'skills.diagnostic.SKILL_DESCRIPTION_REQUIRED': 'description must be a non-empty string.',
  'skills.diagnostic.SKILL_DESCRIPTION_STORAGE_LIMIT_EXCEEDED': 'description must not exceed 1024 characters.',
  'skills.diagnostic.SKILL_DESCRIPTION_TOO_LONG': 'description must not exceed 1024 characters.',
  'skills.diagnostic.SKILL_METADATA_NON_STANDARD': 'metadata should be a mapping. The original value is preserved but ignored by the standard runtime projection.',
  'skills.diagnostic.SKILL_METADATA_VALUE_NON_STANDARD': 'metadata.{{key}} should be a string. The original value is preserved but ignored by the standard runtime projection.',
  'skills.diagnostic.SKILL_METADATA_MAPPING_REQUIRED': 'metadata must be a mapping of string keys to string values.',
  'skills.diagnostic.SKILL_METADATA_VALUE_INVALID': 'A metadata value must be a string.',
  'skills.diagnostic.SKILL_ALLOWED_TOOLS_NON_STANDARD': 'allowed-tools should be a space-separated string. The original value is preserved and ignored as runtime permission authority.',
  'skills.diagnostic.SKILL_ALLOWED_TOOLS_EXPERIMENTAL': 'allowed-tools is experimental and is not used as runtime permission authority.',
  'skills.diagnostic.SKILL_BODY_REQUIRED': 'SKILL.md must contain a non-empty Markdown instruction body.',
  'skills.diagnostic.SKILL_MARKDOWN_SIZE_EXCEEDED': 'SKILL.md exceeds the configured safety size limit.',
  'skills.diagnostic.SKILL_MARKDOWN_LINE_COUNT_HIGH': 'SKILL.md is over 500 lines; consider moving detailed material into references/.',
  'skills.diagnostic.SKILL_MARKDOWN_TOKEN_ESTIMATE_HIGH': 'SKILL.md is estimated to exceed 5000 tokens; consider moving detailed material into references/.',
  'skills.diagnostic.SKILL_RESOURCE_PATH_NOT_CANONICAL': 'Skill resource paths must be canonical paths relative to the Skill root.',
  'skills.diagnostic.SKILL_RESOURCE_PATH_INVALID': 'Skill resource path is invalid: {{detail}}',
  'skills.diagnostic.SKILL_RESOURCE_REFERENCE_MISSING': 'Referenced Skill resource is not present in this package: {{path}}. The Skill remains runnable, but reading this resource may fail at runtime.',
  'skills.diagnostic.SKILL_RESOURCE_REFERENCE_NON_STANDARD': 'A bundled resource reference is not a safe Skill-root-relative path. Runtime path policy will reject unsafe reads.',
  'skills.diagnostic.SKILL_DOCUMENT_INVALID': 'SKILL.md cannot be safely created or run.',
  'skills.diagnostic.SKILL_DOCUMENT_PARSE_FAILED': 'SKILL.md parsing failed: {{detail}}',
  'skills.diagnostic.SKILL_DISPLAY_NAME_REQUIRED': 'Skill display name is required.',
  'skills.diagnostic.SKILL_DISPLAY_NAME_INVALID': 'Skill display name must not exceed 120 characters or contain control characters.',
  'skills.diagnostic.SKILL_GENERATION_INPUT_INVALID': 'Skill generation input validation failed.',
  'skills.diagnostic.SKILL_LICENSE_INVALID': 'license must be a string.',
  'skills.diagnostic.SKILL_COMPATIBILITY_INVALID': 'compatibility must be a string.',
  'skills.diagnostic.SKILL_COMPATIBILITY_TOO_LONG': 'compatibility exceeds the supported length.',
  'skills.diagnostic.SKILL_ALLOWEDTOOLS_INVALID': 'allowedTools must be a string.',
  'skills.diagnostic.SKILL_FILE_COUNT_EXCEEDED': 'Skill file count exceeds the configured limit ({{maxFiles}}).',
  'skills.diagnostic.SKILL_PACKAGE_SIZE_EXCEEDED': 'Skill package size exceeds the configured limit.',
  'skills.diagnostic.SKILL_DUPLICATE_PATH': 'The Skill package contains a duplicate file path: {{path}}.',
  'skills.diagnostic.SKILL_FILE_SIZE_EXCEEDED': 'Skill file {{path}} exceeds the size limit for its file type.',
  'skills.diagnostic.SKILL_PIPE_REMOTE_SHELL': 'Detected a remote download piped directly into a shell.',
  'skills.diagnostic.SKILL_PRIVILEGED_COMMAND': 'Detected a high-risk system command.',
  'skills.diagnostic.SKILL_SECRET_MATERIAL': 'Detected possible credentials or private key material.',
  'skills.diagnostic.SKILL_BIDI_CONTROL': 'Detected bidirectional text control characters.',
  'skills.diagnostic.SKILL_ZERO_WIDTH': 'Detected zero-width characters.',
  'skills.diagnostic.SKILL_HIDDEN_INSTRUCTION': 'Detected hidden instructions inside an HTML comment.',
  'skills.diagnostic.SKILL_DATA_URL': 'Detected an inline executable data URL.',
  'skills.diagnostic.SKILL_PATH_INVALID': 'Skill file path is invalid.',
  'skills.diagnostic.SKILL_PATH_ABSOLUTE': 'Skill files cannot use absolute paths.',
  'skills.diagnostic.SKILL_PATH_TRAVERSAL': 'Skill file path cannot traverse outside the Skill root.',
  'skills.diagnostic.SKILL_PATH_SEGMENT_INVALID': 'Skill file path contains an invalid segment.',
  'skills.diagnostic.SKILL_PATH_HIDDEN_SEGMENT': 'Skill file path cannot contain hidden files or directories.',
  'skills.diagnostic.SKILL_PATH_DEPTH_EXCEEDED': 'Skill file path exceeds the maximum directory depth.',
  'skills.diagnostic.SKILL_PATH_TOO_LONG': 'Skill file path is too long.',
  'skills.diagnostic.SKILL_SKILL_DEPENDENCY_UNAVAILABLE': 'Required Skill dependency is unavailable: {{key}}.',
  'skills.diagnostic.SKILL_TOOL_DEPENDENCY_UNAVAILABLE': 'Required Tool dependency is unavailable: {{key}}.',
  'skills.diagnostic.SKILL_MCP_DEPENDENCY_UNAVAILABLE': 'Required MCP dependency is unavailable: {{key}}.',
  'skills.diagnostic.SKILL_CAPABILITY_UNSUPPORTED': 'Capability is not present in the system catalog: {{capabilityId}}.',
  'skills.diagnostic.SKILL_CAPABILITY_UNAVAILABLE': 'No available Tool currently provides this capability: {{capabilityId}}.',
  'skills.diagnostic.SKILL_CAPABILITY_CONFIRMATION_REQUIRED': 'Capability {{capabilityId}} requires user confirmation.',
  'skills.diagnostic.SKILL_CAPABILITY_CONCRETE_TOOL': 'A concrete Tool id cannot be used as a Skill capability: {{rawValue}}. {{candidates}}',
  'skills.diagnostic.SKILL_CAPABILITY_AMBIGUOUS': 'Capability name is ambiguous: {{rawValue}}. {{candidates}}',
  'skills.diagnostic.SKILL_CAPABILITY_UNRESOLVED': 'Capability is not recognized by the system catalog: {{rawValue}}. {{candidates}}',

  'errors.BRANCH_USER_ID_REQUIRED': 'User is required to create a branch.',
  'errors.BRANCH_CONVERSATION_ID_REQUIRED': 'Conversation is required to create a branch.',
  'errors.BRANCH_FROM_MESSAGE_ID_REQUIRED': 'A source message is required to create a branch.',
  'errors.BRANCH_REQUEST_ID_REQUIRED': 'requestId is required to create a branch.',

  'chat.message.turnFailed': 'This turn failed. Please try again later.',

  'common.cover': 'Cover',
  'common.status.pending': 'Pending',
  'common.toggle.on': 'ON',
  'common.toggle.off': 'OFF',
  'agents.knowledge.chunkCount': '{{count}} chunk(s)',
  'skills.create.skillPackage': 'Skill Package',
  'skills.create.repositoryUrl': 'Repository URL',
  'artifact.kind.codeProject': 'Code Project',
  'artifact.kind.word': 'Word Artifact',
  'artifact.kind.excel': 'Excel Artifact',

  'errors.AUTHENTICATED_USER_REQUIRED': 'A local user session is required.',
  'errors.RENDER_REQUEST_OBJECT_REQUIRED': 'The render request must be an object.',
  'errors.RENDER_TOOL_NAME_REQUIRED': 'The render request is missing toolName.',
  'errors.RENDER_PAYLOAD_OBJECT_REQUIRED': 'The render payload must be an object.',
  'errors.RENDER_PAYLOAD_ARRAY_FORBIDDEN': 'The render payload cannot be an array.',
  'errors.RENDER_FILENAME_STRING_REQUIRED': 'The render filename must be a string.',
  'errors.RENDER_TITLE_STRING_REQUIRED': 'The render title must be a string.',
  'errors.RENDER_META_OBJECT_REQUIRED': 'Render metadata must be an object.',
  'errors.RENDER_BINARY_BUFFER_REQUIRED': 'Render delivery requires a non-empty binary buffer.',
  'errors.RENDER_PLANNING_ARGS_OBJECT_REQUIRED': 'Render planning arguments must be an object.',
  'errors.RENDER_INSTRUCTION_OR_PLAN_REQUIRED': 'Rendering requires an instruction or a plan.',
  'errors.RENDER_SOURCE_OBJECT_REQUIRED': 'Render source must be an object.',
  'errors.RENDER_REQUIREMENTS_OBJECT_REQUIRED': 'Render requirements must be an object.',
  'errors.RENDER_OUTPUT_FIELD_UNSUPPORTED': 'Render output is fixed to the Object Catalog; the output field is not supported.',
  'errors.ZIP_ARGS_OBJECT_REQUIRED': 'ZIP arguments must be an object.',
  'errors.ZIP_FILES_REQUIRED': 'ZIP rendering requires files.',
  'errors.DOCX_PAYLOAD_OBJECT_REQUIRED': 'DOCX payload must be an object.',
  'errors.DOCX_PAYLOAD_EMPTY': 'DOCX payload is empty.',
  'errors.DOCX_BLOCK_TYPE_REQUIRED': 'DOCX block.type is required.',
  'errors.DOCX_IMAGE_BASE64_REQUIRED': 'The DOCX image block is missing base64 content.',
  'errors.DOCX_TABLE_ROWS_ARRAY_REQUIRED': 'DOCX table rows must be an array.',
  'errors.RUNTIME_WORKSPACE_PERSISTENCE_UNAVAILABLE': 'Runtime workspace persistence is unavailable.',
  'errors.WORKSPACE_NOT_FOUND': 'The workspace does not exist.',
  'errors.WORKSPACE_UPDATE_INVALID': 'The workspace update produced an invalid state.',
  'errors.WORKSPACE_DEFAULT_UPDATE_INVALID': 'Updating the default workspace produced an invalid state.',
  'errors.WORKSPACE_PERSISTENCE_UNAVAILABLE': 'Workspace persistence is unavailable.',
  'errors.AGENT_PROFILE_IMAGE_KIND_INVALID': 'The profile image type is invalid.',
  'errors.AGENT_PROFILE_IMAGE_NOT_FOUND': 'The profile image does not exist.',
  'errors.PUBLIC_AGENT_NOT_FOUND': 'The agent does not exist or is not public.',
  'errors.PUBLIC_FREE_AGENT_NOT_FOUND': 'The public free agent does not exist.',
  'errors.PUBLIC_PAID_AGENT_NOT_FOUND': 'The public paid agent does not exist.',
  'errors.AGENT_RELATION_NOT_FOUND': 'The agent relation does not exist.',
  'errors.MCP_AUTHENTICATED_PRINCIPAL_REQUIRED': 'An authenticated MCP principal is required.',
  'errors.MCP_AGENT_ACCESS_DENIED': 'This agent is not accessible to the authenticated user.',
  'errors.CONVERSATION_ID_REQUIRED': 'conversationId is required. Create a conversation first.',

  'errors.TOOL_NOT_FOUND': 'Tool {{toolName}} does not exist.',
  'errors.DOCUMENT_TYPE_UNSUPPORTED': 'Unsupported document type: {{objectName}} ({{mimeType}}).',
  'errors.RENDER_TOOL_CANNOT_HANDLE_REQUEST': 'Render tool {{toolName}} cannot handle this request.',
  'errors.RENDER_TOOL_NOT_FOUND': 'Render tool {{toolName}} does not exist.',
  'errors.RENDER_TOOL_DISABLED': 'Render tool {{toolName}} is disabled.',
  'errors.DOCX_TEXT_LIMIT_EXCEEDED': 'DOCX text exceeds the limit of {{limit}} characters.',
  'errors.DOCX_BLOCK_LIMIT_EXCEEDED': 'DOCX blocks exceed the limit of {{limit}}.',
  'errors.DOCX_TABLE_ROW_LIMIT_EXCEEDED': 'DOCX table rows exceed the limit of {{limit}}.',
  'errors.DOCX_TABLE_COLUMN_LIMIT_EXCEEDED': 'DOCX table columns exceed the limit of {{limit}}.',

  'errors.SKILL_NOT_BINDABLE': 'Skill {{skillId}} cannot be bound in its current state.',
  'errors.ENABLED_SKILL_MUST_BE_ACTIVE_AND_CLEAR': 'Enabled Skill {{skillId}} must be active and pass security checks.',
  'errors.PINNED_VERSION_REQUIRED': 'Skill {{skillId}} requires a pinned version.',
  'errors.PINNED_VERSION_INVALID': 'The pinned version for Skill {{skillId}} is invalid.',
  'errors.ENABLED_SESSION_SKILL_MUST_BE_ACTIVE_AND_CLEAR': 'Enabled session Skill {{skillId}} must be active and pass security checks.',
  'errors.SESSION_SKILL_VERSION_INVALID': 'The selected session version for Skill {{skillId}} is invalid.',
  'errors.SKILL_GENERATION_PAUSED': 'Skill generation is paused: {{reason}}.',
  'errors.SKILL_IMPORT_ZIP_INVALID': 'The Skill ZIP package is invalid: {{reason}}.',
  'errors.OBJECT_REFERENCE_DUPLICATE': 'Object {{objectId}} was referenced more than once.',
  'errors.OBJECT_POSITION_INVALID': 'Object {{objectId}} has an invalid position.',
  'errors.MCP_IMPORT_TRANSPORT_AMBIGUOUS': 'MCP server {{server}} specifies more than one transport.',
  'errors.MCP_IMPORT_TRANSPORT_REQUIRED': 'MCP server {{server}} is missing a transport configuration.',
  'errors.MCP_IMPORT_ARGS_INVALID': 'MCP server {{server}} contains invalid command arguments.',
  'errors.MCP_IMPORT_COMMAND_INVALID': 'MCP server {{server}} contains an invalid command.',
  'errors.OBJECT_TOO_LARGE': 'The object is too large ({{sizeBytes}} bytes; maximum {{maxBytes}} bytes).',
};
