export const zhHant = {
  'app.rendererFailed': '頁面渲染失敗',
  'app.rendererLogHint': '請開啟開發者工具查看 Renderer 日誌',
  'app.startupFailed': 'SEEKMORE 本機工作階段啟動失敗',
  'app.desktopBridgeFailed': '桌面橋接載入失敗，請重新啟動 SEEKMORE',

  'settings.general': '一般',
  'settings.model': '模型設定',
  'settings.data': '資料管理',
  'settings.help': '意見回饋與說明',
  'settings.moreComing': '更多設定選項即將推出...',
  'settings.appearance': '外觀',
  'settings.appearance.light': '明亮',
  'settings.appearance.dark': '暗色',
  'settings.language': '語言',
  'settings.languageDescription': '設定 SEEKMORE 的介面語言；「跟隨系統」使用目前裝置語言。',
  'settings.followSystem': '跟隨系統',
  'settings.simplifiedChinese': '简体中文',
  'settings.traditionalChinese': '繁體中文',
  'settings.english': 'English',
  'common.cancel': '取消',
  'common.notAvailable': '暫無',

  'chat.newConversation': '新對話',
  'chat.toggleSidebar': '切換側邊欄',
  'chat.openTimeRecords': '開啟時間記錄',
  'chat.latestConversation': '已是最新對話',
  'chat.titleGenerating': '標題生成中',
  'chat.expand': '展開',

  'runtime.currentTask': '正在執行目前任務',
  'runtime.tool.queued': '{{tool}}等待執行',
  'runtime.tool.running': '{{tool}}正在執行',
  'runtime.tool.succeeded': '{{tool}}已完成',
  'runtime.tool.failed': '{{tool}}執行失敗',
  'runtime.clarification.waiting': '等待使用者補充資訊',
  'runtime.clarification.title': '需要補充資訊',
  'runtime.step.analysisFirst': '分析任務並制定執行路徑',
  'runtime.step.analysisNext': '分析第 {{round}} 輪執行結果',
  'runtime.step.turnStart': '啟動智慧體執行',
  'runtime.step.verification': '驗證執行結果',
  'runtime.step.completed': '執行完成',
  'runtime.step.waiting': '等待繼續條件',
  'runtime.step.failed': '執行失敗：{{message}}',
  'runtime.result.failed': '工具執行失敗',
  'runtime.result.completed': '工具執行完成',
  'runtime.result.confirmation': '等待使用者確認',

  'runtime.status.queued': '排隊中',
  'runtime.status.running': '執行中',
  'runtime.status.waiting': '等待中',
  'runtime.status.blocked': '已阻止',
  'runtime.status.succeeded': '已完成',
  'runtime.status.failed': '失敗',
  'runtime.status.partial': '部分完成',
  'runtime.status.cancelled': '已取消',
  'runtime.status.skipped': '已跳過',
  'runtime.detail.input': '輸入',
  'runtime.detail.output': '輸出',
  'runtime.detail.error': '錯誤',
  'runtime.detail.evidence': '證據',
  'runtime.clarification.inputNeeded': '需要你的輸入',

  'time.title': '時間',
  'time.description': '提醒、事項、鬧鐘與計時',
  'time.refresh': '重新整理',
  'time.refreshing': '重新整理中',
  'time.section.due': '到時事項',
  'time.section.records': '時間記錄',
  'time.empty.due': '暫無到時事項',
  'time.empty.records': '暫無時間記錄',
  'time.defaultReminderTitle': '時間提醒',
  'time.reminderDue': '提醒時間已到',
  'time.kind.alarm': '鬧鐘',
  'time.kind.reminder': '提醒',
  'time.kind.event': '事項',
  'time.kind.countdown': '倒數計時',
  'time.kind.stopwatch': '碼錶',
  'time.status.triggered': '已到時',
  'time.status.paused': '已暫停',
  'time.status.running': '執行中',
  'time.status.scheduled': '已排程',
  'time.action.processing': '處理中',
  'time.action.snooze5': '稍後 5 分鐘',
  'time.action.snooze5Full': '稍後 5 分鐘提醒我',
  'time.action.complete': '完成',
  'time.action.resume': '繼續',
  'time.action.stop': '結束',
  'time.action.pause': '暫停',
  'time.action.cancel': '取消',

  'skills.source.BUILTIN': '官方',
  'skills.source.REPOSITORY': '從 GitHub 匯入',
  'skills.source.UPLOAD': '本機匯入',
  'skills.source.INLINE': '本機建立',
  'skills.source.IMPORTED': '本機匯入',
  'skills.source.AI_GENERATED': 'AI 建立',
  'skills.source.UNKNOWN': '未知來源',
  'skills.activation.MANUAL': '僅手動使用',
  'skills.activation.AUTOMATIC': '自動使用',
  'skills.activation.ALWAYS': '始終使用',
  'skills.activation.DISABLED': '已停用',
  'skills.version.DRAFT': '草稿',
  'skills.version.VALIDATING': '驗證中',
  'skills.version.PUBLISHED': '可用版本',
  'skills.version.REJECTED': '未通過',
  'skills.version.SUPERSEDED': '歷史版本',
  'skills.agentActivation.INHERIT': '跟隨認知體設定',
  'skills.agentActivation.MANUAL': '僅手動使用',
  'skills.agentActivation.AUTOMATIC': '自動使用',
  'skills.agentActivation.ALWAYS': '始終使用',
  'skills.agentActivationDescription.INHERIT': '依照認知體的預設 Skill 使用方式執行',
  'skills.agentActivationDescription.MANUAL': '只有使用者明確選擇時才使用',
  'skills.agentActivationDescription.AUTOMATIC': '任務相關時由認知體自動使用',
  'skills.agentActivationDescription.ALWAYS': '認知體執行任何任務時都會載入',
  'skills.agentActivation.current': '目前為{{mode}}',
  'skills.binding.summary': '已關聯 Skill 會依啟用狀態與優先順序排列。',
  'skills.binding.count': '{{count}} 項',
  'skills.binding.fallbackName': '已關聯 Skill',
  'skills.binding.deleted': '已刪除',
  'skills.binding.unavailable': 'Skill 資訊暫時無法使用',
  'skills.binding.unlink': '取消關聯',
  'skills.binding.usageMode': '使用方式',
  'skills.binding.deletedPreserved': '關聯與原設定已保留，恢復後會自動繼續使用',
  'skills.binding.priority': '優先順序',
  'skills.binding.priorityHint': '1 最優先，數字越小越靠前。',
  'skills.binding.restoreFirst': '此 Skill 已刪除，請先恢復 Skill。',
  'skills.binding.enabledDeleted': '已啟用（刪除期間暫停）',
  'skills.binding.pausedDeleted': '已暫停（Skill 已刪除）',
  'skills.binding.enabled': '已啟用',
  'skills.binding.paused': '已暫停',

  'skills.settings.title': 'Skill 使用設定',
  'skills.settings.defaultMode': '認知體預設使用方式',
  'skills.settings.defaultHint': '設為「跟隨認知體設定」的 Skill 會使用這裡的預設方式。',
  'skills.settings.linked': '關聯 Skill',
  'skills.settings.add': '新增 Skill',
  'skills.version.none': '暫無版本',
  'skills.loadingBindings': '正在載入關聯 Skill…',
  'agents.type.cognitive': '認知體',
  'agents.knowledge.status.READY': '已就緒',
  'agents.knowledge.status.PARSING': '解析中',
  'agents.knowledge.status.FAILED': '失敗',
  'agents.knowledge.status.PENDING': '等待解析',

  'recycle.unnamedConversation': '未命名對話',
  'recycle.messageCount': '{{count}} 則訊息',
  'recycle.deletedAt': '刪除於 {{date}}',
  'recycle.purgeAt': '永久刪除：{{date}}',
  'recycle.waitingCleanup': '等待清理',
  'recycle.remainingDays': '剩餘 {{count}} 天',
  'recycle.purgeSoon': '即將永久刪除',
  'recycle.collapse': '收起內容',
  'recycle.view': '查看內容',
  'recycle.restoring': '恢復中…',
  'recycle.restore': '恢復',
  'recycle.deleting': '刪除中…',
  'recycle.deletePermanently': '永久刪除',
  'recycle.loadingMessages': '正在載入訊息…',
  'recycle.noMessages': '暫無可顯示訊息。',
  'recycle.emptyMessage': '（空訊息）',
  'recycle.download': '下載',
  'common.role.USER': '使用者',
  'common.role.ASSISTANT': '助手',
  'common.role.SYSTEM': '系統',
  'common.role.TOOL': '工具',

  'agents.recycle.deleted': '已刪除',
  'agents.recycle.noDescription': '暫無描述',
  'agents.recycle.conversationCount': '{{count}} 個對話',
  'agents.recycle.messageCount': '{{count}} 則訊息',
  'agents.recycle.restore': '恢復使用',
  'agents.recycle.restoring': '恢復中…',
  'agents.recycle.delete': '徹底刪除',
  'agents.recycle.deleting': '刪除中…',
  'agents.recycle.coverAlt': '{{name}} 封面',
  'agents.recycle.avatarAlt': '{{name}} 頭像',

  'memory.status.active': '已生效',
  'memory.status.pending_confirmation': '候選',
  'memory.status.superseded': '已取代',
  'memory.status.deleted': '已刪除',
  'memory.status.conflicted': '衝突',
  'memory.kind.identity': '身分',
  'memory.kind.preference': '偏好',
  'memory.kind.constraint': '限制',
  'memory.kind.project_state': '專案狀態',
  'memory.kind.goal': '目標',
  'memory.kind.relationship': '關係',
  'memory.kind.workflow': '流程',
  'memory.kind.tool_preference': '工具偏好',
  'memory.kind.event': '事件',
  'memory.kind.episode': '片段',
  'memory.scope.user': '使用者',
  'memory.scope.agent': '智能體',
  'memory.scope.conversation': '對話',
  'memory.source.user': '全域記憶',
  'memory.source.agent': '智能體 {{id}}',
  'memory.source.conversation': '對話 {{id}}',
  'memory.sensitivity.normal': '一般',
  'memory.sensitivity.private': '私有',
  'memory.sensitivity.sensitive': '敏感',
  'memory.sensitivity.restricted': '受限',
  'memory.updatedAt': '更新 {{date}}',
  'memory.usageCount': '使用 {{count}}',
  'memory.action.promote': '晉升',
  'memory.action.restore': '恢復',
  'memory.action.purge': '清除',
  'memory.action.delete': '刪除',

  'skills.picker.deleted': '已刪除',
  'skills.picker.deletedLinkedHint': '關聯與原設定已保留，恢復後會自動繼續使用',
  'skills.picker.deletedUnlinkedHint': '此 Skill 已刪除，恢復後才能關聯',
  'skills.picker.createdAt': '建立於 {{date}}',
  'skills.picker.unlink': '取消關聯',
  'skills.picker.deletedCannotLink': '已刪除的 Skill 無法新增關聯',
  'skills.picker.linkTitle': '關聯 Skill',
  'skills.picker.link': '關聯',

  'tools.file.search.name': '搜尋檔案',
  'tools.file.read.name': '讀取檔案',
  'tools.file.write.name': '寫入檔案',
  'tools.file.patch.name': '修改檔案',
  'tools.file.delete.name': '刪除檔案',
  'tools.terminal.run.name': '執行終端指令',
  'tools.python.execute.name': '執行 Python',
  'tools.knowledge.search.name': '搜尋知識庫',
  'tools.web.search.name': '網路搜尋',

  'tools.skill_search.name': '搜尋 Skill',
  'tools.skill_view.name': '載入 Skill',
  'tools.skill_read_resource.name': '讀取 Skill 資源',
  'tools.time.name': '時間',
  'tools.automation.name': '自動任務',
  'tools.image.generate.name': '生成圖片',
  'tools.speech.synthesize.name': '生成語音',
  'tools.voice.clone.name': '複製聲音',
  'tools.music.generate.name': '生成音樂',
  'tools.video.general.name': '生成影片',
  'tools.video.generate.name': '生成影片',
  'tools.location.name': '位置',
  'tools.vision.analyze.name': '分析圖片',
  'tools.web.read.name': '讀取網頁',
  'tools.repository.inspect.name': '檢查程式碼倉庫',
  'tools.repository.list_tree.name': '讀取倉庫目錄',
  'tools.repository.read_file.name': '讀取倉庫檔案',
  'tools.workspace.inspect.name': '檢查工作區',
  'tools.terminal.read.name': '讀取終端工作階段',
  'tools.terminal.kill.name': '終止終端工作階段',
  'tools.git.status.name': '檢查 Git 狀態',
  'tools.git.diff.name': '查看 Git 差異',
  'tools.document.parse.name': '解析文件',
  'tools.object.search.name': '搜尋上傳檔案',
  'tools.object.inspect.name': '檢查上傳檔案',
  'tools.code_project.inspect.name': '檢查程式碼專案',
  'tools.document.render.docx.name': '生成 DOCX',
  'tools.document.render.pdf.name': '生成 PDF',
  'tools.spreadsheet.render.xlsx.name': '生成 XLSX',
  'tools.presentation.create.name': '建立簡報',
  'tools.presentation.slides.upsert.name': '建立或更新投影片',
  'tools.presentation.inspect.name': '檢查簡報',
  'tools.presentation.finalize.name': '完成簡報',
  'tools.presentation.render.pptx.name': '生成 PPTX',
  'tools.package.render.zip.name': '生成 ZIP',
  'tools.plugins.mcp_manage.name': '管理 MCP',
  'agents.system.seekmore-system-agent.description': '輕鬆工作 輕鬆生活',

  'explore.action.added': '已加入',
  'explore.action.authorize': '授權',
  'explore.action.add': '加入',
  'explore.action.installed': '已安裝',
  'explore.action.install': '安裝',
  'explore.action.connected': '已接入',
  'explore.action.connecting': '連線中',
  'explore.action.reconnect': '重新連線',
  'explore.action.configure': '設定',
  'explore.action.reconfigure': '重新設定',
  'explore.action.setup': '設定',
  'explore.action.disabled': '已停用',
  'explore.action.connect': '連線',
  'explore.type.agent': '認知體',
  'explore.type.skill': 'SKILL',
  'explore.coverAlt': '{{name}} 封面',
  'explore.avatarAlt': '{{name}} 頭像',
  'explore.noProductIntroduction': '暫無產品介紹',
  'explore.noMcpDescription': '暫無 MCP 能力說明',
  'common.noDescription': '暫無描述',

  'agents.loading': '正在載入智慧體…',
  'agents.empty': '暫無智慧體。',
  'agents.goChat': '前往聊天',
  'agents.processing': '處理中…',
  'agents.systemDefault': '系統預設',
  'agents.coverAlt': '{{name}} 封面',
  'agents.avatarAlt': '{{name}} 頭像',
  'common.back': '返回',

  'mcp.status.disabled': '已停用',
  'mcp.status.authorizationRequired': '待授權',
  'mcp.status.setupRequired': '待設定',
  'mcp.status.configurationRequired': '待設定',
  'mcp.status.connected': '已接入',
  'mcp.status.connecting': '連線中',
  'mcp.status.failed': '連線失敗',
  'mcp.status.disconnected': '未連線',
  'mcp.action.waitingAuthorization': '等待授權…',
  'mcp.action.authorize': '授權',
  'mcp.action.setup': '設定',
  'mcp.action.reconfigure': '重新設定',
  'mcp.action.configure': '設定',
  'mcp.action.connecting': '連線中…',
  'mcp.action.reconnect': '重新連線',
  'mcp.action.connect': '連線',
  'mcp.action.reauthorize': '重新授權',
  'mcp.action.refreshing': '重新整理中',
  'mcp.action.refresh': '重新整理',
  'mcp.action.revoke': '解除綁定',
  'mcp.action.uninstall': '解除安裝',
  'mcp.action.disable': '停用',
  'mcp.action.enable': '啟用',
  'approval.timeline.waiting.title': '需要確認執行',
  'approval.timeline.waiting.summary': '工具 {{tool}} 將執行受控操作',
  'approval.timeline.resolved.approved': '已確認執行',
  'approval.timeline.resolved.cancelled': '已取消執行',
  'approval.timeline.resolved.workspaceChanged': '工作區已切換，舊工作區中尚未執行的操作已取消',
  'approval.timeline.resolved.policyChanged': '審批模式已更新，目前操作已按新策略處理',
  'approval.card.title': '需要批准',
  'approval.action.allowOnce': '允許一次',
  'approval.action.auditOnly': '替我審批',
  'approval.action.fullAccessTask': '本任務完全存取',
  'approval.action.reject': '拒絕',
  'approval.checkpointCreating': '正在建立可恢復的審批檢查點…',
  'errors.requestFailed': '請求失敗，請稍後重試。',
  'errors.UNAUTHORIZED': '本機工作階段不可用，請重試。',
  'errors.AUTHORIZATION_HEADER_INVALID': '缺少或不合法的授權標頭。',
  'errors.ACCESS_TOKEN_REQUIRED': '缺少存取權杖。',
  'errors.ACCESS_TOKEN_INVALID': '存取權杖無效或已過期。',
  'errors.WORKSPACE_PARENT_UNAVAILABLE': '選擇的父目錄不存在或無法存取。',
  'errors.WORKSPACE_PARENT_OUTSIDE_ROOT': '父目錄不在允許的 workspace 根目錄範圍內。',
  'errors.WORKSPACE_PROJECT_EXISTS': '專案目錄已存在。',
  'errors.WORKSPACE_CREATE_FAILED': '專案目錄建立失敗。',
  'errors.WORKSPACE_UNREADABLE': '專案目錄建立後無法讀取。',
  'errors.WORKSPACE_UNAVAILABLE': '選擇的工作區目錄不存在或無法存取。',
  'errors.WORKSPACE_ROOT_FORBIDDEN': '不能將檔案系統根目錄註冊為工作區。',
  'errors.WORKSPACE_SENSITIVE_PATH_FORBIDDEN': '不能將系統敏感目錄註冊為工作區。',
  'errors.WORKSPACE_PROJECT_NAME_INVALID': '專案名稱無效。',
  'errors.WORKSPACE_PATH_INVALID': '專案路徑無效。',
  'errors.AGENT_NOT_FOUND': '助手不存在。',
  'errors.AGENT_ACCESS_DENIED': '你無權存取該助手。',
  'errors.SYSTEM_AGENT_REMOVE_FORBIDDEN': 'SEEKMORE 系統助手不可移除。',
  'errors.SYSTEM_AGENT_DELETE_FORBIDDEN': 'SEEKMORE 系統助手不可刪除。',
  'errors.COGNITIVE_AGENT_NOT_FOUND': '認知體不存在。',
  'errors.COGNITIVE_AGENT_ACCESS_DENIED': '無權存取該認知體。',
  'errors.COGNITIVE_AGENT_OWNER_REQUIRED': '只有擁有者可以操作該認知體。',
  'errors.COGNITIVE_AGENT_SYSTEM_MANAGED': 'SEEKMORE 系統助手由系統管理，不可修改。',
  'errors.KNOWLEDGE_FILE_NOT_FOUND': '知識庫檔案不存在。',
  'errors.KNOWLEDGE_FILE_EMPTY': '知識庫檔案未解析出可檢索內容。',
  'errors.CONVERSATION_NOT_FOUND': '對話不存在。',
  'errors.CONVERSATION_ACCESS_DENIED': '你無權存取此對話。',
  'errors.MESSAGE_NOT_FOUND': '訊息不存在。',
  'agents.capability.chat.name': '基礎對話',
  'agents.capability.chat.description': '允許 Agent 進行基礎對話與問答。',
  'agents.capability.file_reading.name': '讀取檔案',
  'agents.capability.file_reading.description': '允許 Agent 讀取使用者上傳的知識庫與檔案內容。',
  'agents.capability.file_render.name': '檔案生成',
  'agents.capability.file_render.description': '允許 Agent 使用內部檔案渲染能力生成交付檔案。',
  'agents.capability.docx_generation.name': 'Word 生成',
  'agents.capability.docx_generation.description': '允許 Agent 生成 Word 文件。',
  'agents.capability.xlsx_generation.name': 'Excel 生成',
  'agents.capability.xlsx_generation.description': '允許 Agent 生成 Excel 活頁簿。',
  'agents.capability.web_search.name': '聯網搜尋',
  'agents.capability.web_search.description': '允許 Agent 在需要最新資訊、官網資訊或資料來源時呼叫外部搜尋工具。',
  'agents.capability.image_generation.name': '圖片生成',
  'agents.capability.image_generation.description': '允許 Agent 呼叫外部圖片生成工具。',
  'agents.validation.NAME_TOO_SHORT': '名稱過短。',
  'agents.validation.DESCRIPTION_WEAK': '描述過短，建議說明適用場景和核心能力。',
  'agents.validation.ROLE_PROMPT_WEAK': '角色設定過短，無法形成穩定認知體行為。',
  'agents.validation.NO_CAPABILITIES': '至少需要設定一個能力。',
  'agents.validation.KNOWLEDGE_PARSE_FAILED': '有 {{count}} 個知識庫檔案解析失敗。',
  'agents.validation.KNOWLEDGE_PARSE_PENDING': '有 {{count}} 個知識庫檔案等待解析。',
  'errors.KNOWLEDGE_FILE_SELECTION_REQUIRED': '請選擇要上傳的知識庫檔案。',
  'errors.COGNITIVE_AGENT_DELETED_NOT_FOUND': '已刪除的認知體不存在。',
  'errors.COGNITIVE_AGENT_RETENTION_EXPIRED': '該認知體已超過 30 天保留期，無法恢復。',
  'errors.COGNITIVE_AGENT_OWNER_RELATION_MISSING': '認知體擁有權關係不存在，無法恢復。',
  'errors.AGENT_PROFILE_FILE_EMPTY': '{{field}} 檔案內容為空。',
  'errors.AGENT_PROFILE_FILE_WRITE_FAILED': '{{field}} 寫入失敗。',
  'errors.KNOWLEDGE_FILE_CONTENT_EMPTY': '知識庫檔案內容為空：{{fileName}}。',
  'errors.KNOWLEDGE_FILE_WRITE_FAILED': '知識庫檔案寫入失敗：{{fileName}}。',
  'errors.operationFailed': '操作失敗。',
  'errors.explore.loadFailed': 'Explore 載入失敗。',
  'errors.mcp.operationFailed': 'MCP 操作失敗。',
  'errors.mcp.statusLoadFailed': 'MCP 狀態載入失敗。',
  'errors.mcp.globalToggleFailed': 'MCP 總開關更新失敗。',
  'errors.mcp.toggleFailed': 'MCP 開關更新失敗。',
  'errors.mcp.loadFailed': 'MCP 載入失敗。',
  'errors.mcp.refreshFailed': 'MCP 狀態重新整理失敗。',
  'errors.mcp.connectStartFailed': '連線啟動失敗。',
  'errors.mcp.oauthFailed': 'MCP OAuth 授權失敗。',
  'errors.mcp.directoryLoadFailed': 'MCP 目錄載入失敗。',
  'errors.MCP_CONFIGURATION_REQUIRED': '請先完成 MCP 連線設定。',
  'errors.MCP_GLOBALLY_DISABLED': 'MCP 總開關已關閉，請先開啟總開關。',
  'errors.MCP_INSTALLATION_DISABLED': '該 MCP 已關閉，請先開啟後再連線。',
  'errors.MCP_CREDENTIAL_NOT_REQUIRED': '該 MCP 不需要設定存取憑證。',
  'errors.MCP_CREDENTIAL_VALUES_INVALID': '連線設定不完整或格式不正確。',
  'errors.MCP_CREDENTIAL_KEY_NOT_DECLARED': '設定項與該 MCP 宣告的欄位不一致。',
  'errors.MCP_CREDENTIAL_DECLARATION_INCOMPLETE': '請填寫全部必要的連線設定。',
  'errors.MCP_BEARER_TOKEN_REQUIRED': '請填寫存取權杖。',
  'errors.MCP_API_KEY_REQUIRED': '請填寫 API Key。',
  'errors.MCP_HEADER_VALUE_INVALID': '請求標頭設定格式不正確。',
  'errors.MCP_AUTHORIZATION_REQUIRED': '請先登入並授權該 MCP 服務。',
  'errors.MCP_OAUTH_AUTHORIZATION_REQUIRED': '請先登入並授權該 MCP 服務。',
  'errors.MCP_LOCAL_SETUP_REQUIRED': '請先完成本機或自託管服務設定。',
  'errors.MCP_CREDENTIAL_INVALID': '目前憑證無效，請重新設定。',
  'errors.MCP_CONNECTION_FAILED': 'MCP 連線失敗，請檢查服務位址和存取憑證。',
  'errors.MCP_DESKTOP_BRIDGE_UNAVAILABLE': '桌面連線服務不可用，請確認正在 SEEKMORE 桌面端中操作。',
  'common.actions.collapse': '收起',
  'common.actions.expandAll': '展開全部',
  'common.actions.edit': '編輯',
  'common.actions.pause': '暫停',
  'common.actions.resume': '繼續',
  'common.actions.save': '儲存',
  'automation.errors.actionFailed': '自動任務操作失敗，請稍後重試',
  'automation.errors.required': '任務名稱和執行內容不能為空',
  'automation.errors.invalidRunAt': '請選擇有效的執行時間',
  'automation.cancel.confirmTitle': '結束「{{title}}」？',
  'automation.cancel.confirmDescription': '結束後將不再自動執行此任務，歷史訊息仍會保留。',
  'automation.actions.end': '結束任務',
  'automation.fields.frequency': '執行頻率',
  'automation.fields.delivery': '回報方式',
  'automation.fields.endAt': '結束時間',
  'automation.fields.maxRuns': '最多執行',
  'automation.fields.completionCondition': '結束條件',
  'automation.fields.validity': '有效期',
  'automation.fields.nextRun': '下次執行',
  'automation.fields.remaining': '剩餘',
  'automation.fields.completedAt': '完成時間',
  'automation.fields.title': '任務名稱',
  'automation.fields.instruction': '執行內容',
  'automation.fields.every': '每隔',
  'automation.fields.unit': '單位',
  'automation.fields.maxRunsInput': '最多執行次數',
  'automation.fields.runAt': '執行時間',
  'automation.fields.nextStartOptional': '下次起始時間（可選）',
  'automation.delivery.always': '每次執行後回報',
  'automation.delivery.onCompletion': '滿足結束條件時回報',
  'automation.validity.indefinite': '直到手動結束',
  'automation.validity.indefiniteLong': '長期執行，直到我手動結束',
  'automation.status.ACTIVE': '執行中',
  'automation.status.PAUSED': '已暫停',
  'automation.status.COMPLETED': '已完成',
  'automation.status.CANCELLED': '已結束',
  'automation.unit.minute': '分鐘',
  'automation.unit.hour': '小時',
  'automation.unit.day': '天',
  'automation.unit.week': '週',
  'automation.frequency.once': '一次 · {{time}}',
  'automation.frequency.everyOne': '每{{unit}}',
  'automation.frequency.everyMany': '每 {{count}} {{unit}}',
  'automation.completion.default': '滿足設定條件後自動結束',
  'automation.remaining.soon': '即將結束',
  'automation.remaining.days': '{{count}} 天',
  'automation.remaining.hours': '{{count}} 小時',
  'automation.unit.times': '次',
  'common.actions.deleting': '刪除中…',
  'common.actions.delete': '刪除',
  'common.actions.title': '操作',
  'common.iconAlt': '{{name}} 圖示',
  'common.status.deleted': '已刪除',
  'common.priority': '優先順序',
  'common.basicInfo': '基本資訊',
  'common.type': '類型',
  'common.visibility': '可見性',
  'common.createdAt': '建立時間',
  'common.updatedAt': '更新時間',
  'common.untitledFile': '未命名檔案',
  'agents.skills.loadFailed': '關聯 Skill 載入失敗',
  'agents.detail.unsupportedEditor': '此智慧體類型尚未接入編輯器',
  'agents.detail.unsupportedDelete': '此智慧體類型的刪除流程尚未接入',
  'agents.detail.deleteFailed': '刪除失敗，請稍後重試',
  'agents.knowledge.title': '知識庫',
  'agents.knowledge.search': '知識搜尋',
  'agents.knowledge.available': '可用',
  'agents.knowledge.waitingReady': '等待資料就緒',
  'agents.knowledge.noSearchable': '暫無可搜尋資料',
  'agents.knowledge.fileCount': '共 {{count}} 個檔案',
  'agents.knowledge.parsing': '解析中…',
  'agents.knowledge.reparse': '重新解析',
  'agents.knowledge.uploading': '上傳中…',
  'agents.knowledge.add': '新增資料',
  'agents.knowledge.loading': '正在載入知識庫…',
  'agents.knowledge.empty': '此智慧體尚未上傳知識庫資料。',
  'agents.knowledge.deleteConfirmTitle': '確認刪除此知識庫檔案？',
  'agents.knowledge.deleteConfirmDescription': '將從此認知體知識庫移除「{{name}}」，後續知識搜尋不會再使用此檔案。',
  'agents.skills.title': '關聯 Skill',
  'agents.skills.count': '共 {{count}} 個',
  'agents.skills.empty': '此認知體尚未關聯 Skill。',
  'agents.role.title': '角色設定',
  'agents.role.empty': '暫無角色設定',
  'agents.actions.goChat': '前往聊天',
  'agents.actions.edit': '編輯智慧體',
  'agents.actions.delete': '刪除智慧體',
  'agents.delete.confirmTitle': '確認刪除此智慧體？',
  'agents.delete.confirmDescription': '刪除後將停用並移至認知體已刪除面板，全部設定和歷史資料保留 30 天。期間可恢復使用；到期後將自動永久刪除，無法恢復。',
  'agents.title': '認知體',
  'agents.library.mine': '我的認知體',
  'agents.library.deletedDescription': '刪除後完整保留 30 天，可恢復使用；到期後將自動永久刪除。',
  'agents.library.description': '管理你建立的認知、推理與協作智慧體。',
  'agents.actions.create': '+ 建立認知體',
  'agents.library.count': '共 {{count}} 個認知體',
  'agents.purge.confirmTitle': '確認永久刪除此認知體？',
  'agents.purge.confirmDescription': '此操作將永久刪除「{{name}}」的全部設定、{{conversationCount}} 個歷史對話、{{messageCount}} 則訊息、知識庫、Skill 關聯和執行資料。刪除後無法恢復。',
  'agents.actions.purge': '永久刪除',
  'common.coverAlt': '{{name}} 封面',
  'common.processing': '處理中…',
  'common.author': '作者',
  'common.source': '來源',
  'skills.detail.loadFailed': '載入 Skill 失敗',
  'skills.detail.restoreFailed': '恢復 Skill 失敗',
  'skills.detail.statusUpdateFailed': 'Skill 狀態更新失敗',
  'skills.detail.deleteFailed': '刪除 Skill 失敗',
  'skills.detail.loading': '正在載入 Skill…',
  'skills.detail.draftVersion': '草稿版本',
  'skills.detail.unknownAuthor': '未知作者',
  'skills.detail.activationMode': '啟用模式',
  'skills.detail.bindingCount': '關聯次數',
  'skills.detail.usageCount': '使用次數',
  'skills.detail.versionCount': '版本數量',
  'skills.detail.retentionInfo': '刪除保留資訊',
  'skills.detail.retention30Days': '保留 30 天',
  'skills.detail.deletedAt': '刪除時間',
  'skills.detail.purgeAt': '預計永久清理時間',
  'skills.detail.restoreScopeHint': '恢復只會恢復 Skill 本體，不會自動重新啟用刪除前的 Agent 關聯、會話啟用或安裝記錄。',
  'skills.detail.noMarkdown': '暫無 SKILL.md 內容',
  'skills.detail.restoring': '正在恢復…',
  'skills.detail.restore': '恢復使用',
  'skills.detail.edit': '編輯 Skill',
  'skills.detail.archive': '封存 Skill',
  'skills.detail.delete': '刪除 Skill',
  'skills.detail.currentVersion': '目前版本',
  'skills.detail.trustLevel': '信任等級',
  'skills.detail.installCount': '安裝數量',
  'skills.detail.lastUsed': '最後使用',
  'skills.detail.versionHistory': '版本歷史',
  'skills.detail.versionCountValue': '共 {{count}} 個',
  'skills.detail.noVersionRecords': '暫無版本記錄。',
  'skills.detail.deleteConfirmTitle': '確認刪除此 Skill？',
  'skills.detail.deleteConfirmDescription': '刪除後將進入已刪除面板，並從我的 Skill 和所有使用位置中移除。保留期內可以恢復。',
  'common.actions.close': '關閉',
  'common.loading': '正在載入…',
  'common.optional': '可選',
  'common.files': '檔案',
  'common.saving': '正在儲存…',
  'skills.editor.templateDescription': '說明這個 Skill 能做什麼，以及應在什麼情況下使用。',
  'skills.editor.templateHeading': '使用說明',
  'skills.editor.templateBody': '在這裡編寫可重複使用的執行步驟。',
  'skills.editor.loadFailed': 'Skill 載入失敗',
  'skills.editor.prepareDraftFailed': '無法準備可編輯檔案版本',
  'skills.editor.fileRefreshFailed': '檔案重新整理失敗',
  'skills.editor.saveFailed': 'Skill 儲存失敗',
  'skills.editor.editTitle': '編輯 Skill',
  'skills.editor.createTitle': '建立 Skill',
  'skills.editor.description': '編輯原生 SKILL.md 與版本檔案；已發布版本會先建立新的可編輯草稿。',
  'skills.editor.name': 'Skill 名稱',
  'skills.editor.namePlaceholder': '例如：前端設計-通用',
  'skills.editor.nameHint': '可以直接使用目前語言命名；內部識別由系統維護。',
  'skills.editor.editSource': '目前編輯來源',
  'skills.editor.newDocument': '新文件',
  'skills.editor.versionFiles': '版本檔案',
  'skills.editor.fileCount': '{{count}} 個檔案',
  'skills.editor.noVersionYet': '尚未建立版本',
  'skills.editor.changeLog': '版本說明',
  'skills.editor.package.main': 'SKILL.md · 主指令文件',
  'skills.editor.package.reference': 'REFERENCE · 參考資料',
  'skills.editor.package.script': 'SCRIPT · 可執行腳本',
  'skills.editor.package.asset': 'ASSET · 靜態資源',
  'skills.editor.package.other': 'LICENSE / OTHER · 其他檔案',
  'skills.editor.diagnostics': '驗證診斷',
  'skills.editor.diagnosticLocation': '第 {{line}} 行{{column}} · ',
  'skills.editor.filesCreateFirst': '先建立 Skill 草稿，之後即可上傳 reference、script、asset、license 與其他版本檔案。',
  'skills.editor.preparingDraft': '正在建立可編輯草稿版本…',
  'skills.editor.currentVersionLocked': '目前版本不能直接修改。系統正在基於目前版本準備新的草稿版本。',
  'skills.editor.saveNewVersion': '儲存新版本',
  'common.actions.add': '+ 新增',
  'skills.create.recognition.waiting': '等待自動識別…',
  'skills.create.recognition.inspecting': '正在自動識別 Skill Package…',
  'skills.create.recognition.standard': '已自動識別 · 標準相容',
  'skills.create.recognition.compatible': '已自動識別 · 相容模式',
  'skills.create.recognition.rejected': '自動識別完成 · 存在阻斷錯誤',
  'skills.create.recognition.idle': '上傳或輸入後將自動識別',
  'skills.create.importTitle': '匯入 Skill',
  'skills.create.nameHint': '可以直接使用目前語言命名。系統會在背景自動產生並維護穩定的內部識別。',
  'skills.create.instructions': '使用說明',
  'skills.create.instructionsPlaceholder': '說明 Skill 能做什麼，以及 Agent 應在什麼情況下使用它。',
  'skills.create.license': '開源授權',
  'skills.create.compatibility': '相容說明',
  'skills.create.compatibilityPlaceholder': '僅在存在明確執行環境要求時填寫。',
  'skills.create.metadataHint': '鍵和值均以字串儲存。',
  'skills.create.allowedTools': '允許使用的工具',
  'skills.create.optionalExperimental': '可選 · 實驗性',
  'skills.create.allowedToolsHint': '此實驗欄位僅作為可攜式宣告，不取代執行階段權限與安全控制。',
  'skills.create.autoRecognizeAfterInput': '停止輸入後自動識別。',
  'skills.create.rawMarkdown': '原始 SKILL.md',
  'skills.create.importPlaceholder': '---\nname: imported-skill\ndescription: 說明這個 Skill 的用途。\n---\n\n# 使用說明',
  'skills.create.importPreserveHint': '匯入會保留原始 Skill Package；非關鍵規範偏差僅顯示相容性提示，不會呼叫 AI 改寫內容。',
  'mcp.definition.editTitle': '編輯 MCP',
  'mcp.definition.addTitle': '新增 MCP',
  'mcp.definition.description': '建立一個可供所有 Agent 重複使用的 MCP Definition',
  'mcp.definition.namePlaceholder': '名稱',
  'mcp.transport.streamableHttp': '遠端 Streamable HTTP',
  'mcp.transport.stdio': '本機 stdio',
  'mcp.definition.descriptionPlaceholder': '描述',
  'mcp.definition.commandPlaceholder': 'command，例如 uvx',
  'mcp.definition.workingDirectoryPlaceholder': '工作目錄（可選）',
  'mcp.definition.argsPlaceholder': '每行一個參數\n例如：--stdio',
  'mcp.auth.none': '無驗證',
  'mcp.auth.environment': '環境變數 Secret',
  'mcp.auth.oauth2': 'OAuth 瀏覽器授權',
  'mcp.auth.customHeaders': '自訂 Header',
  'mcp.definition.apiKeyHeaderPlaceholder': 'API Key Header 名稱，例如 X-API-Key',
  'mcp.definition.headerNamesPlaceholder': '每行一個允許的 Header 名稱',
  'mcp.definition.environmentKeysPlaceholder': '每行一個允許的環境變數名稱，例如 SERVICE_API_TOKEN',
  'mcp.definition.stdioHint': '儲存只會建立 Definition。連線時才會由 Electron Desktop Connector Host 彈窗確認並啟動命令。',
  'mcp.definition.oauthHint': '安裝後點擊「授權」，SEEKMORE 會依 MCP OAuth 規範發現授權服務，並在系統瀏覽器完成登入。',
  'mcp.import.title': '匯入 MCP',
  'mcp.import.description': '貼上 MCP JSON 設定，語法高亮即時預覽',
  'mcp.import.safetyHint': '匯入只會建立 Definition，不會連線或執行本機命令。Secret 值不會進入 Definition。',
  'mcp.import.willCreate': '將建立：{{names}}',
  'mcp.import.importing': '匯入中…',
  'mcp.import.confirm': '確認匯入',
  'mcp.detail.selectInstallation': '選擇一個已安裝 MCP 查看連線狀態與工具',
  'mcp.detail.toolCount': '{{count}} 個可用工具',
  'mcp.detail.editDefinition': '編輯 Definition',
  'mcp.detail.availableTools': '可用工具',
  'mcp.detail.toolsHint': '此 MCP 連線後，工具會全部進入可用工具池，呼叫仍經過統一權限策略。',
  'mcp.detail.noTools': '尚未發現工具，請先連線並重新整理。',
  'mcp.connectionFailed': '{{name}} 連線失敗',
  'mcp.panel.description': '管理已安裝服務、自訂 Definition、連線設定和可用工具。',
  'mcp.panel.create': '+ 建立 MCP',
  'mcp.panel.import': '匯入 MCP',
  'mcp.panel.installedCount': '共 {{count}} 個已安裝 MCP',
  'mcp.panel.loading': '正在載入 MCP…',
  'mcp.panel.emptyInstalled': '暫無已安裝 MCP。',
  'mcp.confirm.revokeAuthorization': '確認解除 {{name}} 的授權？',
  'mcp.confirm.uninstall': '確認解除安裝 {{name}}？',
  'mcp.panel.userDefinitionsCount': '使用者建立的 MCP Definition · {{count}}',
  'mcp.panel.custom': '自訂',
  'mcp.transport.localStdio': '本機 stdio',
  'mcp.actions.install': '安裝',
  'mcp.confirm.deleteDefinition': '確認刪除 {{name}}？',
  'mcp.panel.emptyDefinitions': '暫無使用者建立的 MCP Definition。',
  'mcp.credential.token': '存取權杖',
  'mcp.credential.endpoint': 'MCP 服務位址',
  'mcp.credential.connectionString': '連線字串',
  'mcp.credential.environmentId': '環境 ID',
  'mcp.credential.username': '使用者名稱',
  'mcp.credential.authorizationHeader': 'Authorization 請求標頭',
  'mcp.credential.endpointDescription': '填寫廠商控制台或自架服務提供的完整 MCP 位址。',
  'mcp.credential.connectionStringDescription': '填寫服務提供的完整連線字串。',
  'mcp.credential.redisUrlDescription': '填寫 Redis 服務連線位址。',
  'mcp.credential.environmentIdDescription': '填寫需要連線的雲端環境識別碼。',
  'mcp.credential.usernameDescription': '填寫該服務要求的使用者名稱。',
  'mcp.credential.authorizationDescription': '填寫廠商要求的完整 Authorization 值。',
  'mcp.credential.secretDescription': '僅用於連線此 MCP，儲存後不會在介面中以明文回傳。',
  'common.inputPlaceholder': '請輸入…',
  'mcp.credential.setupTitle': '設定 {{name}}',
  'mcp.credential.updateTitle': '更新設定 {{name}}',
  'mcp.credential.configureTitle': '設定 {{name}}',
  'mcp.credential.storageHint': '本機 stdio Secret 只寫入 Electron safeStorage；遠端憑證由後端加密儲存。',
  'mcp.credential.freeformHintBefore': '此自訂 Definition 未宣告固定欄位，請按每行',
  'mcp.credential.freeformHintAfter': '填寫。',
  'mcp.credential.save': '儲存設定',
  'errors.MCP_OAUTH_REVOKED': 'MCP OAuth 授權已撤銷。',
  'errors.MCP_OAUTH_PENDING': 'MCP OAuth 授權尚未完成，可再次點選授權繼續。',
  'common.name': '名稱',
  'common.description': '描述',
  'common.actions.cancel': '取消',
  'common.actions.done': '完成',
  'common.actions.removeFile': '移除檔案',
  'common.listSeparator': '、',
  'agents.edit.loadFailed': '載入認知體失敗',
  'agents.edit.saveFailed': '儲存認知體失敗',
  'agents.edit.title': '編輯認知體',
  'agents.edit.description': '修改角色、內容知識庫與關聯 Skill',
  'agents.edit.namePlaceholder': '要叫什麼好呢',
  'agents.edit.descriptionPlaceholder': '描述使用情境',
  'agents.role.placeholder': '身份、性格、行為準則、說話風格等',
  'agents.knowledge.contentLibrary': '內容知識庫',
  'agents.knowledge.reparseAll': '重新解析全部',
  'agents.knowledge.existingFiles': '已有資料',
  'agents.knowledge.loadingExisting': '正在載入已有知識…',
  'agents.knowledge.newFiles': '本次新增',
  'agents.knowledge.uploadContent': '上傳內容資料',
  'agents.knowledge.uploadDescription': '上傳專案資料、政策文件和參考內容，用於知識召回。',
  'agents.knowledge.contentMaterials': '內容資料',
  'agents.knowledge.contentMaterial': '內容資料',
  'agents.create.failed': '建立認知體失敗',
  'agents.create.title': '建立認知體',
  'agents.create.description': '定義角色、內容知識庫與關聯 Skill',
  'agents.create.name': '我的名稱',
  'agents.create.namePlaceholder': '為我取一個名字',
  'agents.create.descriptionPlaceholder': '我要做什麼',
  'agents.create.role': '我的角色設定',
  'agents.create.rolePlaceholder': '我的身份、性格、行為準則、說話風格等',
  'agents.create.creating': '建立中…',
  'agents.create.create': '建立',
  'skills.picker.addTitle': '新增 Skill',
  'skills.picker.description': '從我的 Skill 中選擇並關聯',
  'skills.picker.searchPlaceholder': '搜尋我的 Skill',
  'skills.picker.loading': '正在載入 Skill…',
  'skills.picker.empty': '沒有找到可關聯的 Skill',
  'skills.picker.linkedCount': '已關聯 {{count}} 項',
  'settings.model.currentPrimary': '目前主模型',
  'settings.model.primarySupportsVision': '{{model}} 已支援圖片理解，您仍可選擇更合適的服務，儲存後將優先使用您的選擇。',
  'settings.model.primarySupportsImageGeneration': '{{model}} 已支援圖像生成，您仍可選擇更合適的服務，儲存後將優先使用您的選擇。',
  'settings.model.capability.speechGeneration': '語音生成',
  'settings.model.capability.voiceCloning': '聲音複製',
  'settings.model.capability.musicGeneration': '音樂生成',
  'settings.model.primarySupportsAudio': '{{model}} 已支援{{capabilities}}，您仍可選擇更合適的服務，儲存後將優先使用您的選擇。',
  'settings.model.validatingAndSaving': '正在驗證並儲存…',
  'settings.model.saved': '設定已儲存。',
  'settings.model.clearing': '正在清除設定…',
  'settings.model.cleared': '設定已清除。',
  'settings.model.clearConfirmTitle': '清除目前設定？',
  'settings.model.clearConfirmDescription': '將清除目前能力已儲存的設定，並立即生效。',
  'settings.model.title': '模型設定',
  'settings.model.description': '為主模型、視覺識別、圖像生成、影片生成、音訊生成和聯網搜尋選擇服務。',
  'settings.model.loadingCatalog': '正在載入模型目錄…',
  'settings.model.primary.title': '主模型',
  'settings.model.primary.description': '負責對話、推理和工具呼叫。',
  'settings.model.vision.title': '視覺識別',
  'settings.model.vision.description': '優先使用您選擇的視覺模型；未選擇時才使用主模型原生視覺能力。',
  'settings.model.image.title': '圖像生成',
  'settings.model.image.description': '為 image.generate 提供文生圖、參考圖生成和圖片編輯能力。',
  'settings.model.video.title': '影片生成',
  'settings.model.video.description': '為 video.generate 選擇影片生成服務和模型。',
  'settings.model.video.service': '影片生成服務',
  'settings.model.video.model': '影片生成模型',
  'settings.model.video.apiKey': '影片生成 API Key',
  'settings.model.video.apiKeyHint': '儲存的服務和模型將作為 video.generate 的預設路由；API Key 會重用該服務現有憑據。',
  'settings.model.capability.textToVideo': '文字生成影片',
  'settings.model.capability.imageToVideo': '圖片生成影片',
  'settings.model.capability.firstLastFrame': '首尾幀生成',
  'settings.model.capability.referenceImages': '參考圖生成',
  'settings.model.capability.generatedAudio': '原生音訊',
  'recycle.confirmPermanentTitle': '永久刪除此會話？',
  'recycle.confirmPermanentDescription': '「{{title}}」及其未被其他會話引用的訊息、檔案和生成結果將被永久刪除，且無法復原。',
  'recycle.title': '資源回收桶',
  'recycle.description': '單獨刪除的 Conversation 按智能體歸類保留 30 天，期間可以復原。',
  'recycle.agentInUse': '使用中',
  'recycle.deletedConversationCount': '{{count}} 個已刪除會話',
  'chat.agentActions.remarkPrompt': '修改備註：',
  'chat.agentActions.remarkFailed': '備註失敗，請稍後重試',
  'chat.agentActions.pinFailed': '置頂失敗，請稍後重試',
  'chat.agentActions.shareComingSoon': '分享功能即將推出',
  'chat.agentActions.reportComingSoon': '檢舉功能即將推出',
  'chat.agentActions.systemAgentCannotRemove': 'SEEKMORE 系統助手不可移除',
  'chat.agentActions.removeConfirm': '確認從聊天列表移除此助手？你仍可在「我的智能體」中找回。',
  'chat.agentActions.removeFailed': '移除失敗，請稍後重試',
  'common.actions.back': '← 返回',
  'common.actions.refresh': '重新整理',
  'common.actions.clear': '清除',
  'skills.library.mine': '我的 Skill',
  'skills.library.drafts': '草稿',
  'skills.library.archived': '封存',
  'skills.library.deleted': '已刪除',
  'skills.library.actionFailed': 'Skill 狀態操作失敗',
  'skills.library.purgeTitle': '徹底刪除 Skill？',
  'skills.library.purgeDescription': '此操作會立即從資料庫永久刪除「{{name}}」，所有版本、檔案和關聯記錄都將永久移除，且無法復原。',
  'skills.library.purge': '徹底刪除',
  'skills.library.deletedDescription': '查看並復原仍處於保留期內的 Skill。',
  'skills.library.description': '建立、匯入、驗證並管理認知體可用的本機 Skill。',
  'skills.library.create': '+ 建立 Skill',
  'skills.library.searchDeleted': '搜尋已刪除 Skill',
  'skills.library.search': '搜尋名稱或描述',
  'skills.library.count': '共 {{count}} 個 Skill',
  'skills.library.retentionWarning': '已刪除的 Skill 將保留 30 天，到期後會自動從資料庫徹底刪除，所有版本、檔案和關聯記錄將永久移除且無法復原。',
  'skills.library.loading': '正在載入 Skill…',
  'skills.library.emptyDeleted': '暫無處於保留期內的已刪除 Skill。',
  'skills.library.empty': '暫無符合條件的 Skill。',
  'settings.model.audio.title': '音訊生成',
  'settings.model.audio.description': '選擇用於語音生成、聲音複製和音樂生成的服務。',
  'settings.model.audio.service': '音訊生成服務',
  'settings.model.selectService': '請選擇服務',
  'settings.model.audio.apiKey': '音訊生成 API Key',
  'settings.model.audio.apiKeyHint': 'API Key 儲存時不驗證方案和介面權限；實際呼叫時只限制目前不可用的能力，不影響其他音訊能力。',
  'settings.model.saveSettings': '儲存設定',
  'settings.model.configured': '已設定',
  'settings.model.capability.unsupported': '不支援',
  'settings.model.capability.paidOnly': '需付費訂閱',
  'settings.model.capability.planDependent': '取決於帳戶權限',
  'settings.model.capability.freeCredits': '支援免費額度',
  'settings.model.capability.available': '可用',
  'settings.model.web.title': '聯網搜尋',
  'settings.model.web.description': '為 web.search 設定使用者自己的搜尋服務。未設定時，主模型只會收到能力不可用狀態。',
  'settings.model.web.service': '搜尋服務',
  'settings.model.web.apiKey': '聯網搜尋 API Key',
  'explore.empty': '暫無可用資源',
  'explore.searchResults': '搜尋結果',
  'explore.featured': '精選資源',
  'explore.popular': '熱門資源',
  'tools.library.title': '工具',
  'tools.library.description': 'SEEKMORE 系統工具',
  'tools.library.count': '共 {{count}} 個工具',
  'workspace.readOnly': '唯讀',
  'workspace.none': '不使用專案',
  'workspace.unavailable': '專案不可用',
  'workspace.loadFailed': '載入工作區失敗',
  'workspace.desktopOnly': '此功能僅支援 SEEKMORE 桌面端',
  'workspace.bridgeLoading': '桌面橋接正在載入，請稍後重試',
  'workspace.bridgeFailed': '桌面橋接載入失敗，請重新啟動 SEEKMORE',
  'workspace.pickerFailed': '無法開啟資料夾選擇器，請查看桌面執行記錄',
  'workspace.openFolderFailed': '開啟資料夾失敗',
  'workspace.searchPlaceholder': '搜尋工作專案',
  'workspace.empty': '暫無專案',
  'workspace.newProject': '新工作專案',
  'workspace.createBlank': '建立空白專案',
  'workspace.useExistingFolder': '使用現有資料夾',
  'skills.preview.standard': '標準相容',
  'skills.preview.compatible': '相容模式',
  'skills.preview.rejected': '無法建立',
  'skills.preview.inspecting': '正在識別',
  'skills.preview.waiting': '等待識別',
  'skills.preview.standardHint': '「儲存草稿」和「直接使用」只使用這裡的原始內容。',
  'skills.preview.importHint': '上傳或輸入後自動識別，顯示實際解析的原始 SKILL.md。',
  'skills.preview.template': '---\nname: skill-draft\ndescription: 說明這個 Skill 能做什麼，以及應在什麼情況下使用。\n---\n\n# 使用說明\n',
  'skills.preview.packageContent': '套件內容',
  'skills.preview.untitled': '未命名 Skill',
  'skills.preview.onlySkillMd': '僅 SKILL.md',
  'skills.preview.canRunStandard': '可建立並執行 · 符合 Agent Skills 標準',
  'skills.preview.canRun': '可建立並執行',
  'skills.preview.warningCount': ' · 存在 {{count}} 項標準相容性提示',
  'skills.preview.compatibleSuffix': ' · 相容模式',
  'skills.preview.blockingCount': ' · 存在 {{count}} 項阻斷錯誤',
  'skills.preview.diagnostics': '驗證診斷',
  'skills.preview.linePrefix': '第 {{line}} 行{{column}} · ',
  'skills.preview.warningNonBlocking': '不影響建立和執行',
  'chat.missingModel.title': '尚未設定模型',
  'chat.missingModel.description': '請先在模型設定中選擇模型並填寫 API Key，儲存後即可傳送訊息。',
  'chat.missingModel.openSettings': '前往設定',
  'chat.missingModel.later': '稍後再說',
  'chat.restore.failed': '會話復原失敗',
  'chat.restore.loading': '正在復原會話',
  'common.actions.retry': '重試',
  'mcp.dropdown.globalToggle': 'MCP 總開關',
  'mcp.dropdown.searchPlaceholder': '搜尋 MCP 服務',
  'agents.image.avatarPreview': '認知體頭像預覽',
  'agents.image.avatar': '頭像',
  'agents.image.coverPreview': '認知體封面預覽',
  'agents.image.cover': '封面',
  'skills.create.modalTitle': '建立 Skill',
  'skills.create.modalDescription': '建立、AI 生成或匯入 Agent Skill Package',
  'runtime.status.completed': '執行完成',
  'common.actions.view': '查看',
  'common.actions.download': '下載',
  'chat.attachments.add': '新增附件',
  'chat.attachments.count': '{{count}} 個附件',
  'chat.branch.startHere': '從此處開始新的對話分支',
  'chat.branch.createHere': '從這裡建立分支',
  'chat.branch.create': '建立對話分支',
  'chat.image.generating': '圖片生成中',
  'chat.history.empty': '暫無歷史對話',
  'chat.contact.remarkPlaceholder': '輸入備註...',
  'chat.search.conversations': '對話',
  'chat.search.browserTitle': '搜尋「{{query}}」',
  'chat.search.browserSubtitle': '前往瀏覽器搜尋',
  'chat.search.agents': '助手',
  'chat.audio.unsupportedBrowser': '您的瀏覽器不支援音訊播放。',
  'chat.jumpToBottom': '回到底部',
  'explore.categories': '探索分類',
  'explore.searchPlaceholder': '搜尋認知體或 SKILL',
  'webSearch.card.query': '搜尋內容',
  'webSearch.card.sources': '高相關來源',
  'webSearch.card.openBrowser': '在瀏覽器中開啟',
  'workspace.create.namePlaceholder': '專案名稱，例如 test',
  'workspace.create.name': '專案名稱',
  'charts.config': '圖表設定',
  'charts.themeColor': '主題顏色',
  'skills.files.title': '檔案',
  'skills.files.versionFileCount': '{{count}} 個版本檔案',
  'skills.files.uploadHint': '上傳支援單一檔案、多個檔案和完整資料夾。選擇完整 Skill 根目錄時，SKILL.md 仍由文件編輯區管理。',
  'memory.savedTitle': '儲存的記憶',
  'memory.savedDescription': '資料管理 · 候選記憶不會預設注入上下文。',
  'memory.backToData': '返回資料管理',
  'sidebar.extensions.reading': '閱讀',
  'sidebar.extensions.shortVideo': '短影片',
  'sidebar.extensions.community': '社群',
  'sidebar.user.avatarAlt': '使用者頭像',
  'sidebar.user.changeAvatar': '更換頭像',
  'sidebar.user.editProfile': '點擊設定資料',
  'sidebar.user.profileTitle': '使用者資料',
  'sidebar.user.username': '使用者名稱',
  'sidebar.user.usernamePlaceholder': '輸入使用者名稱',
  'sidebar.user.saveFailed': '儲存使用者資料失敗',
  'common.search': '搜尋',
  'common.pagination.previous': '上一頁',
  'common.pagination.next': '下一頁',
  'chat.input.dropFiles': '拖曳檔案到這裡上傳',
  'mcp.dropdown.disableGlobal': '關閉 MCP 總開關',
  'mcp.dropdown.enableGlobal': '開啟 MCP 總開關',
  'mcp.dropdown.enabled': '已開啟',
  'mcp.dropdown.disabled': '已關閉',
  'mcp.dropdown.empty': '暫無 MCP 服務',
  'mcp.dropdown.noMatch': '沒有符合的 MCP 服務',
  'workspace.permission.confirm.title': '請求批准',
  'workspace.permission.confirm.description': '讀取直接執行，寫入、修改、命令和外部副作用逐次請求批准',
  'workspace.permission.audit.title': '替我審批',
  'workspace.permission.audit.description': '低風險和中風險自動執行，僅高風險操作請求批准',
  'workspace.permission.full.title': '完全存取權限',
  'workspace.permission.full.description': '在目前工作區和已啟用工具範圍內自動執行，不再逐項請求批准',
  'workspace.permission.approveSeekmore': '批准 SEEKMORE 操作',
  'workspace.create.failed': '建立失敗',
  'workspace.create.desktopOnly': '此功能僅支援 SEEKMORE 桌面版',
  'workspace.create.bridgeLoading': '桌面橋接正在載入，請稍後再試',
  'workspace.create.bridgeFailed': '桌面橋接載入失敗，請重新啟動 SEEKMORE',
  'workspace.create.openPickerFailed': '無法開啟資料夾選擇器，請查看桌面執行記錄',
  'workspace.create.nameRequired': '請填寫專案名稱',
  'workspace.create.locationRequired': '請選擇專案建立位置',
  'workspace.create.locationUnset': '尚未選擇建立位置',
  'workspace.create.selecting': '選擇中…',
  'workspace.create.selectLocation': '選擇位置',
  'workspace.create.creating': '建立中…',
  'workspace.create.createAndSelect': '建立並選擇',
  'explore.loading': '載入中…',
  'markdown.code.preview': '預覽',
  'markdown.code.code': '程式碼',
  'markdown.code.showCode': '查看程式碼',
  'markdown.code.previewTitle': 'HTML 預覽',
  'markdown.mermaid.pending': 'Mermaid 將在生成完成後渲染',
  'markdown.mermaid.renderFailed': 'Mermaid 渲染失敗',
  'markdown.textBlock.prompt': '提示詞',
  'markdown.textBlock.text': '文字',
  'embodied.title': '具身體',
  'embodied.description': '人形機器人及具身終端互聯執行｜下一階段實作中',
  'tools.uncategorized': '未分類',
  'tools.requiresConfirmation': '需要確認',
  'tools.enable': '開啟工具 {{name}}',
  'tools.disable': '關閉工具 {{name}}',
  'skills.files.loadFailed': '檔案載入失敗',
  'skills.files.uploading': '正在上傳 {{count}} 個檔案…',
  'skills.files.uploadedOne': '已上傳 {{path}}',
  'skills.files.uploadedMany': '已上傳 {{count}} 個檔案，並保留實際目錄結構。',
  'skills.files.uploadFailed': '上傳失敗',
  'skills.files.deletingOne': '正在刪除檔案…',
  'skills.files.deletingMany': '正在刪除 {{count}} 個檔案…',
  'skills.files.deleteFailed': '刪除失敗',
  'skills.files.confirmDeleteFile': '確認刪除檔案 {{path}}？',
  'skills.files.deletedFile': '已刪除 {{path}}',
  'skills.files.confirmDeleteDirectory': '確認刪除資料夾 {{path}} 及其中 {{count}} 個檔案？',
  'skills.files.deletedDirectory': '已刪除資料夾 {{path}}',
  'skills.files.emptyEditable': '暫無版本檔案。點擊「上傳」新增 references、scripts、assets、license 或其他資源。',
  'skills.files.emptyReadonly': '目前版本暫無其他檔案。',
  'skills.status.deleted': '已刪除',
  'skills.status.blocked': '已阻止',
  'skills.status.quarantined': '已隔離',
  'skills.status.reviewRequired': '待審核',
  'skills.status.ACTIVE': '已啟用',
  'skills.status.DRAFT': '草稿',
  'skills.status.VALIDATING': '驗證中',
  'skills.status.REJECTED': '待修正',
  'skills.status.ARCHIVED': '已封存',
  'skills.status.DISABLED': '已停用',
  'skills.status.STALE': '待更新',
  'skills.action.publish': '發布使用',
  'skills.action.restore': '恢復使用',
  'skills.action.enabled': '已啟用',
  'skills.unknownAuthor': '未知作者',
  'skills.noVersion': '暫無版本',
  'skills.noDescription': '暫無描述',
  'skills.author': '作者：{{name}}',
  'skills.processing': '處理中…',
  'skills.deleting': '刪除中…',
  'skills.permanentDelete': '徹底刪除',
  'memory.empty': '暫無記憶',
  'memory.loadMore': '載入更多',
  'memory.searchPlaceholder': '搜尋記憶內容、主題、來源…',
  'memory.refresh': '重新整理',
  'settings.model.apiKey.saved': '已儲存 ••••{{hint}}',
  'settings.model.apiKey.paste': '貼上 API Key',
  'settings.model.apiKey.get': '取得',
  'settings.model.selectModel': '請選擇模型',
  'settings.model.noModels': '暫無可用模型',
  'settings.model.expandList': '展開模型清單',
  'settings.model.providerListLabel': '{{label}}清單',
  'settings.model.recommended': '推薦',
  'settings.model.roleModel': '{{title}}模型',
  'settings.model.saving': '正在驗證並儲存…',
  'settings.model.save': '儲存設定',
  'settings.model.clear': '清除',
  'sidebar.user.defaultNickname': '使用者暱稱',
  'conversation.more.deleteTitle': '刪除對話',
  'conversation.more.deleteWithAutomations': '此對話還有 {{count}} 個正在執行或暫停的自動任務。刪除對話後這些任務會立即結束；對話進入資源回收筒後可恢復，但自動任務不會自動恢復。',
  'conversation.more.deleteDescription': '刪除後將進入資源回收筒，包含此聊天期間儲存的所有記憶。30 天內可恢復。',
  'conversation.more.deleteAndEnd': '刪除對話並結束任務',
  'conversation.more.remark': '備註',
  'conversation.more.delete': '刪除',
  'conversation.more.report': '檢舉',
  'conversation.more.reportMessage': '檢舉 {{id}}',
  'conversation.more.processing': '處理中…',
  'conversation.more.moreActions': '更多操作',
  'conversation.more.deleteFailed': '刪除失敗，請稍後再試',
  'common.confirm.delete': '刪除',
  'common.confirm.cancel': '取消',
  'common.copy': '複製',
  'common.copied': '已複製',
  'common.copyFailed': '複製失敗',
  'agent.unnamed': '未命名智能體',
  'agent.loadFailed': '取得助手失敗',
  'chat.actions.addAttachment': '新增附件',
  'chat.actions.mcpManageEnabled': 'MCP 總開關已開啟，點擊管理',
  'chat.actions.mcpManageDisabled': 'MCP 總開關已關閉，點擊管理',
  'chat.actions.collapseWorkflow': '收合 Workflow',
  'chat.actions.expandWorkflow': '展開 Workflow',
  'chat.uploadFailed': '上傳失敗',
  'chat.workflow.replyToContinue': '回复上方问题以继续当前 Workflow…',
  'chat.input.addMore': '新增更多內容…',
  'chat.input.sendAnything': '隨心傳送…',
  'chat.message.collapse': '點擊收合',
  'chat.message.expand': '點擊展開',
  'chat.toolbar.branching': '正在建立分支',
  'chat.toolbar.createBranch': '從這裡建立分支',
  'chat.reasoning.thinking': '請讓我思考一下',
  'chat.reasoning.processed': '已处理',
  'webSearch.local': '本地网页搜索',
  'webSearch.status.queued': '排队中',
  'webSearch.status.searching': '搜索中',
  'webSearch.status.waiting': '等待中',
  'webSearch.status.blocked': '已阻止',
  'webSearch.status.completed': '已完成',
  'webSearch.status.failed': '失败',
  'webSearch.status.partial': '部分完成',
  'webSearch.status.cancelled': '已取消',
  'webSearch.status.skipped': '已跳过',
  'chat.sender.you': '你',
  'chat.sender.system': '系統',
  'agent.context.edit': '编辑',
  'agent.context.remark': '备注',
  'agent.context.unpin': '取消置顶',
  'agent.context.pin': '置顶',
  'agent.context.share': '分享',
  'agent.context.report': '举报',
  'agent.context.remove': '移除',
  'chat.defaultGreeting': '今天有什麼可以幫您？',
  'chat.search.placeholder': '搜尋',
  'chat.composer.stop': '停止目前執行',
  'chat.composer.stopPendingConnection': '已記錄停止請求，等待連線後傳送。',
  'chat.composer.stopRequesting': '正在停止本次執行，等待確認。',
  'chat.composer.stopFailed': '停止尚未確認，請同步對話後重試。',
  'chat.composer.send': '傳送訊息',
  'turn.jumpTo': '跳转到第 {{index}} 个回合：{{preview}}',
  'turn.emptyMessage': '空白消息',
  'object.generatedFile': '生成文件',
  'object.validating': '正在驗證',
  'object.uploadProgress': '上传中 {{progress}}%',
  'object.preparingPreview': '正在準備預覽',
  'object.uploadOrProcessFailed': '上傳或處理失敗',
  'object.unsupportedType': '暫不支援此檔案類型',
  'object.ready': '已就緒，可傳送',
  'object.removeAfterProcessed': '处理完成后可移除',
  'object.removeAttachment': '移除附件',
  'object.imageLoadFailed': '圖片無法載入',
  'object.preview.open': '點擊預覽',
  'object.preview.download': '下載檔案',
  'object.preview.expand': '放大預覽',
  'object.preview.restore': '還原預覽',
  'object.preview.close': '關閉預覽',
  'object.preview.loading': '正在載入預覽',
  'object.preview.failed': '預覽載入失敗',
  'object.preview.unavailable': '暫不支援內容預覽，可直接下載檔案',
  'object.preview.empty': '暫無可預覽內容',
  'object.preview.previous': '上一個檔案',
  'object.preview.next': '下一個檔案',
  'object.preview.index': '{{current}} / {{total}}',
  'runtime.executingTask': '正在執行目前任務',
  'assistant.thinking': '正在思考',
  'workflow.status.waiting': '等待',
  'workflow.status.inProgress': '進行中',
  'workflow.status.completed': '完成',
  'workflow.status.blocked': '阻塞',
  'workflow.status.failed': '失败',
  'workflow.status.skipped': '已跳過',
  'workflow.status.cancelled': '已取消',
  'workflow.progress': '任務進度',
  'workflow.blocked': '阻塞',
  'workflow.wait.input': '等待輸入',
  'workflow.wait.approval': '等待授權',
  'workflow.wait.external': '等待外部',
  'workflow.wait.resourceConflict': '資源衝突',
  'workflow.wait.continue': '等待继续',
  'time.loadFailed': '時間資料載入失敗',
  'time.operationFailed': '操作失败',
  'time.notificationConfirmFailed': '通知確認失敗',
  'welcome.heading': '今天想一起做点什么？',
  'welcome.presentation.label': '创作一份演示文档',
  'welcome.presentation.prompt': '帮我创作一份演示文档',
  'welcome.game.label': '创作一个游戏',
  'welcome.game.prompt': '帮我创作一个游戏',
  'welcome.petGif.label': '为桌宠创作一份GIF表情',
  'welcome.petGif.prompt': '帮我为桌宠创作一份 GIF 表情',
  'welcome.blender.label': '创造3D模型',
  'welcome.blender.prompt': '帮我用 Blender 创作一个 3D 模型',
  'welcome.github.label': '管理GitHub',
  'welcome.github.prompt': '帮我处理 GitHub 上的工作',
  'welcome.image.label': '创作一张图片',
  'welcome.image.prompt': '帮我创作一张图片',
  'welcome.music.label': '随心创作一条音乐',
  'welcome.music.prompt': '帮我创作一段音乐',
  'welcome.priceWatch.label': '商品降价与补货提醒',
  'welcome.priceWatch.prompt': '帮我监控电商平台上的商品价格和库存，在商品降价或补货时提醒我',
  'welcome.automation.label': '创建自动化任务，每天帮我做',
  'welcome.automation.prompt': '帮我创建一个持续自动执行的任务，每天帮我做',
  'explore.tabs.overview': '總覽',
  'explore.tabs.agents': '認知體',
  'explore.agent.directory': '認知體目錄',
  'explore.skill.directory': 'SKILL 目錄',
  'markdown.error.defaultTitle': '渲染失败',
  'markdown.error.defaultMessage': '内容无法安全渲染。',
  'markdown.error.unknown': '未知错误',
  'markdown.loading': '内容生成中',
  'myagent.nav.cognitive.title': '認知體',
  'myagent.nav.cognitive.description': '專業領域思考、協作與完成任務',
  'myagent.nav.embodied.title': '具身體',
  'myagent.nav.embodied.description': '裝置與現實世界執行',
  'myagent.nav.skill.title': 'Skill',
  'myagent.nav.skill.description': '可重複使用的程序性知識',
  'myagent.nav.mcp.title': 'MCP',
  'myagent.nav.mcp.description': '外部應用與工具服務',
  'myagent.nav.tool.title': '工具',
  'myagent.nav.tool.description': '系統應用工具',
  'myagent.nav.recycle.title': '資源回收筒',
  'myagent.nav.recycle.description': '按智能體管理已刪除對話',
  'skills.security.SAFE': '安全',
  'skills.security.REVIEW_REQUIRED': '待審查',
  'skills.security.QUARANTINED': '已隔離',
  'skills.security.BLOCKED': '已阻止',
  'skills.files.noUploadable': '没有可上传的文件。根目录 SKILL.md 请在文档编辑区修改。',
  'skills.files.chooseFailed': '文件选择失败',
  'skills.files.desktopChooseFailed': '桌面文件选择失败',
  'skills.files.addToDirectory': '向 {{directory}} 添加文件',
  'skills.files.uploadFileOrFolder': '上传 Skill 文件或文件夹',
  'skills.files.uploadFile': '上传 Skill 文件',
  'skills.files.reading': '读取中…',
  'skills.files.upload': '上传',
  'artifact.status.DRAFT': '草稿',
  'artifact.status.GENERATING': '生成中',
  'artifact.status.RENDERING': '渲染中',
  'artifact.status.COMPLETED': '已完成',
  'artifact.status.FAILED': '失败',
  'artifact.status.ARCHIVED': '已封存',
  'sidebar.nav.chat': '對話',
  'sidebar.nav.myagent': '我的 SEEKMORE',
  'sidebar.nav.explore': '探索 SEEKMORE',
  'sidebar.nav.settings': '設定',
  'memory.loadFailed': '載入記憶失敗',
  'memory.confirm.forgetTitle': '忘記記憶',
  'memory.confirm.forgetDescription': '忘記後不會參與記憶召回，可在已刪除中恢復。',
  'memory.confirm.forget': '忘記',
  'memory.confirm.purgeTitle': '徹底刪除記憶',
  'memory.confirm.purgeDescription': '徹底刪除後無法恢復。',
  'memory.confirm.purge': '徹底刪除',
  'memory.operationFailed': '操作失敗',
  'skills.security.CLEAR': '安全',
  'errors.branchMissingConversationId': '分支建立成功但缺少 conversationId',
  'chat.openConversation': '開啟對話：{{id}}',
  'chat.upload.missingObjectId': '上傳成功但缺少 objectId。',
  'chat.upload.objectNotReady': 'Object 尚未完成處理，不能傳送。',
  'chat.init.missingConversationId': '沒有取得會話 ID。',
  'chat.init.failed': '初始化會話失敗。',
  'chat.title.missingConversationId': '缺少 conversationId。',
  'chat.title.missingSeed': '缺少標題 seed。',
  'chat.title.generateFailed': '標題產生失敗。',
  'chat.title.missingAgentId': '缺少 agentId。',
  'chat.title.createFailed': '標題建立失敗。',
  'chat.title.empty': '標題不能為空。',
  'chat.title.conflict': '標題已被其他操作更新，請重新整理後再試。',
  'chat.title.renameFailed': '重新命名失敗。',
  'chat.conversation.remarkFailed': '備註失敗。',
  'chat.conversation.deleteFailed': '刪除失敗。',
  'chat.branch.unsaved': '目前對話尚未儲存，暫時無法建立分支。',
  'chat.branch.createFailed': '無法建立對話分支，請稍後再試。',
  'chat.turn.blankMessage': '空白訊息',
  'chat.download.failedStatus': '下載失敗：HTTP {{status}}',
  'runtime.workspace.invalidResponse': '後端沒有回傳有效工作區。',
  'runtime.workspace.idRequired': '工作區 ID 不能為空。',
  'runtime.workspace.notFound': '工作區不存在。',
  'runtime.workspace.conversationIdRequired': '會話 ID 不能為空。',
  'cognitive.loadFailed': '載入認知體失敗。',
  'cognitive.deletedLoadFailed': '載入已刪除認知體失敗。',
  'cognitive.knowledge.loadFailed': '知識庫載入失敗。',
  'cognitive.knowledge.uploadFailed': '知識庫檔案上傳失敗。',
  'cognitive.knowledge.deleteFailed': '知識庫檔案刪除失敗。',
  'cognitive.knowledge.reparseFailed': '知識庫重新解析失敗。',
  'myagent.loadFailed': '認知體載入失敗。',
  'skills.validation.failedWithMessage': 'Skill 驗證未通過：{{message}}',
  'skills.validation.failed': 'Skill 驗證未通過。',
  'skills.deleted.restoreFirst': '此 Skill 已刪除，請先還原 Skill。',
  'skills.deleted.bindingBlocked': '已刪除的 Skill 不能新增關聯，請先還原 Skill。',
  'skills.create.templateDescription': '說明這個 Skill 能做什麼，以及應在什麼情況下使用。',
  'skills.create.templateHeading': '使用說明',
  'skills.create.templateBody': '在這裡編寫可重複使用的執行步驟。',
  'skills.request.failed': 'Skill 請求失敗。',
  'skills.import.blocked': 'Skill Package 存在阻斷錯誤，暫時無法匯入。',
  'skills.import.standardRecognized': 'Skill Package 已自動識別，符合 Agent Skills 標準。',
  'skills.import.compatibleRecognized': 'Skill Package 已自動識別，可按相容模式匯入。',
  'skills.import.inspectFailed': 'Skill Package 自動識別失敗。',
  'skills.create.aiGenerated': 'AI 已產生標準 Skill，請檢查右側內容後選擇儲存草稿或直接使用。',
  'skills.activate.failed': 'Skill 未能啟用。',
  'skills.activate.draftSavedButFailed': '草稿已儲存，但直接使用失敗：{{message}}',
  'skills.draft.missingVersionId': 'Skill 草稿已建立，但未回傳可用的草稿版本 ID。',
  'skills.draft.saved': 'Skill 已儲存為草稿。',
  'skills.active.saved': 'Skill 已儲存並可直接使用。',
  'skills.import.notInspected': 'Skill Package 尚未完成自動識別。',
  'skills.import.stillBlocked': '匯入套件仍存在阻斷錯誤。',
  'skills.import.missingVersionId': 'Skill Package 已匯入，但未回傳可用的草稿版本 ID。',
  'skills.import.standardDraftSaved': '標準 Skill Package 已儲存為草稿。',
  'skills.import.compatibleDraftSaved': 'Skill Package 已按相容模式儲存為草稿。',
  'skills.import.standardActivated': '標準 Skill Package 已匯入並可直接使用。',
  'skills.import.compatibleActivated': 'Skill Package 已按相容模式匯入並可直接使用。',
  'skills.actions.creating': '正在建立…',
  'skills.actions.aiCreate': 'AI 建立',
  'skills.actions.saving': '正在儲存…',
  'skills.actions.saveDraft': '儲存草稿',
  'skills.actions.activating': '正在啟用…',
  'skills.actions.retryActivate': '重試直接使用',
  'skills.actions.useDirectly': '直接使用',
  'skills.error.nameConflict': 'Skill 的內部識別碼發生衝突，請重新建立後再試。',
  'skills.error.nameReserved': '對應 Skill 仍處於刪除保留期，請還原原 Skill 或等待徹底刪除後再試。',
  'skills.error.importChanged': 'Skill Package 在識別後發生變更，或識別結果已失效。請等待系統重新識別後再操作。',
  'skills.error.importTokenInvalid': '目前匯入識別憑證無效，請等待系統重新識別 Skill Package。',
  'skills.error.validationRequired': 'Skill 尚未完成有效驗證，暫時不能直接使用。',
  'skills.error.validationFailed': 'Skill 存在阻斷錯誤，暫時不能直接使用。',
  'skills.error.securityReviewRequired': 'Skill 尚未通過安全檢查，暫時不能直接使用。',
  'skills.error.securityRejected': 'Skill 未通過安全檢查，無法直接使用。',
  'skills.error.nameImmutable': 'Skill 的內部識別碼不能修改。介面名稱可以單獨修改。',
  'skills.error.draftVersionNotFound': '沒有找到可驗證或發布的 Skill 草稿版本。',
  'skills.error.versionNotDraft': '目前 Skill 版本已不再是草稿，不能重複發布。',
  'skills.error.versionAlreadyPublished': '目前 Skill 版本已經發布，無需重複啟用。',
  'skills.error.alreadyActive': '目前 Skill 已經處於可用狀態。',
  'skills.error.revisionConflict': 'Skill 已被其他操作更新，請重新整理後再嘗試。',
  'skills.error.displayNameInvalid': 'Skill 名稱不能為空，最多 120 個字元。',
  'skills.error.packageRejected': 'Skill Package 存在阻斷錯誤，無法儲存或直接使用。',
  'skills.error.resourceNotFound': 'Skill 引用的資源檔案不存在。草稿已保留，但目前操作無法完成。',
  'skills.error.notFound': '沒有找到對應的 Skill，它可能已被刪除。',
  'skills.error.permissionDenied': '你沒有權限執行目前 Skill 操作。',
  'skills.error.requestWithCode': 'Skill 請求失敗（{{code}}）。',
  'skills.error.stateConflict': 'Skill 目前狀態或名稱發生衝突。請檢查是否已存在同名草稿或已匯入的 Skill。',
  'skills.error.badRequest': 'Skill 請求內容存在錯誤，請查看驗證診斷後修改。',
  'skills.error.versionMissing': '沒有找到對應的 Skill 或版本。',
  'skills.error.packageTooLarge': 'Skill Package 超過允許的檔案大小限制。',
  'skills.error.metadataDuplicate': 'metadata 鍵重複：{{key}}',
  'skills.files.noneUploadable': '沒有可上傳的檔案。根目錄 SKILL.md 請在文件編輯區修改。',
  'skills.files.selectionFailed': '檔案選擇失敗。',
  'skills.files.desktopSelectionFailed': '桌面檔案選擇失敗。',
  'skills.files.uploadFilesOrFolder': '上傳 Skill 檔案或資料夾',
  'skills.files.uploadFiles': '上傳 Skill 檔案',
  'skills.files.pathRequired': '檔案路徑不能為空。',
  'skills.files.invalidDirectory': '檔案路徑包含無效目錄。',
  'skills.files.duplicatePath': '本次選擇包含重複路徑：{{path}}',
  'skills.loadFailed': 'Skill 載入失敗。',
  'files.upload.partitionRequired': '上傳檔案需要明確的 Agent 與 Conversation 分區。',
  'files.upload.processFailed': '檔案上傳或處理失敗。',
  'files.upload.missingObjectId': '上傳成功但後端未回傳 objectId。',
  'files.upload.objectNotReady': 'Object 尚未完成處理，不能傳送。',
  'files.image.unsupportedFormat': '暫不支援此圖片格式，請使用 PNG、JPEG 或 WebP。',
  'files.image.decodeFailed': '圖片檔案無法解碼或已損壞。',
  'files.type.unsupported': '暫不支援此檔案類型。',
  'http.refresh.missingAccessToken': '重新整理介面未回傳 Access Token。',
  'skills.error.withCode': '{{message}}（{{code}}）',
  'skills.error.httpStatus': '{{message}}（HTTP {{status}}）',
  'errors.AUTH_USER_ID_REQUIRED': '缺少使用者身分。',
  'errors.COGNITIVE_CAPABILITIES_INVALID': 'capabilities 必須是陣列或逗號分隔字串。',
  'errors.COGNITIVE_CAPABILITY_UNSUPPORTED': '不支援的能力：{{capability}}',
  'errors.COGNITIVE_KNOWLEDGE_UPLOAD_BATCH_LIMIT': '知識庫檔案單次最多上傳 {{limit}} 個。',
  'errors.COGNITIVE_KNOWLEDGE_FILE_TOO_LARGE': '檔案 {{fileName}} 超過 {{maxMb}} MB 限制。',
  'errors.COGNITIVE_KNOWLEDGE_FILE_TYPE_UNSUPPORTED': '暫不支援此檔案類型：{{fileName}}（{{mimeType}}）',
  'errors.COGNITIVE_IMAGE_FORMAT_UNSUPPORTED': '頭像/封面僅支援 PNG、JPG、WebP：{{fileName}}',
  'errors.COGNITIVE_IMAGE_TOO_LARGE': '圖片 {{fileName}} 超過 {{maxMb}} MB 限制。',
  'errors.AUTH_SESSION_EXPIRED': '本機工作階段已過期。',
  'errors.CHAT_LEGACY_CREATE_MESSAGE_DISABLED': '舊訊息建立鏈路已停用。',
  'errors.CHAT_LEGACY_CREATE_MESSAGE_WITH_AGENT_DISABLED': '舊智能體訊息建立鏈路已停用。',
  'errors.BRANCH_SOURCE_MESSAGE_NOT_FOUND': '分支起點訊息不存在。',
  'errors.BRANCH_SOURCE_NOT_ASSISTANT': '只能從助手訊息建立分支。',
  'errors.BRANCH_SOURCE_NOT_COMPLETED': '訊息尚未完成，不能建立分支。',
  'errors.BRANCH_MESSAGE_TREE_CYCLE': '訊息樹存在循環，無法建立分支。',
  'errors.BRANCH_CONTEXT_TOO_LONG': '分支上下文過長，無法建立快照。',
  'errors.BRANCH_MESSAGE_CROSS_CONVERSATION': '訊息樹跨越了其他會話。',
  'errors.BRANCH_PARENT_CHAIN_INCOMPLETE': '訊息父鏈不完整，無法建立分支。',
  'errors.CONVERSATION_ARCHIVED_BRANCH_FORBIDDEN': '已封存會話不能建立分支。',
  'errors.BRANCH_CONTEXT_EMPTY': '沒有可複製的對話上下文。',
  'errors.BRANCH_SNAPSHOT_CREATE_FAILED': '分支訊息快照建立失敗。',
  'errors.BRANCH_REQUEST_ID_CONFLICT': 'requestId 已用於其他對話分支請求。',
  'errors.BRANCH_METADATA_INVALID': '分支會話中繼資料不完整。',
  'errors.AGENT_UNAVAILABLE': 'Agent 不存在或已停用。',
  'errors.CONVERSATION_DELETE_DENIED': '無權刪除此會話。',
  'errors.CONVERSATION_DELETED_NOT_FOUND': '已刪除的會話不存在。',
  'errors.CONVERSATION_RETENTION_EXPIRED': '此會話已超過 30 天保留期，無法還原。',
  'errors.CONVERSATION_AGENT_DELETED': '所屬智能體已刪除，請先還原智能體。',
  'errors.CONVERSATION_NOT_IN_RECYCLE_BIN': '請先將會話移入回收站。',
  'errors.MESSAGE_PARENT_CROSS_CONVERSATION': '父訊息不屬於目前會話。',
  'errors.DOCUMENT_BUFFER_INVALID': '檔案 buffer 無效。',
  'errors.DOCUMENT_EMPTY': '檔案內容為空。',
  'errors.DOCUMENT_PARSE_SIZE_LIMIT': '檔案超過 {{maxMb}} MB 解析限制。',
  'errors.DOCUMENT_PARSER_INVALID_RESULT': '解析器回傳無效結果：{{parserKind}}',
  'errors.DOCUMENT_CSV_EMPTY': 'CSV 檔案沒有可解析內容：{{objectName}}',
  'errors.DOCUMENT_CSV_COLUMN_LIMIT': 'CSV 欄數超過 {{limit}} 限制。',
  'errors.DOCUMENT_CSV_FIELD_LIMIT': 'CSV 單欄位超過 {{limit}} 字元限制。',
  'errors.DOCUMENT_CSV_UNCLOSED_QUOTE': 'CSV 包含未閉合的引號欄位。',
  'errors.DOCUMENT_JSON_INVALID': 'JSON 檔案內容無效：{{objectName}}',
  'errors.DOCUMENT_TEXT_INVALID': '檔案不是有效文字：{{objectName}}',
  'errors.OBJECT_ID_REQUIRED': 'objectId 不能為空。',
  'errors.OBJECT_ID_DUPLICATE': 'Duplicate objectId: {{objectId}}',
  'errors.OBJECT_POSITION_DUPLICATE': 'Duplicate Object position: {{position}}',
  'errors.MESSAGE_CONVERSATION_MISMATCH': '訊息不屬於目前會話。',
  'errors.MESSAGE_OBJECT_ROLE_MISMATCH': '訊息角色與 Object 關係角色不匹配。',
  'errors.OBJECT_NOT_READY_OR_INACCESSIBLE': 'Object 未完成解析或不可存取：{{ids}}',
  'errors.OBJECT_NOT_FOUND_OR_INACCESSIBLE': 'Object 不存在或不可存取：{{ids}}',

  'automation.message.expired': '自動任務已結束\n「{{title}}」已到達設定的結束時間，不會再繼續自動執行。',
  'automation.message.blocked': '此自動任務需要使用者操作，已暫停。',
  'automation.message.paused': '自動任務已暫停，本次執行已停止。',
  'automation.message.cancelled': '自動任務已結束，本次執行已停止。',
  'automation.message.failed': '自動任務本次執行失敗。',
  'automation.message.interrupted': '自動任務因應用程式重新啟動而中斷，本次執行已結束。',
  'mcp.configuration.oauth': '需要登入 {{displayName}} 帳號並完成授權。',
  'mcp.configuration.credential': '需要設定 {{displayName}} 存取憑證。',
  'mcp.configuration.localSetup': '需要先完成 {{displayName}} 本機或自託管服務設定。',
  'mcp.configuration.ready': '無需額外設定，安裝後即可連線。',
  'common.avatarAlt': '頭像',
  'chat.reasoning.streaming': '正在生成思考內容',
  'turn.minimap.ariaLabel': '對話回合導覽',
  'explore.banner.ariaLabel': '探索頁橫幅',
  'mcp.definition.urlPlaceholder': 'MCP URL（HTTPS）',
  'mcp.auth.bearerToken': 'Bearer Token',
  'mcp.auth.apiKey': 'API Key',
  'common.apiKey': 'API Key',
  'errors.UNSUPPORTED_UI_LOCALE': '暫不支援該介面語言。',
  'errors.LOCALIZATION_PREFERENCE_CHANGE_REQUIRED': '請選擇需要更新的語言設定。',
  'errors.USER_IDENTITY_REQUIRED': '目前本機工作階段缺少使用者身分，請重試。',
  'errors.SKILL_DISPLAY_NAME_INVALID': 'Skill 名稱最多 120 個字元，且不能包含控制字元。',
  'errors.SKILL_DELETED_CANNOT_BIND': '已刪除的 Skill 不能新增關聯，請先恢復 Skill。',
  'errors.SKILL_DELETED_RESTORE_REQUIRED': '該 Skill 已刪除，請先恢復 Skill。',

  'skills.diagnostic.SKILL_FRONTMATTER_REQUIRED': 'SKILL.md 必須以 YAML frontmatter 開頭。',
  'skills.diagnostic.SKILL_FRONTMATTER_UNCLOSED': 'SKILL.md 的 YAML frontmatter 未正確閉合。',
  'skills.diagnostic.SKILL_FRONTMATTER_YAML_INVALID': 'YAML frontmatter 無效：{{detail}}',
  'skills.diagnostic.SKILL_FRONTMATTER_MAPPING_REQUIRED': 'SKILL.md frontmatter 必須是 YAML 映射。',
  'skills.diagnostic.SKILL_FRONTMATTER_EXTENSION_FIELD': '非標準 frontmatter 欄位 {{field}} 會保留，但標準執行階段投影會忽略它。',
  'skills.diagnostic.SKILL_NAME_REQUIRED': 'name 必須是非空字串。',
  'skills.diagnostic.SKILL_NAME_UNSAFE': 'name 不能包含路徑分隔符、控制字元或路徑越界值。',
  'skills.diagnostic.SKILL_NAME_STORAGE_LIMIT_EXCEEDED': 'name 不能超過 {{maxLength}} 個字元。',
  'skills.diagnostic.SKILL_NAME_NON_STANDARD': 'name 可在相容模式下使用，但 Agent Skills 規範建議僅使用小寫 ASCII 字母、數字和單個連字號。',
  'skills.diagnostic.SKILL_ROOT_NAME_MISMATCH': '套件根目錄名稱 {{rootName}} 與 frontmatter 名稱 {{name}} 不一致，將以 frontmatter 名稱作為 Skill 識別。',
  'skills.diagnostic.SKILL_NAME_IMMUTABLE': '已有 Skill 不能修改 name，請建立新的 Skill。',
  'skills.diagnostic.SKILL_DESCRIPTION_REQUIRED': 'description 必須是非空字串。',
  'skills.diagnostic.SKILL_DESCRIPTION_STORAGE_LIMIT_EXCEEDED': 'description 不能超過 1024 個字元。',
  'skills.diagnostic.SKILL_DESCRIPTION_TOO_LONG': 'description 不能超過 1024 個字元。',
  'skills.diagnostic.SKILL_METADATA_NON_STANDARD': 'metadata 應為映射；原值會保留，但標準執行階段投影會忽略它。',
  'skills.diagnostic.SKILL_METADATA_VALUE_NON_STANDARD': 'metadata.{{key}} 應為字串；原值會保留，但標準執行階段投影會忽略它。',
  'skills.diagnostic.SKILL_METADATA_MAPPING_REQUIRED': 'metadata 必須是字串鍵到字串值的映射。',
  'skills.diagnostic.SKILL_METADATA_VALUE_INVALID': 'metadata 的值必須是字串。',
  'skills.diagnostic.SKILL_ALLOWED_TOOLS_NON_STANDARD': 'allowed-tools 應為以空格分隔的字串；原值會保留，但不會作為執行階段權限依據。',
  'skills.diagnostic.SKILL_ALLOWED_TOOLS_EXPERIMENTAL': 'allowed-tools 仍是實驗欄位，不作為執行階段權限依據。',
  'skills.diagnostic.SKILL_BODY_REQUIRED': 'SKILL.md 必須包含非空的 Markdown 指令正文。',
  'skills.diagnostic.SKILL_MARKDOWN_SIZE_EXCEEDED': 'SKILL.md 超過設定的安全大小限制。',
  'skills.diagnostic.SKILL_MARKDOWN_LINE_COUNT_HIGH': 'SKILL.md 超過 500 行，建議將詳細材料移動到 references/。',
  'skills.diagnostic.SKILL_MARKDOWN_TOKEN_ESTIMATE_HIGH': 'SKILL.md 預計超過 5000 tokens，建議將詳細材料移動到 references/。',
  'skills.diagnostic.SKILL_RESOURCE_PATH_NOT_CANONICAL': 'Skill 資源路徑必須是相對於 Skill 根目錄的規範路徑。',
  'skills.diagnostic.SKILL_RESOURCE_PATH_INVALID': 'Skill 資源路徑無效：{{detail}}',
  'skills.diagnostic.SKILL_RESOURCE_REFERENCE_MISSING': '目前套件中缺少引用的 Skill 資源：{{path}}。Skill 仍可執行，但執行階段讀取該資源可能失敗。',
  'skills.diagnostic.SKILL_RESOURCE_REFERENCE_NON_STANDARD': '資源引用不是安全的 Skill 根目錄相對路徑，執行階段路徑策略會拒絕不安全讀取。',
  'skills.diagnostic.SKILL_DOCUMENT_INVALID': 'SKILL.md 無法安全建立或執行。',
  'skills.diagnostic.SKILL_DOCUMENT_PARSE_FAILED': 'SKILL.md 解析失敗：{{detail}}',
  'skills.diagnostic.SKILL_DISPLAY_NAME_REQUIRED': 'Skill 名稱不能為空。',
  'skills.diagnostic.SKILL_DISPLAY_NAME_INVALID': 'Skill 名稱最多 120 個字元，且不能包含控制字元。',
  'skills.diagnostic.SKILL_GENERATION_INPUT_INVALID': 'Skill 產生輸入驗證失敗。',
  'skills.diagnostic.SKILL_LICENSE_INVALID': 'license 必須是字串。',
  'skills.diagnostic.SKILL_COMPATIBILITY_INVALID': 'compatibility 必須是字串。',
  'skills.diagnostic.SKILL_COMPATIBILITY_TOO_LONG': 'compatibility 超過支援的長度限制。',
  'skills.diagnostic.SKILL_ALLOWEDTOOLS_INVALID': 'allowedTools 必須是字串。',
  'skills.diagnostic.SKILL_FILE_COUNT_EXCEEDED': 'Skill 檔案數量超過設定限制（{{maxFiles}}）。',
  'skills.diagnostic.SKILL_PACKAGE_SIZE_EXCEEDED': 'Skill 套件總大小超過設定限制。',
  'skills.diagnostic.SKILL_DUPLICATE_PATH': 'Skill 套件中存在重複檔案路徑：{{path}}。',
  'skills.diagnostic.SKILL_FILE_SIZE_EXCEEDED': 'Skill 檔案 {{path}} 超過該檔案類型的大小限制。',
  'skills.diagnostic.SKILL_PIPE_REMOTE_SHELL': '偵測到遠端下載後直接交給 Shell 執行。',
  'skills.diagnostic.SKILL_PRIVILEGED_COMMAND': '偵測到高風險系統命令。',
  'skills.diagnostic.SKILL_SECRET_MATERIAL': '偵測到疑似憑據或私鑰材料。',
  'skills.diagnostic.SKILL_BIDI_CONTROL': '偵測到雙向文字控制字元。',
  'skills.diagnostic.SKILL_ZERO_WIDTH': '偵測到零寬字元。',
  'skills.diagnostic.SKILL_HIDDEN_INSTRUCTION': '偵測到 HTML 註解中的隱藏指令。',
  'skills.diagnostic.SKILL_DATA_URL': '偵測到內嵌可執行 data URL。',
  'skills.diagnostic.SKILL_PATH_INVALID': 'Skill 檔案路徑無效。',
  'skills.diagnostic.SKILL_PATH_ABSOLUTE': 'Skill 檔案禁止使用絕對路徑。',
  'skills.diagnostic.SKILL_PATH_TRAVERSAL': 'Skill 檔案路徑禁止越過 Skill 根目錄。',
  'skills.diagnostic.SKILL_PATH_SEGMENT_INVALID': 'Skill 檔案路徑包含無效片段。',
  'skills.diagnostic.SKILL_PATH_HIDDEN_SEGMENT': 'Skill 檔案路徑不能包含隱藏檔案或隱藏目錄。',
  'skills.diagnostic.SKILL_PATH_DEPTH_EXCEEDED': 'Skill 檔案路徑超過最大目錄層級。',
  'skills.diagnostic.SKILL_PATH_TOO_LONG': 'Skill 檔案路徑過長。',
  'skills.diagnostic.SKILL_SKILL_DEPENDENCY_UNAVAILABLE': '必要的 Skill 依賴不可用：{{key}}。',
  'skills.diagnostic.SKILL_TOOL_DEPENDENCY_UNAVAILABLE': '必要的 Tool 依賴不可用：{{key}}。',
  'skills.diagnostic.SKILL_MCP_DEPENDENCY_UNAVAILABLE': '必要的 MCP 依賴不可用：{{key}}。',
  'skills.diagnostic.SKILL_CAPABILITY_UNSUPPORTED': '系統能力目錄中不存在該能力：{{capabilityId}}。',
  'skills.diagnostic.SKILL_CAPABILITY_UNAVAILABLE': '目前沒有可用 Tool 提供該能力：{{capabilityId}}。',
  'skills.diagnostic.SKILL_CAPABILITY_CONFIRMATION_REQUIRED': '能力 {{capabilityId}} 必須要求使用者確認。',
  'skills.diagnostic.SKILL_CAPABILITY_CONCRETE_TOOL': '不能把具體 Tool ID 作為 Skill Capability：{{rawValue}}。{{candidates}}',
  'skills.diagnostic.SKILL_CAPABILITY_AMBIGUOUS': '能力名稱無法唯一匹配：{{rawValue}}。{{candidates}}',
  'skills.diagnostic.SKILL_CAPABILITY_UNRESOLVED': '系統能力目錄中未識別該能力：{{rawValue}}。{{candidates}}',

  'errors.BRANCH_USER_ID_REQUIRED': '建立分支時缺少使用者資訊。',
  'errors.BRANCH_CONVERSATION_ID_REQUIRED': '建立分支時缺少會話資訊。',
  'errors.BRANCH_FROM_MESSAGE_ID_REQUIRED': '建立分支時缺少起點訊息。',
  'errors.BRANCH_REQUEST_ID_REQUIRED': '建立分支時缺少 requestId。',

  'chat.message.turnFailed': '本輪執行失敗，請稍後再試。',

  'common.cover': '封面',
  'common.status.pending': '等待中',
  'common.toggle.on': '開',
  'common.toggle.off': '關',
  'agents.knowledge.chunkCount': '{{count}} 個分塊',
  'skills.create.skillPackage': 'Skill 套件',
  'skills.create.repositoryUrl': '儲存庫 URL',
  'artifact.kind.codeProject': '程式碼專案',
  'artifact.kind.word': 'Word 文件',
  'artifact.kind.excel': 'Excel 試算表',

  'errors.AUTHENTICATED_USER_REQUIRED': '需要本機使用者工作階段。',
  'errors.RENDER_REQUEST_OBJECT_REQUIRED': '渲染請求必須是物件。',
  'errors.RENDER_TOOL_NAME_REQUIRED': '渲染請求缺少 toolName。',
  'errors.RENDER_PAYLOAD_OBJECT_REQUIRED': '渲染 payload 必須是物件。',
  'errors.RENDER_PAYLOAD_ARRAY_FORBIDDEN': '渲染 payload 不能是陣列。',
  'errors.RENDER_FILENAME_STRING_REQUIRED': '渲染檔名必須是字串。',
  'errors.RENDER_TITLE_STRING_REQUIRED': '渲染標題必須是字串。',
  'errors.RENDER_META_OBJECT_REQUIRED': '渲染中繼資料必須是物件。',
  'errors.RENDER_BINARY_BUFFER_REQUIRED': '渲染交付需要非空二進位資料。',
  'errors.RENDER_PLANNING_ARGS_OBJECT_REQUIRED': '渲染規劃參數必須是物件。',
  'errors.RENDER_INSTRUCTION_OR_PLAN_REQUIRED': '渲染需要 instruction 或 plan。',
  'errors.RENDER_SOURCE_OBJECT_REQUIRED': '渲染 source 必須是物件。',
  'errors.RENDER_REQUIREMENTS_OBJECT_REQUIRED': '渲染 requirements 必須是物件。',
  'errors.RENDER_OUTPUT_FIELD_UNSUPPORTED': '渲染輸出固定進入物件目錄，不支援 output 欄位。',
  'errors.ZIP_ARGS_OBJECT_REQUIRED': 'ZIP 參數必須是物件。',
  'errors.ZIP_FILES_REQUIRED': 'ZIP 渲染需要檔案。',
  'errors.DOCX_PAYLOAD_OBJECT_REQUIRED': 'DOCX payload 必須是物件。',
  'errors.DOCX_PAYLOAD_EMPTY': 'DOCX payload 為空。',
  'errors.DOCX_BLOCK_TYPE_REQUIRED': 'DOCX block.type 為必填項。',
  'errors.DOCX_IMAGE_BASE64_REQUIRED': 'DOCX 圖片區塊缺少 base64 內容。',
  'errors.DOCX_TABLE_ROWS_ARRAY_REQUIRED': 'DOCX 表格 rows 必須是陣列。',
  'errors.RUNTIME_WORKSPACE_PERSISTENCE_UNAVAILABLE': '執行時工作區持久化不可用。',
  'errors.WORKSPACE_NOT_FOUND': '工作區不存在。',
  'errors.WORKSPACE_UPDATE_INVALID': '工作區更新產生了無效狀態。',
  'errors.WORKSPACE_DEFAULT_UPDATE_INVALID': '預設工作區更新產生了無效狀態。',
  'errors.WORKSPACE_PERSISTENCE_UNAVAILABLE': '工作區持久化不可用。',
  'errors.AGENT_PROFILE_IMAGE_KIND_INVALID': '資料圖片類型無效。',
  'errors.AGENT_PROFILE_IMAGE_NOT_FOUND': '資料圖片不存在。',
  'errors.PUBLIC_AGENT_NOT_FOUND': '智能體不存在或未公開。',
  'errors.PUBLIC_FREE_AGENT_NOT_FOUND': '公開免費智能體不存在。',
  'errors.PUBLIC_PAID_AGENT_NOT_FOUND': '公開付費智能體不存在。',
  'errors.AGENT_RELATION_NOT_FOUND': '智能體關係不存在。',
  'errors.MCP_AUTHENTICATED_PRINCIPAL_REQUIRED': '需要已驗證的 MCP 主體。',
  'errors.MCP_AGENT_ACCESS_DENIED': '目前使用者無權存取此智能體。',
  'errors.CONVERSATION_ID_REQUIRED': '缺少 conversationId，請先建立對話。',

  'errors.TOOL_NOT_FOUND': '工具 {{toolName}} 不存在。',
  'errors.DOCUMENT_TYPE_UNSUPPORTED': '不支援的文件類型：{{objectName}}（{{mimeType}}）。',
  'errors.RENDER_TOOL_CANNOT_HANDLE_REQUEST': '渲染工具 {{toolName}} 無法處理此請求。',
  'errors.RENDER_TOOL_NOT_FOUND': '渲染工具 {{toolName}} 不存在。',
  'errors.RENDER_TOOL_DISABLED': '渲染工具 {{toolName}} 已停用。',
  'errors.DOCX_TEXT_LIMIT_EXCEEDED': 'DOCX 文字超過 {{limit}} 字元限制。',
  'errors.DOCX_BLOCK_LIMIT_EXCEEDED': 'DOCX 內容區塊超過 {{limit}} 個限制。',
  'errors.DOCX_TABLE_ROW_LIMIT_EXCEEDED': 'DOCX 表格列數超過 {{limit}} 列限制。',
  'errors.DOCX_TABLE_COLUMN_LIMIT_EXCEEDED': 'DOCX 表格欄數超過 {{limit}} 欄限制。',

  'errors.SKILL_NOT_BINDABLE': 'Skill {{skillId}} 目前狀態不可綁定。',
  'errors.ENABLED_SKILL_MUST_BE_ACTIVE_AND_CLEAR': '啟用的 Skill {{skillId}} 必須處於可用狀態並通過安全檢查。',
  'errors.PINNED_VERSION_REQUIRED': 'Skill {{skillId}} 需要指定固定版本。',
  'errors.PINNED_VERSION_INVALID': 'Skill {{skillId}} 的固定版本無效。',
  'errors.ENABLED_SESSION_SKILL_MUST_BE_ACTIVE_AND_CLEAR': '對話中啟用的 Skill {{skillId}} 必須處於可用狀態並通過安全檢查。',
  'errors.SESSION_SKILL_VERSION_INVALID': 'Skill {{skillId}} 選擇的對話版本無效。',
  'errors.SKILL_GENERATION_PAUSED': 'Skill 生成已暫停：{{reason}}。',
  'errors.SKILL_IMPORT_ZIP_INVALID': 'Skill ZIP 套件無效：{{reason}}。',
  'errors.OBJECT_REFERENCE_DUPLICATE': '物件 {{objectId}} 被重複引用。',
  'errors.OBJECT_POSITION_INVALID': '物件 {{objectId}} 的位置無效。',
  'errors.MCP_IMPORT_TRANSPORT_AMBIGUOUS': 'MCP 服務 {{server}} 同時指定了多種傳輸方式。',
  'errors.MCP_IMPORT_TRANSPORT_REQUIRED': 'MCP 服務 {{server}} 缺少傳輸設定。',
  'errors.MCP_IMPORT_ARGS_INVALID': 'MCP 服務 {{server}} 包含無效命令參數。',
  'errors.MCP_IMPORT_COMMAND_INVALID': 'MCP 服務 {{server}} 包含無效命令。',
  'errors.OBJECT_TOO_LARGE': '物件過大（{{sizeBytes}} 位元組；最大 {{maxBytes}} 位元組）。',
};
