export const zhHans = {
  'app.rendererFailed': '页面渲染失败',
  'app.rendererLogHint': '请打开开发者工具查看 Renderer 日志',
  'app.startupFailed': 'SEEKMORE 本地会话启动失败',
  'app.desktopBridgeFailed': '桌面桥接加载失败，请重新启动 SEEKMORE',

  'settings.general': '通用',
  'settings.model': '模型设置',
  'settings.data': '数据管理',
  'settings.help': '反馈与帮助',
  'settings.moreComing': '敬请期待更多设置选项...',
  'settings.appearance': '外观',
  'settings.appearance.light': '明亮',
  'settings.appearance.dark': '暗色',
  'settings.language': '语言',
  'settings.languageDescription': '设置 SEEKMORE 的界面语言；“跟随系统”使用当前设备语言。',
  'settings.followSystem': '跟随系统',
  'settings.simplifiedChinese': '简体中文',
  'settings.traditionalChinese': '繁體中文',
  'settings.english': 'English',
  'common.cancel': '取消',
  'common.notAvailable': '暂无',

  'chat.newConversation': '新对话',
  'chat.toggleSidebar': '切换侧边栏',
  'chat.openTimeRecords': '打开时间记录',
  'chat.latestConversation': '已是最新对话',
  'chat.titleGenerating': '标题生成中',
  'chat.expand': '展开',

  'runtime.currentTask': '正在执行当前任务',
  'runtime.tool.queued': '{{tool}}等待执行',
  'runtime.tool.running': '{{tool}}正在执行',
  'runtime.tool.succeeded': '{{tool}}已完成',
  'runtime.tool.failed': '{{tool}}执行失败',
  'runtime.clarification.waiting': '等待用户补充信息',
  'runtime.clarification.title': '需要补充信息',
  'runtime.step.analysisFirst': '分析任务并制定执行路径',
  'runtime.step.analysisNext': '分析第 {{round}} 轮执行结果',
  'runtime.step.turnStart': '启动智能体执行',
  'runtime.step.verification': '验证执行结果',
  'runtime.step.completed': '执行完成',
  'runtime.step.waiting': '等待继续条件',
  'runtime.step.failed': '执行失败：{{message}}',
  'runtime.result.failed': '工具执行失败',
  'runtime.result.completed': '工具执行完成',
  'runtime.result.confirmation': '等待用户确认',

  'runtime.status.queued': '排队中',
  'runtime.status.running': '执行中',
  'runtime.status.waiting': '等待中',
  'runtime.status.blocked': '已阻止',
  'runtime.status.succeeded': '已完成',
  'runtime.status.failed': '失败',
  'runtime.status.partial': '部分完成',
  'runtime.status.cancelled': '已取消',
  'runtime.status.skipped': '已跳过',
  'runtime.detail.input': '输入',
  'runtime.detail.output': '输出',
  'runtime.detail.error': '错误',
  'runtime.detail.evidence': '证据',
  'runtime.clarification.inputNeeded': '需要你的输入',

  'time.title': '时间',
  'time.description': '提醒、事项、闹钟与计时',
  'time.refresh': '刷新',
  'time.refreshing': '刷新中',
  'time.section.due': '进行事项',
  'time.section.records': '记录事项',
  'time.empty.due': '暂无到时事项',
  'time.empty.records': '暂无时间记录',
  'time.defaultReminderTitle': '时间提醒',
  'time.reminderDue': '提醒已到时间',
  'time.kind.alarm': '闹钟',
  'time.kind.reminder': '提醒',
  'time.kind.event': '事项',
  'time.kind.countdown': '倒计时',
  'time.kind.stopwatch': '计时',
  'time.status.triggered': '已到时',
  'time.status.paused': '已暂停',
  'time.status.running': '运行中',
  'time.status.scheduled': '已安排',
  'time.action.processing': '处理中',
  'time.action.snooze5': '稍后 5 分钟',
  'time.action.snooze5Full': '稍后 5 分钟提醒我',
  'time.action.complete': '完成',
  'time.action.resume': '继续',
  'time.action.stop': '结束',
  'time.action.pause': '暂停',
  'time.action.cancel': '取消',

  'skills.source.BUILTIN': '官方',
  'skills.source.REPOSITORY': 'GitHub 导入',
  'skills.source.UPLOAD': '本地导入',
  'skills.source.INLINE': '本地创建',
  'skills.source.IMPORTED': '本地导入',
  'skills.source.AI_GENERATED': 'AI 创建',
  'skills.source.UNKNOWN': '未知来源',
  'skills.activation.MANUAL': '仅手动使用',
  'skills.activation.AUTOMATIC': '自动使用',
  'skills.activation.ALWAYS': '始终使用',
  'skills.activation.DISABLED': '已停用',
  'skills.version.DRAFT': '草稿',
  'skills.version.VALIDATING': '校验中',
  'skills.version.PUBLISHED': '可用版本',
  'skills.version.REJECTED': '未通过',
  'skills.version.SUPERSEDED': '历史版本',
  'skills.agentActivation.INHERIT': '跟随认知体设置',
  'skills.agentActivation.MANUAL': '仅手动使用',
  'skills.agentActivation.AUTOMATIC': '自动使用',
  'skills.agentActivation.ALWAYS': '始终使用',
  'skills.agentActivationDescription.INHERIT': '按照认知体的默认 Skill 使用方式运行',
  'skills.agentActivationDescription.MANUAL': '只有用户明确选择时才使用',
  'skills.agentActivationDescription.AUTOMATIC': '任务相关时由认知体自动使用',
  'skills.agentActivationDescription.ALWAYS': '认知体执行任何任务时都会加载',
  'skills.agentActivation.current': '当前为{{mode}}',
  'skills.binding.summary': '已关联 Skill 会按照启用状态和优先顺序排列。',
  'skills.binding.count': '{{count}} 项',
  'skills.binding.fallbackName': '已关联 Skill',
  'skills.binding.deleted': '已删除',
  'skills.binding.unavailable': 'Skill 信息暂不可用',
  'skills.binding.unlink': '取消关联',
  'skills.binding.usageMode': '使用方式',
  'skills.binding.deletedPreserved': '关联和原设置已保留，恢复后自动继续使用',
  'skills.binding.priority': '优先顺序',
  'skills.binding.priorityHint': '1 最先，数字越小越靠前。',
  'skills.binding.restoreFirst': '该 Skill 已删除，请先恢复 Skill。',
  'skills.binding.enabledDeleted': '已启用（删除期间暂停）',
  'skills.binding.pausedDeleted': '已暂停（Skill 已删除）',
  'skills.binding.enabled': '已启用',
  'skills.binding.paused': '已暂停',

  'skills.settings.title': 'Skill 使用设置',
  'skills.settings.defaultMode': '认知体默认使用方式',
  'skills.settings.defaultHint': '设为“跟随认知体设置”的 Skill 会使用这里的默认方式。',
  'skills.settings.linked': '关联 Skill',
  'skills.settings.add': '添加 Skill',
  'skills.version.none': '暂无版本',
  'skills.loadingBindings': '正在加载关联 Skill…',
  'agents.type.cognitive': '认知体',
  'agents.knowledge.status.READY': '已就绪',
  'agents.knowledge.status.PARSING': '解析中',
  'agents.knowledge.status.FAILED': '失败',
  'agents.knowledge.status.PENDING': '等待解析',

  'recycle.unnamedConversation': '未命名对话',
  'recycle.messageCount': '{{count}} 条消息',
  'recycle.deletedAt': '删除于 {{date}}',
  'recycle.purgeAt': '永久删除：{{date}}',
  'recycle.waitingCleanup': '等待清理',
  'recycle.remainingDays': '剩余 {{count}} 天',
  'recycle.purgeSoon': '即将永久删除',
  'recycle.collapse': '收起内容',
  'recycle.view': '查看内容',
  'recycle.restoring': '恢复中…',
  'recycle.restore': '恢复',
  'recycle.deleting': '删除中…',
  'recycle.deletePermanently': '永久删除',
  'recycle.loadingMessages': '正在加载消息…',
  'recycle.noMessages': '暂无可展示消息。',
  'recycle.emptyMessage': '（空消息）',
  'recycle.download': '下载',
  'common.role.USER': '用户',
  'common.role.ASSISTANT': '助手',
  'common.role.SYSTEM': '系统',
  'common.role.TOOL': '工具',

  'agents.recycle.deleted': '已删除',
  'agents.recycle.noDescription': '暂无描述',
  'agents.recycle.conversationCount': '{{count}} 个对话',
  'agents.recycle.messageCount': '{{count}} 条消息',
  'agents.recycle.restore': '恢复使用',
  'agents.recycle.restoring': '恢复中…',
  'agents.recycle.delete': '彻底删除',
  'agents.recycle.deleting': '删除中…',
  'agents.recycle.coverAlt': '{{name}} 封面',
  'agents.recycle.avatarAlt': '{{name}} 头像',

  'memory.status.active': '已生效',
  'memory.status.pending_confirmation': '候选',
  'memory.status.superseded': '已替换',
  'memory.status.deleted': '已删除',
  'memory.status.conflicted': '冲突',
  'memory.kind.identity': '身份',
  'memory.kind.preference': '偏好',
  'memory.kind.constraint': '约束',
  'memory.kind.project_state': '项目状态',
  'memory.kind.goal': '目标',
  'memory.kind.relationship': '关系',
  'memory.kind.workflow': '流程',
  'memory.kind.tool_preference': '工具偏好',
  'memory.kind.event': '事件',
  'memory.kind.episode': '片段',
  'memory.scope.user': '用户',
  'memory.scope.agent': '智能体',
  'memory.scope.conversation': '对话',
  'memory.source.user': '全局记忆',
  'memory.source.agent': '智能体 {{id}}',
  'memory.source.conversation': '对话 {{id}}',
  'memory.sensitivity.normal': '普通',
  'memory.sensitivity.private': '私有',
  'memory.sensitivity.sensitive': '敏感',
  'memory.sensitivity.restricted': '受限',
  'memory.updatedAt': '更新 {{date}}',
  'memory.usageCount': '使用 {{count}}',
  'memory.action.promote': '晋升',
  'memory.action.restore': '恢复',
  'memory.action.purge': '清除',
  'memory.action.delete': '删除',

  'skills.picker.deleted': '已删除',
  'skills.picker.deletedLinkedHint': '关联和原设置已保留，恢复后自动继续使用',
  'skills.picker.deletedUnlinkedHint': '该 Skill 已删除，恢复后才能关联',
  'skills.picker.createdAt': '创建于 {{date}}',
  'skills.picker.unlink': '取消关联',
  'skills.picker.deletedCannotLink': '已删除的 Skill 不能新增关联',
  'skills.picker.linkTitle': '关联 Skill',
  'skills.picker.link': '关联',

  'tools.file.search.name': '搜索文件',
  'tools.file.read.name': '读取文件',
  'tools.file.write.name': '写入文件',
  'tools.file.patch.name': '修改文件',
  'tools.file.delete.name': '删除文件',
  'tools.terminal.run.name': '运行终端命令',
  'tools.python.execute.name': '运行 Python',
  'tools.knowledge.search.name': '搜索知识库',
  'tools.web.search.name': '联网搜索',

  'tools.skill_search.name': '搜索 Skill',
  'tools.skill_view.name': '加载 Skill',
  'tools.skill_read_resource.name': '读取 Skill 资源',
  'tools.time.name': '时间',
  'tools.automation.name': '自动任务',
  'tools.image.generate.name': '生成图片',
  'tools.speech.synthesize.name': '生成语音',
  'tools.voice.clone.name': '克隆声音',
  'tools.music.generate.name': '生成音乐',
  'tools.video.general.name': '生成视频',
  'tools.video.generate.name': '生成视频',
  'tools.location.name': '位置',
  'tools.vision.analyze.name': '分析图片',
  'tools.web.read.name': '网页读取',
  'tools.repository.inspect.name': '检查代码仓库',
  'tools.repository.list_tree.name': '读取仓库目录',
  'tools.repository.read_file.name': '读取仓库文件',
  'tools.workspace.inspect.name': '检查工作区',
  'tools.terminal.read.name': '读取终端会话',
  'tools.terminal.kill.name': '终止终端会话',
  'tools.git.status.name': '检查 Git 状态',
  'tools.git.diff.name': '查看 Git 差异',
  'tools.document.parse.name': '解析文档',
  'tools.object.search.name': '搜索上传文件',
  'tools.object.inspect.name': '检查上传文件',
  'tools.code_project.inspect.name': '检查代码项目',
  'tools.document.render.docx.name': '生成 DOCX',
  'tools.document.render.pdf.name': '生成 PDF',
  'tools.spreadsheet.render.xlsx.name': '生成 XLSX',
  'tools.presentation.create.name': '创建演示文稿',
  'tools.presentation.slides.upsert.name': '创建或更新幻灯片',
  'tools.presentation.inspect.name': '检查演示文稿',
  'tools.presentation.finalize.name': '完成演示文稿',
  'tools.presentation.render.pptx.name': '生成 PPTX',
  'tools.package.render.zip.name': '生成 ZIP',
  'tools.plugins.mcp_manage.name': '管理 MCP',
                                        

  'agents.system.seekmore-system-agent.description': '轻松工作 轻松生活',

  'explore.action.added': '已加入',
  'explore.action.authorize': '授权',
  'explore.action.add': '加入',
  'explore.action.installed': '已安装',
  'explore.action.install': '安装',
  'explore.action.connected': '已接入',
  'explore.action.connecting': '连接中',
  'explore.action.reconnect': '重新连接',
  'explore.action.configure': '配置',
  'explore.action.reconfigure': '重新配置',
  'explore.action.setup': '设置',
  'explore.action.disabled': '已停用',
  'explore.action.connect': '连接',
  'explore.type.agent': '认知体',
  'explore.type.skill': 'SKILL',
  'explore.coverAlt': '{{name}} 封面',
  'explore.avatarAlt': '{{name}} 头像',
  'explore.noProductIntroduction': '暂无产品介绍',
  'explore.noMcpDescription': '暂无 MCP 能力说明',
  'common.noDescription': '暂无描述',

  'agents.loading': '正在加载智能体…',
  'agents.empty': '暂无智能体。',
  'agents.goChat': '前往聊天',
  'agents.processing': '处理中…',
  'agents.systemDefault': '系统默认',
  'agents.coverAlt': '{{name}} 封面',
  'agents.avatarAlt': '{{name}} 头像',
  'common.back': '返回',

  'mcp.status.disabled': '已停用',
  'mcp.status.authorizationRequired': '待授权',
  'mcp.status.setupRequired': '待设置',
  'mcp.status.configurationRequired': '待配置',
  'mcp.status.connected': '已接入',
  'mcp.status.connecting': '连接中',
  'mcp.status.failed': '连接失败',
  'mcp.status.disconnected': '未连接',
  'mcp.action.waitingAuthorization': '等待授权…',
  'mcp.action.authorize': '授权',
  'mcp.action.setup': '设置',
  'mcp.action.reconfigure': '重新配置',
  'mcp.action.configure': '配置',
  'mcp.action.connecting': '连接中…',
  'mcp.action.reconnect': '重新连接',
  'mcp.action.connect': '连接',
  'mcp.action.reauthorize': '重新授权',
  'mcp.action.refreshing': '刷新中',
  'mcp.action.refresh': '刷新',
  'mcp.action.revoke': '解绑',
  'mcp.action.uninstall': '卸载',
  'mcp.action.disable': '停用',
  'mcp.action.enable': '启用',
  'approval.timeline.waiting.title': '需要确认执行',
  'approval.timeline.waiting.summary': '工具 {{tool}} 将执行受控操作',
  'approval.timeline.resolved.approved': '已确认执行',
  'approval.timeline.resolved.cancelled': '已取消执行',
  'approval.timeline.resolved.workspaceChanged': '工作区已切换，旧工作区中尚未执行的操作已取消',
  'approval.timeline.resolved.policyChanged': '审批模式已更新，当前操作已按新策略处理',
  'approval.card.title': '需要批准',
  'approval.action.allowOnce': '允许一次',
  'approval.action.auditOnly': '替我审批',
  'approval.action.fullAccessTask': '本任务完全访问',
  'approval.action.reject': '拒绝',
  'approval.checkpointCreating': '正在建立可恢复审批检查点…',
  'errors.requestFailed': '请求失败，请稍后重试。',
  'errors.UNAUTHORIZED': '本地会话不可用，请重试。',
  'errors.AUTHORIZATION_HEADER_INVALID': '缺少或非法的授权头。',
  'errors.ACCESS_TOKEN_REQUIRED': '缺少访问令牌。',
  'errors.ACCESS_TOKEN_INVALID': '访问令牌无效或已过期。',
  'errors.WORKSPACE_PARENT_UNAVAILABLE': '选择的父目录不存在或无法访问。',
  'errors.WORKSPACE_PARENT_OUTSIDE_ROOT': '父目录不在允许的 workspace 根目录范围内。',
  'errors.WORKSPACE_PROJECT_EXISTS': '项目目录已存在。',
  'errors.WORKSPACE_CREATE_FAILED': '项目目录创建失败。',
  'errors.WORKSPACE_UNREADABLE': '项目目录创建后无法读取。',
  'errors.WORKSPACE_UNAVAILABLE': '选择的工作区目录不存在或无法访问。',
  'errors.WORKSPACE_ROOT_FORBIDDEN': '不能将文件系统根目录注册为工作区。',
  'errors.WORKSPACE_SENSITIVE_PATH_FORBIDDEN': '不能将系统敏感目录注册为工作区。',
  'errors.WORKSPACE_PROJECT_NAME_INVALID': '项目名称无效。',
  'errors.WORKSPACE_PATH_INVALID': '项目路径无效。',
  'errors.AGENT_NOT_FOUND': '助手不存在。',
  'errors.AGENT_ACCESS_DENIED': '你无权访问该助手。',
  'errors.SYSTEM_AGENT_REMOVE_FORBIDDEN': 'SEEKMORE 系统助手不可移除。',
  'errors.SYSTEM_AGENT_DELETE_FORBIDDEN': 'SEEKMORE 系统助手不可删除。',
  'errors.COGNITIVE_AGENT_NOT_FOUND': '认知体不存在。',
  'errors.COGNITIVE_AGENT_ACCESS_DENIED': '无权访问该认知体。',
  'errors.COGNITIVE_AGENT_OWNER_REQUIRED': '只有所有者可以操作该认知体。',
  'errors.COGNITIVE_AGENT_SYSTEM_MANAGED': 'SEEKMORE 系统助手由系统管理，不可修改。',
  'errors.KNOWLEDGE_FILE_NOT_FOUND': '知识库文件不存在。',
  'errors.KNOWLEDGE_FILE_EMPTY': '知识库文件未解析出可检索内容。',
  'errors.CONVERSATION_NOT_FOUND': '会话不存在。',
  'errors.CONVERSATION_ACCESS_DENIED': '你无权访问此会话。',
  'errors.MESSAGE_NOT_FOUND': '消息不存在。',
  'agents.capability.chat.name': '基础对话',
  'agents.capability.chat.description': '允许 Agent 进行基础对话与问答。',
  'agents.capability.file_reading.name': '读取文件',
  'agents.capability.file_reading.description': '允许 Agent 读取用户上传的知识库与文件内容。',
  'agents.capability.file_render.name': '文件生成',
  'agents.capability.file_render.description': '允许 Agent 使用内部文件渲染能力生成交付文件。',
  'agents.capability.docx_generation.name': 'Word 生成',
  'agents.capability.docx_generation.description': '允许 Agent 生成 Word 文档。',
  'agents.capability.xlsx_generation.name': 'Excel 生成',
  'agents.capability.xlsx_generation.description': '允许 Agent 生成 Excel 表格。',
  'agents.capability.web_search.name': '联网搜索',
  'agents.capability.web_search.description': '允许 Agent 在需要最新信息、官网信息或资料来源时调用外部搜索工具。',
  'agents.capability.image_generation.name': '图片生成',
  'agents.capability.image_generation.description': '允许 Agent 调用外部图片生成工具。',
  'agents.validation.NAME_TOO_SHORT': '名称过短。',
  'agents.validation.DESCRIPTION_WEAK': '描述过短，建议说明适用场景和核心能力。',
  'agents.validation.ROLE_PROMPT_WEAK': '角色设定过短，无法形成稳定认知体行为。',
  'agents.validation.NO_CAPABILITIES': '至少需要配置一个能力。',
  'agents.validation.KNOWLEDGE_PARSE_FAILED': '存在 {{count}} 个知识库文件解析失败。',
  'agents.validation.KNOWLEDGE_PARSE_PENDING': '存在 {{count}} 个知识库文件等待解析。',
  'errors.KNOWLEDGE_FILE_SELECTION_REQUIRED': '请选择要上传的知识库文件。',
  'errors.COGNITIVE_AGENT_DELETED_NOT_FOUND': '已删除的认知体不存在。',
  'errors.COGNITIVE_AGENT_RETENTION_EXPIRED': '该认知体已超过 30 天保留期，无法恢复。',
  'errors.COGNITIVE_AGENT_OWNER_RELATION_MISSING': '认知体所有权关系不存在，无法恢复。',
  'errors.AGENT_PROFILE_FILE_EMPTY': '{{field}} 文件内容为空。',
  'errors.AGENT_PROFILE_FILE_WRITE_FAILED': '{{field}} 写入失败。',
  'errors.KNOWLEDGE_FILE_CONTENT_EMPTY': '知识库文件内容为空：{{fileName}}。',
  'errors.KNOWLEDGE_FILE_WRITE_FAILED': '知识库文件写入失败：{{fileName}}。',
  'errors.operationFailed': '操作失败。',
  'errors.explore.loadFailed': 'Explore 加载失败。',
  'errors.mcp.operationFailed': 'MCP 操作失败。',
  'errors.mcp.statusLoadFailed': 'MCP 状态加载失败。',
  'errors.mcp.globalToggleFailed': 'MCP 总开关更新失败。',
  'errors.mcp.toggleFailed': 'MCP 开关更新失败。',
  'errors.mcp.loadFailed': 'MCP 加载失败。',
  'errors.mcp.refreshFailed': 'MCP 状态刷新失败。',
  'errors.mcp.connectStartFailed': '连接启动失败。',
  'errors.mcp.oauthFailed': 'MCP OAuth 授权失败。',
  'errors.mcp.directoryLoadFailed': 'MCP 目录加载失败。',
  'errors.MCP_CONFIGURATION_REQUIRED': '请先完成 MCP 连接配置。',
  'errors.MCP_GLOBALLY_DISABLED': 'MCP 总开关已关闭，请先开启总开关。',
  'errors.MCP_INSTALLATION_DISABLED': '该 MCP 已关闭，请先开启后再连接。',
  'errors.MCP_CREDENTIAL_NOT_REQUIRED': '该 MCP 不需要配置访问凭据。',
  'errors.MCP_CREDENTIAL_VALUES_INVALID': '连接配置不完整或格式不正确。',
  'errors.MCP_CREDENTIAL_KEY_NOT_DECLARED': '配置项与该 MCP 声明的字段不一致。',
  'errors.MCP_CREDENTIAL_DECLARATION_INCOMPLETE': '请填写全部必需的连接配置。',
  'errors.MCP_BEARER_TOKEN_REQUIRED': '请填写访问令牌。',
  'errors.MCP_API_KEY_REQUIRED': '请填写 API Key。',
  'errors.MCP_HEADER_VALUE_INVALID': '请求头配置格式不正确。',
  'errors.MCP_AUTHORIZATION_REQUIRED': '请先登录并授权该 MCP 服务。',
  'errors.MCP_OAUTH_AUTHORIZATION_REQUIRED': '请先登录并授权该 MCP 服务。',
  'errors.MCP_LOCAL_SETUP_REQUIRED': '请先完成本地或自托管服务设置。',
  'errors.MCP_CREDENTIAL_INVALID': '当前凭据无效，请重新配置。',
  'errors.MCP_CONNECTION_FAILED': 'MCP 连接失败，请检查服务地址和访问凭据。',
  'errors.MCP_DESKTOP_BRIDGE_UNAVAILABLE': '桌面连接服务不可用，请确认正在 SEEKMORE 桌面端中操作。',
  'common.actions.collapse': '收起',
  'common.actions.expandAll': '展开全部',
  'common.actions.edit': '编辑',
  'common.actions.pause': '暂停',
  'common.actions.resume': '继续',
  'common.actions.save': '保存',
  'automation.errors.actionFailed': '自动任务操作失败，请稍后重试',
  'automation.errors.required': '任务名称和执行内容不能为空',
  'automation.errors.invalidRunAt': '请选择有效的执行时间',
  'automation.cancel.confirmTitle': '结束“{{title}}”？',
  'automation.cancel.confirmDescription': '结束后将不再自动执行此任务，历史消息仍会保留。',
  'automation.actions.end': '结束任务',
  'automation.fields.frequency': '执行频率',
  'automation.fields.delivery': '汇报方式',
  'automation.fields.endAt': '结束时间',
  'automation.fields.maxRuns': '最多执行',
  'automation.fields.completionCondition': '结束条件',
  'automation.fields.validity': '有效期',
  'automation.fields.nextRun': '下次执行',
  'automation.fields.remaining': '剩余',
  'automation.fields.completedAt': '完成时间',
  'automation.fields.title': '任务名称',
  'automation.fields.instruction': '执行内容',
  'automation.fields.every': '每隔',
  'automation.fields.unit': '单位',
  'automation.fields.maxRunsInput': '最多执行次数',
  'automation.fields.runAt': '执行时间',
  'automation.fields.nextStartOptional': '下次起始时间（可选）',
  'automation.delivery.always': '每次执行后汇报',
  'automation.delivery.onCompletion': '满足结束条件时汇报',
  'automation.validity.indefinite': '直到手动结束',
  'automation.validity.indefiniteLong': '长期运行，直到我手动结束',
  'automation.status.ACTIVE': '运行中',
  'automation.status.PAUSED': '已暂停',
  'automation.status.COMPLETED': '已完成',
  'automation.status.CANCELLED': '已结束',
  'automation.unit.minute': '分钟',
  'automation.unit.hour': '小时',
  'automation.unit.day': '天',
  'automation.unit.week': '周',
  'automation.frequency.once': '一次 · {{time}}',
  'automation.frequency.everyOne': '每{{unit}}',
  'automation.frequency.everyMany': '每 {{count}} {{unit}}',
  'automation.completion.default': '满足设定条件后自动结束',
  'automation.remaining.soon': '即将结束',
  'automation.remaining.days': '{{count}} 天',
  'automation.remaining.hours': '{{count}} 小时',
  'automation.unit.times': '次',
  'common.actions.deleting': '删除中…',
  'common.actions.delete': '删除',
  'common.actions.title': '操作',
  'common.iconAlt': '{{name}} 图标',
  'common.status.deleted': '已删除',
  'common.priority': '优先级',
  'common.basicInfo': '基础信息',
  'common.type': '类型',
  'common.visibility': '可见性',
  'common.createdAt': '创建时间',
  'common.updatedAt': '更新时间',
  'common.untitledFile': '未命名文件',
  'agents.skills.loadFailed': '关联 Skill 加载失败',
  'agents.detail.unsupportedEditor': '该智能体类型暂未接入编辑器',
  'agents.detail.unsupportedDelete': '该智能体类型的删除流程暂未接入',
  'agents.detail.deleteFailed': '删除失败，请稍后重试',
  'agents.knowledge.title': '知识库',
  'agents.knowledge.search': '知识检索',
  'agents.knowledge.available': '可用',
  'agents.knowledge.waitingReady': '等待资料就绪',
  'agents.knowledge.noSearchable': '暂无可检索资料',
  'agents.knowledge.fileCount': '共 {{count}} 个文件',
  'agents.knowledge.parsing': '解析中…',
  'agents.knowledge.reparse': '重新解析',
  'agents.knowledge.uploading': '上传中…',
  'agents.knowledge.add': '添加资料',
  'agents.knowledge.loading': '正在加载知识库…',
  'agents.knowledge.empty': '该智能体暂未上传知识库资料。',
  'agents.knowledge.deleteConfirmTitle': '确认删除该知识库文件？',
  'agents.knowledge.deleteConfirmDescription': '将从该认知体知识库移除「{{name}}」，后续知识检索不会再使用该文件。',
  'agents.skills.title': '关联 Skill',
  'agents.skills.count': '共 {{count}} 个',
  'agents.skills.empty': '该认知体暂未关联 Skill。',
  'agents.role.title': '角色设定',
  'agents.role.empty': '暂无角色设定',
  'agents.actions.goChat': '前往聊天',
  'agents.actions.edit': '编辑智能体',
  'agents.actions.delete': '删除智能体',
  'agents.delete.confirmTitle': '确认删除该智能体？',
  'agents.delete.confirmDescription': '删除后将停用并进入认知体已删除面板，全部设置和历史数据保留 30 天。期间可以恢复使用；到期后将自动彻底删除，无法恢复。',
  'agents.title': '认知体',
  'agents.library.mine': '我的认知体',
  'agents.library.deletedDescription': '删除后完整保留 30 天，可恢复使用；到期后将自动永久删除。',
  'agents.library.description': '管理你创建的认知、推理与协作智能体。',
  'agents.actions.create': '+ 创建认知体',
  'agents.library.count': '共 {{count}} 个认知体',
  'agents.purge.confirmTitle': '确认彻底删除该认知体？',
  'agents.purge.confirmDescription': '该操作将永久删除“{{name}}”的全部设置、{{conversationCount}} 个历史对话、{{messageCount}} 条消息、知识库、Skill 关联和运行数据。删除后无法恢复。',
  'agents.actions.purge': '彻底删除',
  'common.coverAlt': '{{name}} 封面',
  'common.processing': '处理中…',
  'common.author': '作者',
  'common.source': '来源',
  'skills.detail.loadFailed': '加载 Skill 失败',
  'skills.detail.restoreFailed': '恢复 Skill 失败',
  'skills.detail.statusUpdateFailed': 'Skill 状态更新失败',
  'skills.detail.deleteFailed': '删除 Skill 失败',
  'skills.detail.loading': '正在加载 Skill…',
  'skills.detail.draftVersion': '草稿版本',
  'skills.detail.unknownAuthor': '未知作者',
  'skills.detail.activationMode': '激活模式',
  'skills.detail.bindingCount': '关联次数',
  'skills.detail.usageCount': '使用次数',
  'skills.detail.versionCount': '版本数量',
  'skills.detail.retentionInfo': '删除保留信息',
  'skills.detail.retention30Days': '保留 30 天',
  'skills.detail.deletedAt': '删除时间',
  'skills.detail.purgeAt': '预计永久清理时间',
  'skills.detail.restoreScopeHint': '恢复只会恢复 Skill 本体，不会自动重新启用删除前的 Agent 绑定、会话激活或安装记录。',
  'skills.detail.noMarkdown': '暂无 SKILL.md 内容',
  'skills.detail.restoring': '正在恢复…',
  'skills.detail.restore': '恢复使用',
  'skills.detail.edit': '编辑 Skill',
  'skills.detail.archive': '归档 Skill',
  'skills.detail.delete': '删除 Skill',
  'skills.detail.currentVersion': '当前版本',
  'skills.detail.trustLevel': '信任等级',
  'skills.detail.installCount': '安装数量',
  'skills.detail.lastUsed': '最后使用',
  'skills.detail.versionHistory': '版本历史',
  'skills.detail.versionCountValue': '共 {{count}} 个',
  'skills.detail.noVersionRecords': '暂无版本记录。',
  'skills.detail.deleteConfirmTitle': '确认删除该 Skill？',
  'skills.detail.deleteConfirmDescription': '删除后将进入已删除面板，并从我的 Skill 和所有使用位置中移除。保留期内可以恢复。',
  'common.actions.close': '关闭',
  'common.loading': '正在加载…',
  'common.optional': '可选',
  'common.files': '文件',
  'common.saving': '正在保存…',
  'skills.editor.templateDescription': '说明这个 Skill 能做什么，以及应在什么情况下使用。',
  'skills.editor.templateHeading': '使用说明',
  'skills.editor.templateBody': '在这里编写可重复使用的执行步骤。',
  'skills.editor.loadFailed': 'Skill 加载失败',
  'skills.editor.prepareDraftFailed': '无法准备可编辑文件版本',
  'skills.editor.fileRefreshFailed': '文件刷新失败',
  'skills.editor.saveFailed': 'Skill 保存失败',
  'skills.editor.editTitle': '编辑 Skill',
  'skills.editor.createTitle': '创建 Skill',
  'skills.editor.description': '编辑原生 SKILL.md 与版本文件；已发布版本会先创建新的可编辑草稿。',
  'skills.editor.name': 'Skill 名称',
  'skills.editor.namePlaceholder': '例如：前端设计-通用',
  'skills.editor.nameHint': '可以直接使用当前语言命名；内部标识由系统维护。',
  'skills.editor.editSource': '当前编辑来源',
  'skills.editor.newDocument': '新文档',
  'skills.editor.versionFiles': '版本文件',
  'skills.editor.fileCount': '{{count}} 个文件',
  'skills.editor.noVersionYet': '尚未创建版本',
  'skills.editor.changeLog': '版本说明',
  'skills.editor.package.main': 'SKILL.md · 主指令文档',
  'skills.editor.package.reference': 'REFERENCE · 参考资料',
  'skills.editor.package.script': 'SCRIPT · 可执行脚本',
  'skills.editor.package.asset': 'ASSET · 静态资源',
  'skills.editor.package.other': 'LICENSE / OTHER · 其他文件',
  'skills.editor.diagnostics': '验证诊断',
  'skills.editor.diagnosticLocation': '第 {{line}} 行{{column}} · ',
  'skills.editor.filesCreateFirst': '先创建 Skill 草稿，之后即可上传 reference、script、asset、license 与其他版本文件。',
  'skills.editor.preparingDraft': '正在创建可编辑草稿版本…',
  'skills.editor.currentVersionLocked': '当前版本不可直接修改。系统正在基于当前版本准备新的草稿版本。',
  'skills.editor.saveNewVersion': '保存新版本',
  'common.actions.add': '+ 添加',
  'skills.create.recognition.waiting': '等待自动识别…',
  'skills.create.recognition.inspecting': '正在自动识别 Skill Package…',
  'skills.create.recognition.standard': '已自动识别 · 标准兼容',
  'skills.create.recognition.compatible': '已自动识别 · 兼容模式',
  'skills.create.recognition.rejected': '自动识别完成 · 存在阻断错误',
  'skills.create.recognition.idle': '上传或输入后将自动识别',
  'skills.create.importTitle': '导入 Skill',
  'skills.create.nameHint': '可以直接使用当前语言命名。系统会在后台自动生成并维护稳定的内部标识。',
  'skills.create.instructions': '使用说明',
  'skills.create.instructionsPlaceholder': '说明 Skill 能做什么，以及 Agent 应在什么情况下使用它。',
  'skills.create.license': '开源许可',
  'skills.create.compatibility': '兼容说明',
  'skills.create.compatibilityPlaceholder': '仅在存在明确运行环境要求时填写。',
  'skills.create.metadataHint': '键和值均按字符串保存。',
  'skills.create.allowedTools': '允许使用的工具',
  'skills.create.optionalExperimental': '可选 · 实验性',
  'skills.create.allowedToolsHint': '此实验字段仅作为可移植声明，不替代运行时权限与安全控制。',
  'skills.create.autoRecognizeAfterInput': '停止输入后自动识别。',
  'skills.create.rawMarkdown': '原始 SKILL.md',
  'skills.create.importPlaceholder': '---\nname: imported-skill\ndescription: 说明这个 Skill 的用途。\n---\n\n# 使用说明',
  'skills.create.importPreserveHint': '导入会保留原始 Skill Package；非关键规范偏差仅显示兼容性提示，不会调用 AI 改写内容。',
  'mcp.definition.editTitle': '编辑 MCP',
  'mcp.definition.addTitle': '添加 MCP',
  'mcp.definition.description': '创建一个可供所有 Agent 复用的 MCP Definition',
  'mcp.definition.namePlaceholder': '名称',
  'mcp.transport.streamableHttp': '远程 Streamable HTTP',
  'mcp.transport.stdio': '本地 stdio',
  'mcp.definition.descriptionPlaceholder': '描述',
  'mcp.definition.commandPlaceholder': 'command，例如 uvx',
  'mcp.definition.workingDirectoryPlaceholder': '工作目录（可选）',
  'mcp.definition.argsPlaceholder': '每行一个参数\n例如：--stdio',
  'mcp.auth.none': '无认证',
  'mcp.auth.environment': '环境变量 Secret',
  'mcp.auth.oauth2': 'OAuth 浏览器授权',
  'mcp.auth.customHeaders': '自定义 Header',
  'mcp.definition.apiKeyHeaderPlaceholder': 'API Key Header 名称，例如 X-API-Key',
  'mcp.definition.headerNamesPlaceholder': '每行一个允许的 Header 名称',
  'mcp.definition.environmentKeysPlaceholder': '每行一个允许的环境变量名称，例如 SERVICE_API_TOKEN',
  'mcp.definition.stdioHint': '保存只创建 Definition。连接时才会由 Electron Desktop Connector Host 弹窗确认并启动命令。',
  'mcp.definition.oauthHint': '安装后点击“授权”，SEEKMORE 会按 MCP OAuth 规范发现授权服务，并在系统浏览器完成登录。',
  'mcp.import.title': '导入 MCP',
  'mcp.import.description': '粘贴 MCP JSON 配置，语法高亮实时预览',
  'mcp.import.safetyHint': '导入只创建 Definition，不会连接或执行本地命令。Secret 值不会进入 Definition。',
  'mcp.import.willCreate': '将创建：{{names}}',
  'mcp.import.importing': '导入中…',
  'mcp.import.confirm': '确认导入',
  'mcp.detail.selectInstallation': '选择一个已安装 MCP 查看连接状态和工具',
  'mcp.detail.toolCount': '{{count}} 个可用工具',
  'mcp.detail.editDefinition': '编辑 Definition',
  'mcp.detail.availableTools': '可用工具',
  'mcp.detail.toolsHint': '该 MCP 连接后，工具会全部进入可用工具池，调用仍经过统一权限策略。',
  'mcp.detail.noTools': '尚未发现工具，请先连接并刷新。',
  'mcp.connectionFailed': '{{name}} 连接失败',
  'mcp.panel.description': '管理已安装服务、自定义 Definition、连接配置和可用工具。',
  'mcp.panel.create': '+ 创建 MCP',
  'mcp.panel.import': '导入 MCP',
  'mcp.panel.installedCount': '共 {{count}} 个已安装 MCP',
  'mcp.panel.loading': '正在加载 MCP…',
  'mcp.panel.emptyInstalled': '暂无已安装 MCP。',
  'mcp.confirm.revokeAuthorization': '确认解除 {{name}} 的授权？',
  'mcp.confirm.uninstall': '确认卸载 {{name}}？',
  'mcp.panel.userDefinitionsCount': '用户创建的 MCP Definition · {{count}}',
  'mcp.panel.custom': '自定义',
  'mcp.transport.localStdio': '本地 stdio',
  'mcp.actions.install': '安装',
  'mcp.confirm.deleteDefinition': '确认删除 {{name}}？',
  'mcp.panel.emptyDefinitions': '暂无用户创建的 MCP Definition。',
  'mcp.credential.token': '访问令牌',
  'mcp.credential.endpoint': 'MCP 服务地址',
  'mcp.credential.connectionString': '连接字符串',
  'mcp.credential.environmentId': '环境 ID',
  'mcp.credential.username': '用户名',
  'mcp.credential.authorizationHeader': 'Authorization 请求头',
  'mcp.credential.endpointDescription': '填写厂商控制台或自托管服务提供的完整 MCP 地址。',
  'mcp.credential.connectionStringDescription': '填写服务提供的完整连接字符串。',
  'mcp.credential.redisUrlDescription': '填写 Redis 服务连接地址。',
  'mcp.credential.environmentIdDescription': '填写需要连接的云环境标识。',
  'mcp.credential.usernameDescription': '填写该服务要求的用户名称。',
  'mcp.credential.authorizationDescription': '填写厂商要求的完整 Authorization 值。',
  'mcp.credential.secretDescription': '仅用于连接该 MCP，保存后不会在界面中明文返回。',
  'common.inputPlaceholder': '请输入…',
  'mcp.credential.setupTitle': '设置 {{name}}',
  'mcp.credential.updateTitle': '更新配置 {{name}}',
  'mcp.credential.configureTitle': '配置 {{name}}',
  'mcp.credential.storageHint': '本地 stdio Secret 只写入 Electron safeStorage；远程凭据由后端加密保存。',
  'mcp.credential.freeformHintBefore': '此自定义 Definition 未声明固定字段，请按每行',
  'mcp.credential.freeformHintAfter': '填写。',
  'mcp.credential.save': '保存配置',
  'errors.MCP_OAUTH_REVOKED': 'MCP OAuth 授权已撤销。',
  'errors.MCP_OAUTH_PENDING': 'MCP OAuth 授权尚未完成，可再次点击授权继续。',
  'common.name': '名称',
  'common.description': '描述',
  'common.actions.cancel': '取消',
  'common.actions.done': '完成',
  'common.actions.removeFile': '移除文件',
  'common.listSeparator': '、',
  'agents.edit.loadFailed': '加载认知体失败',
  'agents.edit.saveFailed': '保存认知体失败',
  'agents.edit.title': '编辑认知体',
  'agents.edit.description': '修改角色、内容知识库与关联 Skill',
  'agents.edit.namePlaceholder': '要叫什么好呢',
  'agents.edit.descriptionPlaceholder': '描述使用场景',
  'agents.role.placeholder': '身份、性格、行为准则、说话风格等',
  'agents.knowledge.contentLibrary': '内容知识库',
  'agents.knowledge.reparseAll': '重新解析全部',
  'agents.knowledge.existingFiles': '已有资料',
  'agents.knowledge.loadingExisting': '正在加载已有知识…',
  'agents.knowledge.newFiles': '本次新增',
  'agents.knowledge.uploadContent': '上传内容资料',
  'agents.knowledge.uploadDescription': '上传项目资料、政策文件和参考内容，用于知识召回。',
  'agents.knowledge.contentMaterials': '内容资料',
  'agents.knowledge.contentMaterial': '内容资料',
  'agents.create.failed': '创建认知体失败',
  'agents.create.title': '创建认知体',
  'agents.create.description': '定义角色、内容知识库与关联 Skill',
  'agents.create.name': '我的名称',
  'agents.create.namePlaceholder': '为我取一个名字',
  'agents.create.descriptionPlaceholder': '我要做什么',
  'agents.create.role': '我的角色设定',
  'agents.create.rolePlaceholder': '我的身份、性格、行为准则、说话风格等',
  'agents.create.creating': '创建中…',
  'agents.create.create': '创建',
  'skills.picker.addTitle': '添加 Skill',
  'skills.picker.description': '从我的 Skill 中选择并关联',
  'skills.picker.searchPlaceholder': '搜索我的 Skill',
  'skills.picker.loading': '正在加载 Skill…',
  'skills.picker.empty': '没有找到可关联的 Skill',
  'skills.picker.linkedCount': '已关联 {{count}} 项',
  'settings.model.currentPrimary': '当前主模型',
  'settings.model.primarySupportsVision': '{{model}} 已支持图片理解，您仍然可以为自己选择更合适的服务，保存后将优先使用您的选择。',
  'settings.model.primarySupportsImageGeneration': '{{model}} 已支持图像生成，您仍然可以为自己选择更合适的服务，保存后将优先使用您的选择。',
  'settings.model.capability.speechGeneration': '语音生成',
  'settings.model.capability.voiceCloning': '声音克隆',
  'settings.model.capability.musicGeneration': '音乐生成',
  'settings.model.primarySupportsAudio': '{{model}} 已支持{{capabilities}}，您仍然可以为自己选择更合适的服务，保存后将优先使用您的选择。',
  'settings.model.validatingAndSaving': '正在验证并保存…',
  'settings.model.saved': '设置已保存。',
  'settings.model.clearing': '正在清除设置…',
  'settings.model.cleared': '设置已清除。',
  'settings.model.clearConfirmTitle': '清除当前设置？',
  'settings.model.clearConfirmDescription': '将清除当前能力已保存的设置，并立即生效。',
  'settings.model.title': '模型设置',
  'settings.model.description': '为主模型、视觉识别、图像生成、视频生成、音频生成和联网搜索选择服务。',
  'settings.model.loadingCatalog': '正在加载模型目录…',
  'settings.model.primary.title': '主模型',
  'settings.model.primary.description': '负责对话、推理和工具调用。',
  'settings.model.vision.title': '视觉识别',
  'settings.model.vision.description': '优先使用您选择的视觉模型；未选择时才使用主模型原生视觉能力。',
  'settings.model.image.title': '图像生成',
  'settings.model.image.description': '为 image.generate 提供文生图、参考图生成和图片编辑能力。',
  'settings.model.video.title': '视频生成',
  'settings.model.video.description': '为 video.generate 选择视频生成服务和模型。',
  'settings.model.video.service': '视频生成服务',
  'settings.model.video.model': '视频生成模型',
  'settings.model.video.apiKey': '视频生成 API Key',
  'settings.model.video.apiKeyHint': '保存的服务和模型将作为 video.generate 的默认路由；API Key 复用该服务现有凭据。',
  'settings.model.capability.textToVideo': '文生视频',
  'settings.model.capability.imageToVideo': '图生视频',
  'settings.model.capability.firstLastFrame': '首尾帧生成',
  'settings.model.capability.referenceImages': '参考图生成',
  'settings.model.capability.generatedAudio': '原生音频',
  'recycle.confirmPermanentTitle': '永久删除该会话？',
  'recycle.confirmPermanentDescription': '“{{title}}”及其未被其他会话引用的消息、文件和生成结果将被永久删除，且无法恢复。',
  'recycle.title': '回收站',
  'recycle.description': '单独删除的 Conversation 按智能体归类保留 30 天，期间可以恢复。',
  'recycle.agentInUse': '使用中',
  'recycle.deletedConversationCount': '{{count}} 个已删除会话',
  'chat.agentActions.remarkPrompt': '修改备注：',
  'chat.agentActions.remarkFailed': '备注失败，请稍后重试',
  'chat.agentActions.pinFailed': '置顶失败，请稍后重试',
  'chat.agentActions.shareComingSoon': '分享功能即将上线',
  'chat.agentActions.reportComingSoon': '举报功能即将上线',
  'chat.agentActions.systemAgentCannotRemove': 'SEEKMORE 系统助手不可移除',
  'chat.agentActions.removeConfirm': '确认从聊天列表移除该助手？你仍可在“我的智能体”中找回。',
  'chat.agentActions.removeFailed': '移除失败，请稍后重试',
  'common.actions.back': '← 返回',
  'common.actions.refresh': '刷新',
  'common.actions.clear': '清除',
  'skills.library.mine': '我的 Skill',
  'skills.library.drafts': '草稿',
  'skills.library.archived': '存档',
  'skills.library.deleted': '已删除',
  'skills.library.actionFailed': 'Skill 状态操作失败',
  'skills.library.purgeTitle': '彻底删除 Skill？',
  'skills.library.purgeDescription': '此操作会立即从数据库永久删除“{{name}}”，所有版本、文件和关联记录都将永久移除，且无法恢复。',
  'skills.library.purge': '彻底删除',
  'skills.library.deletedDescription': '查看并恢复仍处于保留期内的 Skill。',
  'skills.library.description': '创建、导入、验证并管理认知体可用的本地 Skill。',
  'skills.library.create': '+ 创建 Skill',
  'skills.library.searchDeleted': '搜索已删除 Skill',
  'skills.library.search': '搜索名称或描述',
  'skills.library.count': '共 {{count}} 个 Skill',
  'skills.library.retentionWarning': '已删除的 Skill 将保留 30 天，到期后会自动从数据库彻底删除，所有版本、文件和关联记录将永久移除且无法恢复。',
  'skills.library.loading': '正在加载 Skill…',
  'skills.library.emptyDeleted': '暂无处于保留期内的已删除 Skill。',
  'skills.library.empty': '暂无符合条件的 Skill。',
  'settings.model.audio.title': '音频生成',
  'settings.model.audio.description': '选择用于语音生成、声音克隆和音乐生成的服务。',
  'settings.model.audio.service': '音频生成服务',
  'settings.model.selectService': '请选择服务',
  'settings.model.audio.apiKey': '音频生成 API Key',
  'settings.model.audio.apiKeyHint': 'API Key 保存时不校验套餐和接口权限；实际调用时只限制当前不可用的能力，不影响其他音频能力。',
  'settings.model.saveSettings': '保存设置',
  'settings.model.configured': '已设置',
  'settings.model.capability.unsupported': '不支持',
  'settings.model.capability.paidOnly': '需付费订阅',
  'settings.model.capability.planDependent': '取决于账户权限',
  'settings.model.capability.freeCredits': '支持免费积分',
  'settings.model.capability.available': '可用',
  'settings.model.web.title': '联网搜索',
  'settings.model.web.description': '为 web.search 配置用户自己的搜索服务。未配置时，主模型只会收到能力不可用状态。',
  'settings.model.web.service': '搜索服务',
  'settings.model.web.apiKey': '联网搜索 API Key',
  'explore.empty': '暂无可用资源',
  'explore.searchResults': '搜索结果',
  'explore.featured': '精选资源',
  'explore.popular': '热门资源',
  'tools.library.title': '工具',
  'tools.library.description': 'SEEKMORE 系统工具',
  'tools.library.count': '共 {{count}} 个工具',
  'workspace.readOnly': '只读',
  'workspace.none': '不使用项目',
  'workspace.unavailable': '项目不可用',
  'workspace.loadFailed': '加载工作区失败',
  'workspace.desktopOnly': '此功能仅支持 SEEKMORE 桌面端',
  'workspace.bridgeLoading': '桌面桥接正在加载，请稍后重试',
  'workspace.bridgeFailed': '桌面桥接加载失败，请重新启动 SEEKMORE',
  'workspace.pickerFailed': '无法打开文件夹选择器，请查看桌面运行日志',
  'workspace.openFolderFailed': '打开文件夹失败',
  'workspace.searchPlaceholder': '搜索工作项目',
  'workspace.empty': '暂无项目',
  'workspace.newProject': '新工作项目',
  'workspace.createBlank': '新建空白项目',
  'workspace.useExistingFolder': '使用现有文件夹',
  'skills.preview.standard': '标准兼容',
  'skills.preview.compatible': '兼容模式',
  'skills.preview.rejected': '无法创建',
  'skills.preview.inspecting': '正在识别',
  'skills.preview.waiting': '等待识别',
  'skills.preview.standardHint': '“保存草稿”和“直接使用”只使用这里的原始内容。',
  'skills.preview.importHint': '上传或输入后自动识别，展示实际解析的原始 SKILL.md。',
  'skills.preview.template': '---\nname: skill-draft\ndescription: 说明这个 Skill 能做什么，以及应在什么情况下使用。\n---\n\n# 使用说明\n',
  'skills.preview.packageContent': '包内容',
  'skills.preview.untitled': '未命名 Skill',
  'skills.preview.onlySkillMd': '仅 SKILL.md',
  'skills.preview.canRunStandard': '可创建并运行 · 符合 Agent Skills 标准',
  'skills.preview.canRun': '可创建并运行',
  'skills.preview.warningCount': ' · 存在 {{count}} 项标准兼容性提示',
  'skills.preview.compatibleSuffix': ' · 兼容模式',
  'skills.preview.blockingCount': ' · 存在 {{count}} 项阻断错误',
  'skills.preview.diagnostics': '验证诊断',
  'skills.preview.linePrefix': '第 {{line}} 行{{column}} · ',
  'skills.preview.warningNonBlocking': '不影响创建和运行',
  'chat.missingModel.title': '尚未配置模型',
  'chat.missingModel.description': '请先在模型设置中选择模型并填写 API Key，保存后即可发送消息。',
  'chat.missingModel.openSettings': '去设置',
  'chat.missingModel.later': '稍后再说',
  'chat.restore.failed': '对话恢复失败',
  'chat.restore.loading': '正在恢复对话',
  'common.actions.retry': '重试',
  'mcp.dropdown.globalToggle': 'MCP 总开关',
  'mcp.dropdown.searchPlaceholder': '搜索 MCP 服务',
  'agents.image.avatarPreview': '认知体头像预览',
  'agents.image.avatar': '头像',
  'agents.image.coverPreview': '认知体封面预览',
  'agents.image.cover': '封面',
  'skills.create.modalTitle': '创建 Skill',
  'skills.create.modalDescription': '创建、AI 生成或导入 Agent Skill Package',
  'runtime.status.completed': '执行完成',
  'common.actions.view': '查看',
  'common.actions.download': '下载',
  'chat.attachments.add': '添加附件',
  'chat.attachments.count': '{{count}} 个附件',
  'chat.branch.startHere': '从此处开始新的对话分支',
  'chat.branch.createHere': '从这里创建分支',
  'chat.branch.create': '创建对话分支',
  'chat.image.generating': '图片生成中',
  'chat.history.empty': '暂无历史对话',
  'chat.contact.remarkPlaceholder': '输入备注...',
  'chat.search.conversations': '对话',
  'chat.search.browserTitle': '搜索 “{{query}}”',
  'chat.search.browserSubtitle': '前往浏览器搜索',
  'chat.search.agents': '助手',
  'chat.audio.unsupportedBrowser': '您的浏览器不支持音频播放。',
  'chat.jumpToBottom': '回到底部',
  'explore.categories': '探索分类',
  'explore.searchPlaceholder': '搜索认知体或 SKILL',
  'webSearch.card.query': '搜索内容',
  'webSearch.card.sources': '高相关来源',
  'webSearch.card.openBrowser': '在浏览器中打开',
  'workspace.create.namePlaceholder': '项目名称，例如 test',
  'workspace.create.name': '项目名称',
  'charts.config': '图表配置',
  'charts.themeColor': '主题颜色',
  'skills.files.title': '文件',
  'skills.files.versionFileCount': '{{count}} 个版本文件',
  'skills.files.uploadHint': '上传支持单文件、多文件和完整文件夹。选择完整 Skill 根目录时，SKILL.md 仍由文档编辑区管理。',
  'memory.savedTitle': '保存的记忆',
  'memory.savedDescription': '数据管理 · 候选记忆不会默认注入上下文。',
  'memory.backToData': '返回数据管理',
  'sidebar.extensions.reading': '读书',
  'sidebar.extensions.shortVideo': '短视频',
  'sidebar.extensions.community': '社区',
  'sidebar.user.avatarAlt': '用户头像',
  'sidebar.user.changeAvatar': '更换头像',
  'sidebar.user.editProfile': '点击设置资料',
  'sidebar.user.profileTitle': '用户资料',
  'sidebar.user.username': '用户名',
  'sidebar.user.usernamePlaceholder': '输入用户名',
  'sidebar.user.saveFailed': '保存用户资料失败',
  'common.search': '搜索',
  'common.pagination.previous': '上一页',
  'common.pagination.next': '下一页',
  'chat.input.dropFiles': '拖拽文件到这里上传',
  'mcp.dropdown.disableGlobal': '关闭 MCP 总开关',
  'mcp.dropdown.enableGlobal': '开启 MCP 总开关',
  'mcp.dropdown.enabled': '已开启',
  'mcp.dropdown.disabled': '已关闭',
  'mcp.dropdown.empty': '暂无 MCP 服务',
  'mcp.dropdown.noMatch': '没有匹配的 MCP 服务',
  'workspace.permission.confirm.title': '请求批准',
  'workspace.permission.confirm.description': '读取直接执行，写入、修改、命令和外部副作用逐次请求批准',
  'workspace.permission.audit.title': '替我审批',
  'workspace.permission.audit.description': '低风险和中风险自动执行，仅高风险操作请求批准',
  'workspace.permission.full.title': '完全访问权限',
  'workspace.permission.full.description': '在当前工作区和已启用工具范围内自动执行，不再逐项请求批准',
  'workspace.permission.approveSeekmore': '批准 SEEKMORE 操作',
  'workspace.create.failed': '创建失败',
  'workspace.create.desktopOnly': '此功能仅支持 SEEKMORE 桌面端',
  'workspace.create.bridgeLoading': '桌面桥接正在加载，请稍后重试',
  'workspace.create.bridgeFailed': '桌面桥接加载失败，请重新启动 SEEKMORE',
  'workspace.create.openPickerFailed': '无法打开文件夹选择器，请查看桌面运行日志',
  'workspace.create.nameRequired': '请填写项目名称',
  'workspace.create.locationRequired': '请选择项目创建位置',
  'workspace.create.locationUnset': '尚未选择创建位置',
  'workspace.create.selecting': '选择中…',
  'workspace.create.selectLocation': '选择位置',
  'workspace.create.creating': '创建中…',
  'workspace.create.createAndSelect': '创建并选择',
  'explore.loading': '加载中…',
  'markdown.code.preview': '预览',
  'markdown.code.code': '代码',
  'markdown.code.showCode': '查看代码',
  'markdown.code.previewTitle': 'HTML 预览',
  'markdown.mermaid.pending': 'Mermaid 将在生成完成后渲染',
  'markdown.mermaid.renderFailed': 'Mermaid 渲染失败',
  'markdown.textBlock.prompt': '提示词',
  'markdown.textBlock.text': '文本',
  'embodied.title': '具身体',
  'embodied.description': '人形机器人及具身终端互联运行｜下一阶段实现中',
  'tools.uncategorized': '未分类',
  'tools.requiresConfirmation': '需要确认',
  'tools.enable': '开启工具 {{name}}',
  'tools.disable': '关闭工具 {{name}}',
  'skills.files.loadFailed': '文件加载失败',
  'skills.files.uploading': '正在上传 {{count}} 个文件…',
  'skills.files.uploadedOne': '已上传 {{path}}',
  'skills.files.uploadedMany': '已上传 {{count}} 个文件，并保留真实目录结构。',
  'skills.files.uploadFailed': '上传失败',
  'skills.files.deletingOne': '正在删除文件…',
  'skills.files.deletingMany': '正在删除 {{count}} 个文件…',
  'skills.files.deleteFailed': '删除失败',
  'skills.files.confirmDeleteFile': '确认删除文件 {{path}}？',
  'skills.files.deletedFile': '已删除 {{path}}',
  'skills.files.confirmDeleteDirectory': '确认删除文件夹 {{path}} 及其中 {{count}} 个文件？',
  'skills.files.deletedDirectory': '已删除文件夹 {{path}}',
  'skills.files.emptyEditable': '暂无版本文件。点击“上传”添加 references、scripts、assets、license 或其他资源。',
  'skills.files.emptyReadonly': '当前版本暂无其他文件。',
  'skills.status.deleted': '已删除',
  'skills.status.blocked': '已阻止',
  'skills.status.quarantined': '已隔离',
  'skills.status.reviewRequired': '待审核',
  'skills.status.ACTIVE': '已启用',
  'skills.status.DRAFT': '草稿',
  'skills.status.VALIDATING': '验证中',
  'skills.status.REJECTED': '待修正',
  'skills.status.ARCHIVED': '已存档',
  'skills.status.DISABLED': '已停用',
  'skills.status.STALE': '待更新',
  'skills.action.publish': '发布使用',
  'skills.action.restore': '恢复使用',
  'skills.action.enabled': '已启用',
  'skills.unknownAuthor': '未知作者',
  'skills.noVersion': '暂无版本',
  'skills.noDescription': '暂无描述',
  'skills.author': '作者：{{name}}',
  'skills.processing': '处理中…',
  'skills.deleting': '删除中…',
  'skills.permanentDelete': '彻底删除',
  'memory.empty': '暂无记忆',
  'memory.loadMore': '加载更多',
  'memory.searchPlaceholder': '搜索记忆内容、主题、来源…',
  'memory.refresh': '刷新',
  'settings.model.apiKey.saved': '已保存 ••••{{hint}}',
  'settings.model.apiKey.paste': '粘贴 API Key',
  'settings.model.apiKey.get': '获取',
  'settings.model.selectModel': '请选择模型',
  'settings.model.noModels': '暂无可用模型',
  'settings.model.expandList': '展开模型列表',
  'settings.model.providerListLabel': '{{label}}列表',
  'settings.model.recommended': '推荐',
  'settings.model.roleModel': '{{title}}模型',
  'settings.model.saving': '正在验证并保存…',
  'settings.model.save': '保存设置',
  'settings.model.clear': '清除',
  'sidebar.user.defaultNickname': '用户昵称',
  'conversation.more.deleteTitle': '删除对话',
  'conversation.more.deleteWithAutomations': '此对话还有 {{count}} 个正在运行或暂停的自动任务。删除对话后这些任务会立即结束；对话进入回收站后可恢复，但自动任务不会自动恢复。',
  'conversation.more.deleteDescription': '删除后将进入回收站，及此聊天期间保存的所有记忆。30 天内可恢复。',
  'conversation.more.deleteAndEnd': '删除对话并结束任务',
  'conversation.more.remark': '备注',
  'conversation.more.delete': '删除',
  'conversation.more.report': '举报',
  'conversation.more.reportMessage': '举报 {{id}}',
  'conversation.more.processing': '处理中…',
  'conversation.more.moreActions': '更多操作',
  'conversation.more.deleteFailed': '删除失败，请稍后重试',
  'common.confirm.delete': '删除',
  'common.confirm.cancel': '取消',
  'common.copy': '复制',
  'common.copied': '已复制',
  'common.copyFailed': '复制失败',
  'agent.unnamed': '未命名智能体',
  'agent.loadFailed': '获取助手失败',
  'chat.actions.addAttachment': '添加附件',
  'chat.actions.mcpManageEnabled': 'MCP 总开关已开启，点击管理',
  'chat.actions.mcpManageDisabled': 'MCP 总开关已关闭，点击管理',
  'chat.actions.collapseWorkflow': '折叠 Workflow',
  'chat.actions.expandWorkflow': '展开 Workflow',
  'chat.uploadFailed': '上传失败',
  'chat.workflow.replyToContinue': '回复上方问题以继续当前 Workflow…',
  'chat.input.addMore': '添加更多内容…',
  'chat.input.sendAnything': '随心发送…',
  'chat.message.collapse': '点击收起',
  'chat.message.expand': '点击展开',
  'chat.toolbar.branching': '正在创建分支',
  'chat.toolbar.createBranch': '从这里创建分支',
  'chat.reasoning.thinking': '请让我思考一下',
  'chat.reasoning.processed': '已处理',
  'webSearch.local': '本地网页搜索',
  'webSearch.status.queued': '排队中',
  'webSearch.status.searching': '搜索中',
  'webSearch.status.waiting': '等待中',
  'webSearch.status.blocked': '已阻止',
  'webSearch.status.completed': '已完成',
  'webSearch.status.failed': '失败',
  'webSearch.status.partial': '部分完成',
  'webSearch.status.cancelled': '已取消',
  'webSearch.status.skipped': '已跳过',
  'chat.sender.you': '你',
  'chat.sender.system': '系统',
  'agent.context.edit': '编辑',
  'agent.context.remark': '备注',
  'agent.context.unpin': '取消置顶',
  'agent.context.pin': '置顶',
  'agent.context.share': '分享',
  'agent.context.report': '举报',
  'agent.context.remove': '移除',
  'chat.defaultGreeting': '今天有什么可以帮您？',
  'chat.search.placeholder': '搜索',
  'chat.composer.stop': '停止当前运行',
  'chat.composer.stopPendingConnection': '已记录停止请求，等待连接后发送。',
  'chat.composer.stopRequesting': '正在停止本次运行，等待确认。',
  'chat.composer.stopFailed': '停止未获确认，请同步会话后重试。',
  'chat.composer.send': '发送消息',
  'turn.jumpTo': '跳转到第 {{index}} 个回合：{{preview}}',
  'turn.emptyMessage': '空白消息',
  'object.generatedFile': '生成文件',
  'object.validating': '正在校验',
  'object.uploadProgress': '上传中 {{progress}}%',
  'object.preparingPreview': '正在准备预览',
  'object.uploadOrProcessFailed': '上传或处理失败',
  'object.unsupportedType': '暂不支持该文件类型',
  'object.ready': '已就绪，可发送',
  'object.removeAfterProcessed': '处理完成后可移除',
  'object.removeAttachment': '移除附件',
  'object.imageLoadFailed': '图片无法加载',
  'object.preview.open': '点击预览',
  'object.preview.download': '下载文件',
  'object.preview.expand': '放大预览',
  'object.preview.restore': '还原预览',
  'object.preview.close': '关闭预览',
  'object.preview.loading': '正在加载预览',
  'object.preview.failed': '预览加载失败',
  'object.preview.unavailable': '暂不支持内容预览，可直接下载文件',
  'object.preview.empty': '暂无可预览内容',
  'object.preview.previous': '上一个文件',
  'object.preview.next': '下一个文件',
  'object.preview.index': '{{current}} / {{total}}',
  'runtime.executingTask': '正在执行当前任务',
  'assistant.thinking': '正在思考',
  'workflow.status.waiting': '等待',
  'workflow.status.inProgress': '进行中',
  'workflow.status.completed': '完成',
  'workflow.status.blocked': '阻塞',
  'workflow.status.failed': '失败',
  'workflow.status.skipped': '已跳过',
  'workflow.status.cancelled': '已取消',
  'workflow.progress': '任务进度',
  'workflow.blocked': '阻塞',
  'workflow.wait.input': '等待输入',
  'workflow.wait.approval': '等待授权',
  'workflow.wait.external': '等待外部',
  'workflow.wait.resourceConflict': '资源冲突',
  'workflow.wait.continue': '等待继续',
  'time.loadFailed': '时间数据加载失败',
  'time.operationFailed': '操作失败',
  'time.notificationConfirmFailed': '通知确认失败',
  'welcome.heading': '今天想一起做点什么？',
  'welcome.presentation.label': '创作一份演示文档',
  'welcome.presentation.prompt': '帮我创作一份演示文档',
  'welcome.game.label': '创作一个游戏',
  'welcome.game.prompt': '帮我创作一个游戏',
  'welcome.petGif.label': '为桌宠创作一份GIF表情',
  'welcome.petGif.prompt': '帮我为桌宠创作一份 GIF 表情',
  'welcome.blender.label': '创造3D模型',
  'welcome.blender.prompt': '帮我用 Blender 创作一个 3D 模型',
  'welcome.github.label': '管理GitHub',
  'welcome.github.prompt': '帮我处理 GitHub 上的工作',
  'welcome.image.label': '创作图片',
  'welcome.image.prompt': '帮我生成一张图片',
  'welcome.music.label': '音乐创作',
  'welcome.music.prompt': '帮我创作一段音乐',
  'welcome.priceWatch.label': '持续自动任务',
  'welcome.priceWatch.prompt': '帮我监控电商平台上的商品价格和库存，在商品降价或补货时提醒我',
  'welcome.automation.label': '定时持续任务',
  'welcome.automation.prompt': '帮我创建一个持续自动执行的任务，每天帮我做',
  'explore.tabs.overview': '总览',
  'explore.tabs.agents': '认知体',
  'explore.agent.directory': '认知体目录',
  'explore.skill.directory': 'SKILL 目录',
  'markdown.error.defaultTitle': '渲染失败',
  'markdown.error.defaultMessage': '内容无法安全渲染。',
  'markdown.error.unknown': '未知错误',
  'markdown.loading': '内容生成中',
  'myagent.nav.cognitive.title': '认知体',
  'myagent.nav.cognitive.description': '定义专业认知角色',
  'myagent.nav.embodied.title': '具身体',
  'myagent.nav.embodied.description': '设备与现实世界执行',
  'myagent.nav.skill.title': 'Skill',
  'myagent.nav.skill.description': '可复用的程序性知识',
  'myagent.nav.mcp.title': 'MCP',
  'myagent.nav.mcp.description': '外部应用与工具服务',
  'myagent.nav.tool.title': '工具',
  'myagent.nav.tool.description': '系统应用工具',
  'myagent.nav.recycle.title': '回收站',
  'myagent.nav.recycle.description': '按智能体管理已删除对话',
  'skills.security.SAFE': '安全',
  'skills.security.REVIEW_REQUIRED': '待审查',
  'skills.security.QUARANTINED': '已隔离',
  'skills.security.BLOCKED': '已阻止',
  'skills.files.noUploadable': '没有可上传的文件。根目录 SKILL.md 请在文档编辑区修改。',
  'skills.files.chooseFailed': '文件选择失败',
  'skills.files.desktopChooseFailed': '桌面文件选择失败',
  'skills.files.addToDirectory': '向 {{directory}} 添加文件',
  'skills.files.uploadFileOrFolder': '上传 Skill 文件或文件夹',
  'skills.files.uploadFile': '上传 Skill 文件',
  'skills.files.reading': '读取中…',
  'skills.files.upload': '上传',
  'artifact.status.DRAFT': '草稿',
  'artifact.status.GENERATING': '生成中',
  'artifact.status.RENDERING': '渲染中',
  'artifact.status.COMPLETED': '已完成',
  'artifact.status.FAILED': '失败',
  'artifact.status.ARCHIVED': '已归档',
  'sidebar.nav.chat': '对话',
  'sidebar.nav.myagent': '我的',
  'sidebar.nav.explore': '探索',
  'sidebar.nav.settings': '设置',
  'memory.loadFailed': '加载记忆失败',
  'memory.confirm.forgetTitle': '忘记记忆',
  'memory.confirm.forgetDescription': '忘记后不会参与记忆召回，可在已删除中恢复。',
  'memory.confirm.forget': '忘记',
  'memory.confirm.purgeTitle': '彻底删除记忆',
  'memory.confirm.purgeDescription': '彻底删除后无法恢复。',
  'memory.confirm.purge': '彻底删除',
  'memory.operationFailed': '操作失败',
  'skills.security.CLEAR': '安全',
  'errors.branchMissingConversationId': '分支创建成功但缺少 conversationId',
  'chat.openConversation': '打开对话：{{id}}',
  'chat.upload.missingObjectId': '上传成功但缺少 objectId。',
  'chat.upload.objectNotReady': 'Object 尚未完成处理，不能发送。',
  'chat.init.missingConversationId': '没有获取到会话 ID。',
  'chat.init.failed': '初始化会话失败。',
  'chat.title.missingConversationId': '缺少 conversationId。',
  'chat.title.missingSeed': '缺少标题 seed。',
  'chat.title.generateFailed': '标题生成失败。',
  'chat.title.missingAgentId': '缺少 agentId。',
  'chat.title.createFailed': '标题创建失败。',
  'chat.title.empty': '标题不能为空。',
  'chat.title.conflict': '标题已被其他操作更新，请刷新后重试。',
  'chat.title.renameFailed': '重命名失败。',
  'chat.conversation.remarkFailed': '备注失败。',
  'chat.conversation.deleteFailed': '删除失败。',
  'chat.branch.unsaved': '当前对话尚未保存，暂时无法创建分支。',
  'chat.branch.createFailed': '无法创建对话分支，请稍后重试。',
  'chat.turn.blankMessage': '空白消息',
  'chat.download.failedStatus': '下载失败：HTTP {{status}}',
  'runtime.workspace.invalidResponse': '后端没有返回有效工作区。',
  'runtime.workspace.idRequired': '工作区 ID 不能为空。',
  'runtime.workspace.notFound': '工作区不存在。',
  'runtime.workspace.conversationIdRequired': '会话 ID 不能为空。',
  'cognitive.loadFailed': '加载认知体失败。',
  'cognitive.deletedLoadFailed': '加载已删除认知体失败。',
  'cognitive.knowledge.loadFailed': '知识库加载失败。',
  'cognitive.knowledge.uploadFailed': '知识库文件上传失败。',
  'cognitive.knowledge.deleteFailed': '知识库文件删除失败。',
  'cognitive.knowledge.reparseFailed': '知识库重新解析失败。',
  'myagent.loadFailed': '认知体加载失败。',
  'skills.validation.failedWithMessage': 'Skill 验证未通过：{{message}}',
  'skills.validation.failed': 'Skill 验证未通过。',
  'skills.deleted.restoreFirst': '该 Skill 已删除，请先恢复 Skill。',
  'skills.deleted.bindingBlocked': '已删除的 Skill 不能新增关联，请先恢复 Skill。',
  'skills.create.templateDescription': '说明这个 Skill 能做什么，以及应在什么情况下使用。',
  'skills.create.templateHeading': '使用说明',
  'skills.create.templateBody': '在这里编写可重复使用的执行步骤。',
  'skills.request.failed': 'Skill 请求失败。',
  'skills.import.blocked': 'Skill Package 存在阻断错误，暂时无法导入。',
  'skills.import.standardRecognized': 'Skill Package 已自动识别，符合 Agent Skills 标准。',
  'skills.import.compatibleRecognized': 'Skill Package 已自动识别，可按兼容模式导入。',
  'skills.import.inspectFailed': 'Skill Package 自动识别失败。',
  'skills.create.aiGenerated': 'AI 已生成标准 Skill，请检查右侧内容后选择保存草稿或直接使用。',
  'skills.activate.failed': 'Skill 未能启用。',
  'skills.activate.draftSavedButFailed': '草稿已保存，但直接使用失败：{{message}}',
  'skills.draft.missingVersionId': 'Skill 草稿已创建，但未返回可用的草稿版本 ID。',
  'skills.draft.saved': 'Skill 已保存为草稿。',
  'skills.active.saved': 'Skill 已保存并可直接使用。',
  'skills.import.notInspected': 'Skill Package 尚未完成自动识别。',
  'skills.import.stillBlocked': '导入包仍存在阻断错误。',
  'skills.import.missingVersionId': 'Skill Package 已导入，但未返回可用的草稿版本 ID。',
  'skills.import.standardDraftSaved': '标准 Skill Package 已保存为草稿。',
  'skills.import.compatibleDraftSaved': 'Skill Package 已按兼容模式保存为草稿。',
  'skills.import.standardActivated': '标准 Skill Package 已导入并可直接使用。',
  'skills.import.compatibleActivated': 'Skill Package 已按兼容模式导入并可直接使用。',
  'skills.actions.creating': '正在创建…',
  'skills.actions.aiCreate': 'AI 创建',
  'skills.actions.saving': '正在保存…',
  'skills.actions.saveDraft': '保存草稿',
  'skills.actions.activating': '正在启用…',
  'skills.actions.retryActivate': '重试直接使用',
  'skills.actions.useDirectly': '直接使用',
  'skills.error.nameConflict': 'Skill 的内部标识发生冲突，请重新创建后再试。',
  'skills.error.nameReserved': '对应 Skill 仍处于删除保留期，请恢复原 Skill 或等待彻底删除后再试。',
  'skills.error.importChanged': 'Skill Package 在识别后发生了变化，或识别结果已经失效。请等待系统重新识别后再操作。',
  'skills.error.importTokenInvalid': '当前导入识别凭证无效，请等待系统重新识别 Skill Package。',
  'skills.error.validationRequired': 'Skill 尚未完成有效验证，暂时不能直接使用。',
  'skills.error.validationFailed': 'Skill 存在阻断错误，暂时不能直接使用。',
  'skills.error.securityReviewRequired': 'Skill 尚未通过安全检查，暂时不能直接使用。',
  'skills.error.securityRejected': 'Skill 未通过安全检查，无法直接使用。',
  'skills.error.nameImmutable': 'Skill 的内部标识不能修改。界面名称可以单独修改。',
  'skills.error.draftVersionNotFound': '没有找到可验证或发布的 Skill 草稿版本。',
  'skills.error.versionNotDraft': '当前 Skill 版本已不再是草稿，不能重复发布。',
  'skills.error.versionAlreadyPublished': '当前 Skill 版本已经发布，无需重复启用。',
  'skills.error.alreadyActive': '当前 Skill 已经处于可用状态。',
  'skills.error.revisionConflict': 'Skill 已被其他操作更新，请刷新后重新尝试。',
  'skills.error.displayNameInvalid': 'Skill 名称不能为空，最多 120 个字符。',
  'skills.error.packageRejected': 'Skill Package 存在阻断错误，无法保存或直接使用。',
  'skills.error.resourceNotFound': 'Skill 引用的资源文件不存在。草稿已保留，但当前操作无法完成。',
  'skills.error.notFound': '没有找到对应的 Skill，它可能已被删除。',
  'skills.error.permissionDenied': '你没有权限执行当前 Skill 操作。',
  'skills.error.requestWithCode': 'Skill 请求失败（{{code}}）。',
  'skills.error.stateConflict': 'Skill 当前状态或名称发生冲突。请检查是否已经存在同名草稿或已导入的 Skill。',
  'skills.error.badRequest': 'Skill 请求内容存在错误，请查看验证诊断后修改。',
  'skills.error.versionMissing': '没有找到对应的 Skill 或版本。',
  'skills.error.packageTooLarge': 'Skill Package 超过允许的文件大小限制。',
  'skills.error.metadataDuplicate': 'metadata 键重复：{{key}}',
  'skills.files.noneUploadable': '没有可上传的文件。根目录 SKILL.md 请在文档编辑区修改。',
  'skills.files.selectionFailed': '文件选择失败。',
  'skills.files.desktopSelectionFailed': '桌面文件选择失败。',
  'skills.files.uploadFilesOrFolder': '上传 Skill 文件或文件夹',
  'skills.files.uploadFiles': '上传 Skill 文件',
  'skills.files.pathRequired': '文件路径不能为空。',
  'skills.files.invalidDirectory': '文件路径包含无效目录。',
  'skills.files.duplicatePath': '本次选择包含重复路径：{{path}}',
  'skills.loadFailed': 'Skill 加载失败。',
  'files.upload.partitionRequired': '上传文件需要明确的 Agent 和 Conversation 分区。',
  'files.upload.processFailed': '文件上传或处理失败。',
  'files.upload.missingObjectId': '上传成功但后端未返回 objectId。',
  'files.upload.objectNotReady': 'Object 尚未完成处理，不能发送。',
  'files.image.unsupportedFormat': '暂不支持该图片格式，请使用 PNG、JPEG 或 WebP。',
  'files.image.decodeFailed': '图片文件无法解码或已损坏。',
  'files.type.unsupported': '暂不支持该文件类型。',
  'http.refresh.missingAccessToken': '刷新接口未返回 Access Token。',
  'skills.error.withCode': '{{message}}（{{code}}）',
  'skills.error.httpStatus': '{{message}}（HTTP {{status}}）',
  'errors.AUTH_USER_ID_REQUIRED': '缺少用户身份。',
  'errors.COGNITIVE_CAPABILITIES_INVALID': 'capabilities 必须是数组或逗号分隔字符串。',
  'errors.COGNITIVE_CAPABILITY_UNSUPPORTED': '不支持的能力：{{capability}}',
  'errors.COGNITIVE_KNOWLEDGE_UPLOAD_BATCH_LIMIT': '知识库文件单次最多上传 {{limit}} 个。',
  'errors.COGNITIVE_KNOWLEDGE_FILE_TOO_LARGE': '文件 {{fileName}} 超过 {{maxMb}} MB 限制。',
  'errors.COGNITIVE_KNOWLEDGE_FILE_TYPE_UNSUPPORTED': '暂不支持该文件类型：{{fileName}}（{{mimeType}}）',
  'errors.COGNITIVE_IMAGE_FORMAT_UNSUPPORTED': '头像/封面仅支持 PNG、JPG、WebP：{{fileName}}',
  'errors.COGNITIVE_IMAGE_TOO_LARGE': '图片 {{fileName}} 超过 {{maxMb}} MB 限制。',
  'errors.AUTH_SESSION_EXPIRED': '本地会话已过期。',
  'errors.CHAT_LEGACY_CREATE_MESSAGE_DISABLED': '旧消息创建链路已停用。',
  'errors.CHAT_LEGACY_CREATE_MESSAGE_WITH_AGENT_DISABLED': '旧智能体消息创建链路已停用。',
  'errors.BRANCH_SOURCE_MESSAGE_NOT_FOUND': '分支起点消息不存在。',
  'errors.BRANCH_SOURCE_NOT_ASSISTANT': '只能从助手消息创建分支。',
  'errors.BRANCH_SOURCE_NOT_COMPLETED': '消息尚未完成，不能创建分支。',
  'errors.BRANCH_MESSAGE_TREE_CYCLE': '消息树存在循环，无法创建分支。',
  'errors.BRANCH_CONTEXT_TOO_LONG': '分支上下文过长，无法创建快照。',
  'errors.BRANCH_MESSAGE_CROSS_CONVERSATION': '消息树跨越了其他会话。',
  'errors.BRANCH_PARENT_CHAIN_INCOMPLETE': '消息父链不完整，无法创建分支。',
  'errors.CONVERSATION_ARCHIVED_BRANCH_FORBIDDEN': '已归档会话不能创建分支。',
  'errors.BRANCH_CONTEXT_EMPTY': '没有可复制的对话上下文。',
  'errors.BRANCH_SNAPSHOT_CREATE_FAILED': '分支消息快照创建失败。',
  'errors.BRANCH_REQUEST_ID_CONFLICT': 'requestId 已用于其他对话分支请求。',
  'errors.BRANCH_METADATA_INVALID': '分支会话元数据不完整。',
  'errors.AGENT_UNAVAILABLE': 'Agent 不存在或已停用。',
  'errors.CONVERSATION_DELETE_DENIED': '无权删除该会话。',
  'errors.CONVERSATION_DELETED_NOT_FOUND': '已删除的会话不存在。',
  'errors.CONVERSATION_RETENTION_EXPIRED': '该会话已超过 30 天保留期，无法恢复。',
  'errors.CONVERSATION_AGENT_DELETED': '所属智能体已删除，请先恢复智能体。',
  'errors.CONVERSATION_NOT_IN_RECYCLE_BIN': '请先将会话移入回收站。',
  'errors.MESSAGE_PARENT_CROSS_CONVERSATION': '父消息不属于当前会话。',
  'errors.DOCUMENT_BUFFER_INVALID': '文件 buffer 无效。',
  'errors.DOCUMENT_EMPTY': '文件内容为空。',
  'errors.DOCUMENT_PARSE_SIZE_LIMIT': '文件超过 {{maxMb}} MB 解析限制。',
  'errors.DOCUMENT_PARSER_INVALID_RESULT': '解析器返回无效结果：{{parserKind}}',
  'errors.DOCUMENT_CSV_EMPTY': 'CSV 文件没有可解析内容：{{objectName}}',
  'errors.DOCUMENT_CSV_COLUMN_LIMIT': 'CSV 列数超过 {{limit}} 限制。',
  'errors.DOCUMENT_CSV_FIELD_LIMIT': 'CSV 单字段超过 {{limit}} 字符限制。',
  'errors.DOCUMENT_CSV_UNCLOSED_QUOTE': 'CSV 包含未闭合的引号字段。',
  'errors.DOCUMENT_JSON_INVALID': 'JSON 文件内容无效：{{objectName}}',
  'errors.DOCUMENT_TEXT_INVALID': '文件不是有效文本：{{objectName}}',
  'errors.OBJECT_ID_REQUIRED': 'objectId 不能为空。',
  'errors.OBJECT_ID_DUPLICATE': 'Duplicate objectId: {{objectId}}',
  'errors.OBJECT_POSITION_DUPLICATE': 'Duplicate Object position: {{position}}',
  'errors.MESSAGE_CONVERSATION_MISMATCH': '消息不属于当前会话。',
  'errors.MESSAGE_OBJECT_ROLE_MISMATCH': '消息角色与 Object 关系角色不匹配。',
  'errors.OBJECT_NOT_READY_OR_INACCESSIBLE': 'Object 未完成解析或不可访问：{{ids}}',
  'errors.OBJECT_NOT_FOUND_OR_INACCESSIBLE': 'Object 不存在或不可访问：{{ids}}',

  'automation.message.expired': '自动任务已结束\n“{{title}}”已到达设定的结束时间，不会再继续自动执行。',
  'automation.message.blocked': '此自动任务需要用户操作，已暂停。',
  'automation.message.paused': '自动任务已暂停，本次执行已停止。',
  'automation.message.cancelled': '自动任务已结束，本次执行已停止。',
  'automation.message.failed': '自动任务本次执行失败。',
  'automation.message.interrupted': '自动任务因应用重启中断，本次执行已结束。',
  'mcp.configuration.oauth': '需要登录 {{displayName}} 账号并完成授权。',
  'mcp.configuration.credential': '需要配置 {{displayName}} 访问凭据。',
  'mcp.configuration.localSetup': '需要先完成 {{displayName}} 本地或自托管服务设置。',
  'mcp.configuration.ready': '无需额外配置，安装后即可连接。',
  'common.avatarAlt': '头像',
  'chat.reasoning.streaming': '正在生成思考内容',
  'turn.minimap.ariaLabel': '对话回合导航',
  'explore.banner.ariaLabel': '发现页横幅',
  'mcp.definition.urlPlaceholder': 'MCP URL（HTTPS）',
  'mcp.auth.bearerToken': 'Bearer Token',
  'mcp.auth.apiKey': 'API Key',
  'common.apiKey': 'API Key',
  'errors.UNSUPPORTED_UI_LOCALE': '暂不支持该界面语言。',
  'errors.LOCALIZATION_PREFERENCE_CHANGE_REQUIRED': '请选择需要更新的语言设置。',
  'errors.USER_IDENTITY_REQUIRED': '当前本地会话缺少用户身份，请重试。',
  'errors.SKILL_DISPLAY_NAME_INVALID': 'Skill 名称最多 120 个字符，且不能包含控制字符。',
  'errors.SKILL_DELETED_CANNOT_BIND': '已删除的 Skill 不能新增关联，请先恢复 Skill。',
  'errors.SKILL_DELETED_RESTORE_REQUIRED': '该 Skill 已删除，请先恢复 Skill。',

  'skills.diagnostic.SKILL_FRONTMATTER_REQUIRED': 'SKILL.md 必须以 YAML frontmatter 开头。',
  'skills.diagnostic.SKILL_FRONTMATTER_UNCLOSED': 'SKILL.md 的 YAML frontmatter 未正确闭合。',
  'skills.diagnostic.SKILL_FRONTMATTER_YAML_INVALID': 'YAML frontmatter 无效：{{detail}}',
  'skills.diagnostic.SKILL_FRONTMATTER_MAPPING_REQUIRED': 'SKILL.md frontmatter 必须是 YAML 映射。',
  'skills.diagnostic.SKILL_FRONTMATTER_EXTENSION_FIELD': '非标准 frontmatter 字段 {{field}} 会保留，但标准运行时投影会忽略它。',
  'skills.diagnostic.SKILL_NAME_REQUIRED': 'name 必须是非空字符串。',
  'skills.diagnostic.SKILL_NAME_UNSAFE': 'name 不能包含路径分隔符、控制字符或路径越界值。',
  'skills.diagnostic.SKILL_NAME_STORAGE_LIMIT_EXCEEDED': 'name 不能超过 {{maxLength}} 个字符。',
  'skills.diagnostic.SKILL_NAME_NON_STANDARD': 'name 可在兼容模式下使用，但 Agent Skills 规范建议仅使用小写 ASCII 字母、数字和单个连字符。',
  'skills.diagnostic.SKILL_ROOT_NAME_MISMATCH': '包根目录名称 {{rootName}} 与 frontmatter 名称 {{name}} 不一致，将以 frontmatter 名称作为 Skill 标识。',
  'skills.diagnostic.SKILL_NAME_IMMUTABLE': '已有 Skill 不能修改 name，请创建新的 Skill。',
  'skills.diagnostic.SKILL_DESCRIPTION_REQUIRED': 'description 必须是非空字符串。',
  'skills.diagnostic.SKILL_DESCRIPTION_STORAGE_LIMIT_EXCEEDED': 'description 不能超过 1024 个字符。',
  'skills.diagnostic.SKILL_DESCRIPTION_TOO_LONG': 'description 不能超过 1024 个字符。',
  'skills.diagnostic.SKILL_METADATA_NON_STANDARD': 'metadata 应为映射；原值会保留，但标准运行时投影会忽略它。',
  'skills.diagnostic.SKILL_METADATA_VALUE_NON_STANDARD': 'metadata.{{key}} 应为字符串；原值会保留，但标准运行时投影会忽略它。',
  'skills.diagnostic.SKILL_METADATA_MAPPING_REQUIRED': 'metadata 必须是字符串键到字符串值的映射。',
  'skills.diagnostic.SKILL_METADATA_VALUE_INVALID': 'metadata 的值必须是字符串。',
  'skills.diagnostic.SKILL_ALLOWED_TOOLS_NON_STANDARD': 'allowed-tools 应为以空格分隔的字符串；原值会保留，但不会作为运行时权限依据。',
  'skills.diagnostic.SKILL_ALLOWED_TOOLS_EXPERIMENTAL': 'allowed-tools 仍是实验字段，不作为运行时权限依据。',
  'skills.diagnostic.SKILL_BODY_REQUIRED': 'SKILL.md 必须包含非空的 Markdown 指令正文。',
  'skills.diagnostic.SKILL_MARKDOWN_SIZE_EXCEEDED': 'SKILL.md 超过配置的安全大小限制。',
  'skills.diagnostic.SKILL_MARKDOWN_LINE_COUNT_HIGH': 'SKILL.md 超过 500 行，建议将详细材料移动到 references/。',
  'skills.diagnostic.SKILL_MARKDOWN_TOKEN_ESTIMATE_HIGH': 'SKILL.md 预计超过 5000 tokens，建议将详细材料移动到 references/。',
  'skills.diagnostic.SKILL_RESOURCE_PATH_NOT_CANONICAL': 'Skill 资源路径必须是相对于 Skill 根目录的规范路径。',
  'skills.diagnostic.SKILL_RESOURCE_PATH_INVALID': 'Skill 资源路径无效：{{detail}}',
  'skills.diagnostic.SKILL_RESOURCE_REFERENCE_MISSING': '当前包中缺少引用的 Skill 资源：{{path}}。Skill 仍可运行，但运行时读取该资源可能失败。',
  'skills.diagnostic.SKILL_RESOURCE_REFERENCE_NON_STANDARD': '资源引用不是安全的 Skill 根目录相对路径，运行时路径策略会拒绝不安全读取。',
  'skills.diagnostic.SKILL_DOCUMENT_INVALID': 'SKILL.md 无法安全创建或运行。',
  'skills.diagnostic.SKILL_DOCUMENT_PARSE_FAILED': 'SKILL.md 解析失败：{{detail}}',
  'skills.diagnostic.SKILL_DISPLAY_NAME_REQUIRED': 'Skill 名称不能为空。',
  'skills.diagnostic.SKILL_DISPLAY_NAME_INVALID': 'Skill 名称最多 120 个字符，且不能包含控制字符。',
  'skills.diagnostic.SKILL_GENERATION_INPUT_INVALID': 'Skill 生成输入验证失败。',
  'skills.diagnostic.SKILL_LICENSE_INVALID': 'license 必须是字符串。',
  'skills.diagnostic.SKILL_COMPATIBILITY_INVALID': 'compatibility 必须是字符串。',
  'skills.diagnostic.SKILL_COMPATIBILITY_TOO_LONG': 'compatibility 超过支持的长度限制。',
  'skills.diagnostic.SKILL_ALLOWEDTOOLS_INVALID': 'allowedTools 必须是字符串。',
  'skills.diagnostic.SKILL_FILE_COUNT_EXCEEDED': 'Skill 文件数量超过配置限制（{{maxFiles}}）。',
  'skills.diagnostic.SKILL_PACKAGE_SIZE_EXCEEDED': 'Skill 包总大小超过配置限制。',
  'skills.diagnostic.SKILL_DUPLICATE_PATH': 'Skill 包中存在重复文件路径：{{path}}。',
  'skills.diagnostic.SKILL_FILE_SIZE_EXCEEDED': 'Skill 文件 {{path}} 超过该文件类型的大小限制。',
  'skills.diagnostic.SKILL_PIPE_REMOTE_SHELL': '检测到远程下载后直接交给 Shell 执行。',
  'skills.diagnostic.SKILL_PRIVILEGED_COMMAND': '检测到高风险系统命令。',
  'skills.diagnostic.SKILL_SECRET_MATERIAL': '检测到疑似凭据或私钥材料。',
  'skills.diagnostic.SKILL_BIDI_CONTROL': '检测到双向文本控制字符。',
  'skills.diagnostic.SKILL_ZERO_WIDTH': '检测到零宽字符。',
  'skills.diagnostic.SKILL_HIDDEN_INSTRUCTION': '检测到 HTML 注释中的隐藏指令。',
  'skills.diagnostic.SKILL_DATA_URL': '检测到内联可执行 data URL。',
  'skills.diagnostic.SKILL_PATH_INVALID': 'Skill 文件路径无效。',
  'skills.diagnostic.SKILL_PATH_ABSOLUTE': 'Skill 文件禁止使用绝对路径。',
  'skills.diagnostic.SKILL_PATH_TRAVERSAL': 'Skill 文件路径禁止越过 Skill 根目录。',
  'skills.diagnostic.SKILL_PATH_SEGMENT_INVALID': 'Skill 文件路径包含无效片段。',
  'skills.diagnostic.SKILL_PATH_HIDDEN_SEGMENT': 'Skill 文件路径不能包含隐藏文件或隐藏目录。',
  'skills.diagnostic.SKILL_PATH_DEPTH_EXCEEDED': 'Skill 文件路径超过最大目录层级。',
  'skills.diagnostic.SKILL_PATH_TOO_LONG': 'Skill 文件路径过长。',
  'skills.diagnostic.SKILL_SKILL_DEPENDENCY_UNAVAILABLE': '必需的 Skill 依赖不可用：{{key}}。',
  'skills.diagnostic.SKILL_TOOL_DEPENDENCY_UNAVAILABLE': '必需的 Tool 依赖不可用：{{key}}。',
  'skills.diagnostic.SKILL_MCP_DEPENDENCY_UNAVAILABLE': '必需的 MCP 依赖不可用：{{key}}。',
  'skills.diagnostic.SKILL_CAPABILITY_UNSUPPORTED': '系统能力目录中不存在该能力：{{capabilityId}}。',
  'skills.diagnostic.SKILL_CAPABILITY_UNAVAILABLE': '当前没有可用 Tool 提供该能力：{{capabilityId}}。',
  'skills.diagnostic.SKILL_CAPABILITY_CONFIRMATION_REQUIRED': '能力 {{capabilityId}} 必须要求用户确认。',
  'skills.diagnostic.SKILL_CAPABILITY_CONCRETE_TOOL': '不能把具体 Tool ID 作为 Skill Capability：{{rawValue}}。{{candidates}}',
  'skills.diagnostic.SKILL_CAPABILITY_AMBIGUOUS': '能力名称无法唯一匹配：{{rawValue}}。{{candidates}}',
  'skills.diagnostic.SKILL_CAPABILITY_UNRESOLVED': '系统能力目录中未识别该能力：{{rawValue}}。{{candidates}}',

  'errors.BRANCH_USER_ID_REQUIRED': '创建分支时缺少用户信息。',
  'errors.BRANCH_CONVERSATION_ID_REQUIRED': '创建分支时缺少会话信息。',
  'errors.BRANCH_FROM_MESSAGE_ID_REQUIRED': '创建分支时缺少起点消息。',
  'errors.BRANCH_REQUEST_ID_REQUIRED': '创建分支时缺少 requestId。',

  'chat.message.turnFailed': '本轮运行失败，请稍后重试。',

  'common.cover': '封面',
  'common.status.pending': '等待中',
  'common.toggle.on': '开',
  'common.toggle.off': '关',
  'agents.knowledge.chunkCount': '{{count}} 个分块',
  'skills.create.skillPackage': 'Skill 包',
  'skills.create.repositoryUrl': '仓库 URL',
  'artifact.kind.codeProject': '代码项目',
  'artifact.kind.word': 'Word 文档',
  'artifact.kind.excel': 'Excel 表格',

  'errors.AUTHENTICATED_USER_REQUIRED': '需要本地用户会话。',
  'errors.RENDER_REQUEST_OBJECT_REQUIRED': '渲染请求必须是对象。',
  'errors.RENDER_TOOL_NAME_REQUIRED': '渲染请求缺少 toolName。',
  'errors.RENDER_PAYLOAD_OBJECT_REQUIRED': '渲染 payload 必须是对象。',
  'errors.RENDER_PAYLOAD_ARRAY_FORBIDDEN': '渲染 payload 不能是数组。',
  'errors.RENDER_FILENAME_STRING_REQUIRED': '渲染文件名必须是字符串。',
  'errors.RENDER_TITLE_STRING_REQUIRED': '渲染标题必须是字符串。',
  'errors.RENDER_META_OBJECT_REQUIRED': '渲染元数据必须是对象。',
  'errors.RENDER_BINARY_BUFFER_REQUIRED': '渲染交付需要非空二进制数据。',
  'errors.RENDER_PLANNING_ARGS_OBJECT_REQUIRED': '渲染规划参数必须是对象。',
  'errors.RENDER_INSTRUCTION_OR_PLAN_REQUIRED': '渲染需要 instruction 或 plan。',
  'errors.RENDER_SOURCE_OBJECT_REQUIRED': '渲染 source 必须是对象。',
  'errors.RENDER_REQUIREMENTS_OBJECT_REQUIRED': '渲染 requirements 必须是对象。',
  'errors.RENDER_OUTPUT_FIELD_UNSUPPORTED': '渲染输出固定进入对象目录，不支持 output 字段。',
  'errors.ZIP_ARGS_OBJECT_REQUIRED': 'ZIP 参数必须是对象。',
  'errors.ZIP_FILES_REQUIRED': 'ZIP 渲染需要文件。',
  'errors.DOCX_PAYLOAD_OBJECT_REQUIRED': 'DOCX payload 必须是对象。',
  'errors.DOCX_PAYLOAD_EMPTY': 'DOCX payload 为空。',
  'errors.DOCX_BLOCK_TYPE_REQUIRED': 'DOCX block.type 为必填项。',
  'errors.DOCX_IMAGE_BASE64_REQUIRED': 'DOCX 图片块缺少 base64 内容。',
  'errors.DOCX_TABLE_ROWS_ARRAY_REQUIRED': 'DOCX 表格 rows 必须是数组。',
  'errors.RUNTIME_WORKSPACE_PERSISTENCE_UNAVAILABLE': '运行时工作区持久化不可用。',
  'errors.WORKSPACE_NOT_FOUND': '工作区不存在。',
  'errors.WORKSPACE_UPDATE_INVALID': '工作区更新产生了无效状态。',
  'errors.WORKSPACE_DEFAULT_UPDATE_INVALID': '默认工作区更新产生了无效状态。',
  'errors.WORKSPACE_PERSISTENCE_UNAVAILABLE': '工作区持久化不可用。',
  'errors.AGENT_PROFILE_IMAGE_KIND_INVALID': '资料图片类型无效。',
  'errors.AGENT_PROFILE_IMAGE_NOT_FOUND': '资料图片不存在。',
  'errors.PUBLIC_AGENT_NOT_FOUND': '智能体不存在或未公开。',
  'errors.PUBLIC_FREE_AGENT_NOT_FOUND': '公开免费智能体不存在。',
  'errors.PUBLIC_PAID_AGENT_NOT_FOUND': '公开付费智能体不存在。',
  'errors.AGENT_RELATION_NOT_FOUND': '智能体关系不存在。',
  'errors.MCP_AUTHENTICATED_PRINCIPAL_REQUIRED': '需要已认证的 MCP 主体。',
  'errors.MCP_AGENT_ACCESS_DENIED': '当前用户无权访问此智能体。',
  'errors.CONVERSATION_ID_REQUIRED': '缺少 conversationId，请先创建会话。',

  'errors.TOOL_NOT_FOUND': '工具 {{toolName}} 不存在。',
  'errors.DOCUMENT_TYPE_UNSUPPORTED': '不支持的文档类型：{{objectName}}（{{mimeType}}）。',
  'errors.RENDER_TOOL_CANNOT_HANDLE_REQUEST': '渲染工具 {{toolName}} 无法处理此请求。',
  'errors.RENDER_TOOL_NOT_FOUND': '渲染工具 {{toolName}} 不存在。',
  'errors.RENDER_TOOL_DISABLED': '渲染工具 {{toolName}} 已停用。',
  'errors.DOCX_TEXT_LIMIT_EXCEEDED': 'DOCX 文本超过 {{limit}} 字符限制。',
  'errors.DOCX_BLOCK_LIMIT_EXCEEDED': 'DOCX 内容块超过 {{limit}} 个限制。',
  'errors.DOCX_TABLE_ROW_LIMIT_EXCEEDED': 'DOCX 表格行数超过 {{limit}} 行限制。',
  'errors.DOCX_TABLE_COLUMN_LIMIT_EXCEEDED': 'DOCX 表格列数超过 {{limit}} 列限制。',

  'errors.SKILL_NOT_BINDABLE': 'Skill {{skillId}} 当前状态不可绑定。',
  'errors.ENABLED_SKILL_MUST_BE_ACTIVE_AND_CLEAR': '启用的 Skill {{skillId}} 必须处于可用状态并通过安全检查。',
  'errors.PINNED_VERSION_REQUIRED': 'Skill {{skillId}} 需要指定固定版本。',
  'errors.PINNED_VERSION_INVALID': 'Skill {{skillId}} 的固定版本无效。',
  'errors.ENABLED_SESSION_SKILL_MUST_BE_ACTIVE_AND_CLEAR': '会话中启用的 Skill {{skillId}} 必须处于可用状态并通过安全检查。',
  'errors.SESSION_SKILL_VERSION_INVALID': 'Skill {{skillId}} 选择的会话版本无效。',
  'errors.SKILL_GENERATION_PAUSED': 'Skill 生成已暂停：{{reason}}。',
  'errors.SKILL_IMPORT_ZIP_INVALID': 'Skill ZIP 包无效：{{reason}}。',
  'errors.OBJECT_REFERENCE_DUPLICATE': '对象 {{objectId}} 被重复引用。',
  'errors.OBJECT_POSITION_INVALID': '对象 {{objectId}} 的位置无效。',
  'errors.MCP_IMPORT_TRANSPORT_AMBIGUOUS': 'MCP 服务 {{server}} 同时指定了多种传输方式。',
  'errors.MCP_IMPORT_TRANSPORT_REQUIRED': 'MCP 服务 {{server}} 缺少传输配置。',
  'errors.MCP_IMPORT_ARGS_INVALID': 'MCP 服务 {{server}} 包含无效命令参数。',
  'errors.MCP_IMPORT_COMMAND_INVALID': 'MCP 服务 {{server}} 包含无效命令。',
  'errors.OBJECT_TOO_LARGE': '对象过大（{{sizeBytes}} 字节；最大 {{maxBytes}} 字节）。',
};
